function image_smooth1(orimage,tgcanv,tgw,tgh){var orw=orimage.naturalWidth;var orh=orimage.naturalHeight;var orcanv=document.createElement('canvas');orcanv.width=orw;orcanv.height=orh;orcanv.getContext('2d').drawImage(orimage,0,0,orw,orh);var ratio_w=orw/tgw;var ratio_h=orh/tgh;var ratio_w_half=Math.ceil(ratio_w/2);var ratio_h_half=Math.ceil(ratio_h/2);var orData=orcanv.getContext("2d").getImageData(0,0,orw,orh).data;var tgImage=tgcanv.getContext("2d").getImageData(0,0,tgw,tgh);var tgData=tgImage.data;var i,seq,r,g,b,a,cx,cy,dx,dy;var sq_dy,w,alen,blen,xx,yy;var w,weight,weights;for(var j=0;j<tgh;j++){for(i=0;i<tgw;i++){weight=0;weights=0;r=0;g=0;b=0;a=0;seq=(i+j*tgw)*4;cy=(j+0.5)*ratio_h;alen=(j+1)*ratio_h;for(yy=Math.floor(j*ratio_h);yy<alen;yy++){dy=Math.abs(cy-(yy+0.5))/ratio_h_half;cx=(i+0.5)*ratio_w;sq_dy=dy*dy;blen=(i+1)*ratio_w;for(xx=Math.floor(i*ratio_w);xx<blen;xx++){dx=Math.abs(cx-(xx+0.5))/ratio_w_half;w=Math.sqrt(sq_dy+dx*dx);if(w>=-1&&w<=1){weight=2*w*w*w-3*w*w+1;if(weight>0){dx=4*(xx+yy*orw);r+=weight*orData[dx];g+=weight*orData[dx+1];b+=weight*orData[dx+2];a+=weight*orData[dx+3];weights+=weight;}}}}
tgData[seq]=r/weights;tgData[seq+1]=g/weights;tgData[seq+2]=b/weights;tgData[seq+3]=a/weights;}}
tgcanv.getContext("2d").putImageData(tgImage,0,0);}
function image_smooth2(orimage,tgcanv,tw,th){var sw=orimage.naturalWidth;var sh=orimage.naturalHeight;var ratio_w=tw/sw;var ratio_h=th/sh;var orcanv=document.createElement('canvas');orcanv.width=sw;orcanv.height=sh;orcanv.getContext('2d').drawImage(orimage,0,0,sw,sh);var sqScale=ratio_w*ratio_h;var sx=0,sy=0,sIndex=0;var tx=0,ty=0,yIndex=0,tIndex=0;var tX=0,tY=0;var w=0,nw=0,wx=0,nwx=0,wy=0,nwy=0;var crossX=false;var crossY=false;var sBuffer=orcanv.getContext('2d').getImageData(0,0,sw,sh).data;var tBuffer=new Float32Array(4*sw*sh);var sR=0,sG=0,sB=0,sA=0;for(sy=0;sy<sh;sy++){ty=sy*ratio_h;tY=0|ty;yIndex=4*tY*tw;crossY=(tY!=(0|ty+ratio_h));if(crossY){wy=(tY+1-ty);nwy=(ty+ratio_h-tY-1);}
for(sx=0;sx<sw;sx++,sIndex+=4){tx=sx*ratio_w;tX=0|tx;tIndex=yIndex+tX*4;crossX=(tX!=(0|tx+ratio_w));if(crossX){wx=(tX+1-tx);nwx=(tx+ratio_w-tX-1);}
sR=sBuffer[sIndex];sG=sBuffer[sIndex+1];sB=sBuffer[sIndex+2];sA=sBuffer[sIndex+3];if(!crossX&&!crossY){tBuffer[tIndex]+=sR*sqScale;tBuffer[tIndex+1]+=sG*sqScale;tBuffer[tIndex+2]+=sB*sqScale;tBuffer[tIndex+3]+=sA*sqScale;}
else if(crossX&&!crossY){w=wx*ratio_w;tBuffer[tIndex]+=sR*w;tBuffer[tIndex+1]+=sG*w;tBuffer[tIndex+2]+=sB*w;tBuffer[tIndex+3]+=sA*w;nw=nwx*ratio_w
tBuffer[tIndex+4]+=sR*nw;tBuffer[tIndex+5]+=sG*nw;tBuffer[tIndex+6]+=sB*nw;tBuffer[tIndex+7]+=sA*nw;}
else if(crossY&&!crossX){w=wy*ratio_h;tBuffer[tIndex]+=sR*w;tBuffer[tIndex+1]+=sG*w;tBuffer[tIndex+2]+=sB*w;tBuffer[tIndex+3]+=sA*w;nw=nwy*ratio_h
tBuffer[tIndex+4*tw]+=sR*nw;tBuffer[tIndex+4*tw+1]+=sG*nw;tBuffer[tIndex+4*tw+2]+=sB*nw;tBuffer[tIndex+4*tw+3]+=sA*nw;}
else{w=wx*wy;tBuffer[tIndex]+=sR*w;tBuffer[tIndex+1]+=sG*w;tBuffer[tIndex+2]+=sB*w;tBuffer[tIndex+3]+=sA*w;nw=nwx*wy;tBuffer[tIndex+4]+=sR*nw;tBuffer[tIndex+5]+=sG*nw;tBuffer[tIndex+6]+=sB*nw;tBuffer[tIndex+7]+=sA*nw;nw=wx*nwy;tBuffer[tIndex+4*tw]+=sR*nw;tBuffer[tIndex+4*tw+1]+=sG*nw;tBuffer[tIndex+4*tw+2]+=sB*nw;tBuffer[tIndex+4*tw+3]+=sA*nw;nw=nwx*nwy;tBuffer[tIndex+4*tw+4]+=sR*nw;tBuffer[tIndex+4*tw+5]+=sG*nw;tBuffer[tIndex+4*tw+6]+=sB*nw;tBuffer[tIndex+4*tw+7]+=sA*nw;}}}
var imgRes=tgcanv.getContext("2d").getImageData(0,0,tw,th);var tByteBuffer=imgRes.data;var alen=tw*th;var pxIndex=0;for(tIndex=0;pxIndex<alen;tIndex+=4,pxIndex++){tByteBuffer[tIndex]=Math.ceil(tBuffer[tIndex]);tByteBuffer[tIndex+1]=Math.ceil(tBuffer[tIndex+1]);tByteBuffer[tIndex+2]=Math.ceil(tBuffer[tIndex+2]);tByteBuffer[tIndex+3]=Math.ceil(tBuffer[tIndex+3]);}
tgcanv.getContext("2d").putImageData(imgRes,0,0);}
