function do_afterFirstAllLoaded(){Action.aniLocking=false;}
function go_next(bool){if(aniSvg.smcState=="catimage"){if(bool==true)PageInfo.reset_pageNext();go_next2();}
else{aniSvg.go_swingChange(0,8,"next");}}
function go_next2(){Action.loaded=0;Action.loadto=0;var aaa=FileInfo.cimgFilePath(PageInfo.prevPage,"s","","*");if(aaa[0]==""){SmcObj.drawL=1;}
else{Action.loadto++;SmcObj.drawL=0;}
var bbb=FileInfo.cimgFilePath(PageInfo.prevPage+1,"s","","*");if(bbb[0]==""){SmcObj.drawR=1;}
else{Action.loadto++;SmcObj.drawR=0;}
if(SmcObj.drawL===0){catImageLN=new Image();if(ServerInfo.applyCipher===true){load_cipherImage('btn',0,aaa[0],go_nextLNCipher);}
else{catImageLN.src=aaa[0];catImageLN.onload=go_next3;}}
if(SmcObj.drawR===0){catImageRN=new Image();if(ServerInfo.applyCipher===true){load_cipherImage('btn',0,bbb[0],go_nextRNCipher);}
else{catImageRN.src=bbb[0];catImageRN.onload=go_next3;}}}
function go_nextLNCipher(skd,npage,urlsrc){catImageLN.src=urlsrc;catImageLN.onload=go_next3;}
function go_nextRNCipher(skd,npage,urlsrc){catImageRN.src=urlsrc;catImageRN.onload=go_next3;}
function go_next3(){Action.loaded++;if(Action.loadto==Action.loaded){Action.drawCondition=2;prepare_turnover();if(ScreenInfo.onesmc==true){AniObj.seq=0;next_animateOneR();smcDiv.style.visibility="hidden";AniObj.seq=0;AniObj.timer=setInterval(next_animateOneR,AniObj.transInterval);}
else{AniObj.seq=0;next_animateR();smcDiv.style.visibility="hidden";AniObj.seq=0;AniObj.timer=setInterval(next_animateR,AniObj.transInterval);}}}
function next_animateOneR(){clear_canvas();var percent=AniObj.transPercent[AniObj.seq];if(SmcObj.drawL==1){cntx.fillStyle=ScreenInfo.blankColor;cntx.fillRect(smRect.x+ScreenInfo.smImageWidth*percent,smRect.y,ScreenInfo.smImageWidth*percent,ScreenInfo.smImageHeight);}
else{cntx.drawImage(catImageLN,0,0,ScreenInfo.smImageOriWidth*(1-percent),ScreenInfo.smImageOriHeight,smRect.x+ScreenInfo.smImageWidth*percent,smRect.y,ScreenInfo.smImageWidth*(1-percent),ScreenInfo.smImageHeight);}
AniObj.seq++;if(AniObj.seq==AniObj.transLen-1){clearInterval(AniObj.timer);after_nextRanimateComplete();}}
function next_animateR(){clear_canvas();var percent=AniObj.transPercent[AniObj.seq];if(SmcObj.drawL===1){cntx.fillStyle=ScreenInfo.blankColor;cntx.fillRect(smRect.x+ScreenInfo.smImageWidth*percent,smRect.y,ScreenInfo.smImageWidth*percent,ScreenInfo.smImageHeight);}
else{cntx.drawImage(catImageLN,0,0,ScreenInfo.smImageOriWidth*(1-percent),ScreenInfo.smImageOriHeight,smRect.x+ScreenInfo.smImageWidth*percent,smRect.y,ScreenInfo.smImageWidth*(1-percent),ScreenInfo.smImageHeight);}
if(SmcObj.drawR===1){cntx.fillStyle=ScreenInfo.blankColor;cntx.fillRect(smRect.centerPt.x+ScreenInfo.smImageWidth*(1-percent),smRect.y,ScreenInfo.smImageWidth*percent,ScreenInfo.smImageHeight);}
else{cntx.drawImage(catImageRN,ScreenInfo.smImageOriWidth*percent,0,ScreenInfo.smImageOriWidth*(1-percent),ScreenInfo.smImageOriHeight,smRect.centerPt.x,smRect.y,ScreenInfo.smImageWidth*(1-percent),ScreenInfo.smImageHeight);}
AniObj.seq++;if(AniObj.seq===AniObj.transLen-1){clearInterval(AniObj.timer);after_nextRanimateComplete();}}
function after_nextRanimateComplete(){Action.loaded=0;Action.loadto=0;var aaa=FileInfo.cimgFilePath(PageInfo.currentPage,"s","","*");if(aaa[0]==""){SmcObj.drawL=1;}
else{Action.loadto++;SmcObj.drawL=0;}
var bbb=FileInfo.cimgFilePath(PageInfo.currentPage+1,"s","","*");if(bbb[0]==""){SmcObj.drawR=1;}
else{Action.loadto++;SmcObj.drawR=0;}
if(SmcObj.drawL===0){catImageLN=new Image();if(ServerInfo.applyCipher===true){load_cipherImage('btn',0,aaa[0],go_prevLNCipher);}
else{catImageLN.src=aaa[0];catImageLN.onload=go_next4;}}
if(SmcObj.drawR===0){catImageRN=new Image();if(ServerInfo.applyCipher===true){load_cipherImage('btn',0,bbb[0],go_prevRNCipher);}
else{catImageRN.src=bbb[0];catImageRN.onload=go_next4;}}}
function go_prevLNCipher(skd,npage,urlsrc){catImageLN.src=urlsrc;catImageLN.onload=go_next4;}
function go_prevRNCipher(skd,npage,urlsrc){catImageRN.src=urlsrc;catImageRN.onload=go_next4;}
function go_next4(){Action.loaded++;if(Action.loadto==Action.loaded){AniObj.seq=0;if(ScreenInfo.onesmc==true)AniObj.timer=setInterval(next_animateOneL,AniObj.transInterval);else AniObj.timer=setInterval(next_animateL,AniObj.transInterval);}}
function next_animateOneL(){clear_canvas();var percent=transPercent[AniObj.seq];if(SmcObj.drawL==1){cntx.fillStyle=ScreenInfo.blankColor;cntx.fillRect(smRect.x+ScreenInfo.smImageWidth*(1-percent),smRect.y,ScreenInfo.smImageWidth*percent,ScreenInfo.smImageHeight);}
else{cntx.drawImage(catImageLN,0,0,ScreenInfo.smImageOriWidth*percent,ScreenInfo.smImageOriHeight,smRect.x+ScreenInfo.smImageWidth*(1-percent),smRect.y,ScreenInfo.smImageWidth*percent,ScreenInfo.smImageHeight);}
AniObj.seq++;if(AniObj.seq==AniObj.transLen){clearInterval(AniObj.timer);finish_turnover();}}
function next_animateL(){clear_canvas();var percent=AniObj.transPercent[AniObj.seq];if(SmcObj.drawL==1){cntx.fillStyle=ScreenInfo.blankColor;cntx.fillRect(smRect.x+ScreenInfo.smImageWidth*(1-percent),smRect.y,ScreenInfo.smImageWidth*percent,ScreenInfo.smImageHeight);}
else{cntx.drawImage(catImageLN,0,0,ScreenInfo.smImageOriWidth*percent,ScreenInfo.smImageOriHeight,smRect.x+ScreenInfo.smImageWidth*(1-percent),smRect.y,ScreenInfo.smImageWidth*percent,ScreenInfo.smImageHeight);}
if(SmcObj.drawR==1){cntx.fillStyle=ScreenInfo.blankColor;cntx.fillRect(smRect.centerPt.x,smRect.y,ScreenInfo.smImageWidth*percent,ScreenInfo.smImageHeight);}
else{cntx.drawImage(catImageRN,ScreenInfo.smImageOriWidth*(1-percent),0,ScreenInfo.smImageOriWidth*percent,ScreenInfo.smImageOriHeight,smRect.centerPt.x,smRect.y,ScreenInfo.smImageWidth*percent,ScreenInfo.smImageHeight);}
AniObj.seq++;if(AniObj.seq==AniObj.transLen){clearInterval(AniObj.timer);finish_turnover();}}
function go_prev(bool){if(aniSvg.smcState=="catimage"){if(bool==true)PageInfo.reset_pagePrev();go_next2();}
else{aniSvg.go_swingChange(0,7,"prev");}}
function go_direct(n){if(aniSvg.smcState=="catimage"){n=PageInfo.get_directPageNo(n);if(n<1)n=1;PageInfo.prevPage=PageInfo.currentPage;PageInfo.currentPage=n;go_next2();}
else{aniSvg.go_direct(n);}}
function go_catimageState(n){n=PageInfo.get_directPageNo(n);if(n<1)n=1;PageInfo.prevPage=PageInfo.currentPage;PageInfo.currentPage=n;load_smc();}
function prepare_turnover(){if(glassesSvg!=undefined)unload_glasses();if(soundctrlSvg!=undefined)unload_soundcontrol();AniObj.seq=0;cntx.globalAlpha=1;if(mainCnv.width!=winRect.width){maincnvDiv.style.width=winRect.width+"px";maincnvDiv.style.height=winRect.height+"px";mainCnv.width=winRect.width;mainCnv.height=winRect.height;}
SmcObj.prepare_turnover();}
function finish_turnover(){SmcObj.finish_turnover();}
function finish_turnover2(){smcDiv.style.visibility="visible";clear_canvas();mainCnv.width=1;mainCnv.height=1;maincnvDiv.style.width="1px";maincnvDiv.style.height="1px";Action.drawCondition=0;if(MoveInfo.pairEnlarge==true)Action.set_togetherEnlarge();MoveInfo.show_pageNumber();CoverObj.set_cover();if(Action.mainState=="slide"){if(SmcObj.nextPermission("wheel")==false||PermitMan.access_memberZone(-1,"wheel")==false){Action.mainState="stop";}
else if(MoveInfo.loadLinkAtSlide==true){SmcObj.show_linkData();}
if(Action.mainState=="slide"){setTimeout("go_next(true)",MoveInfo.slideIntervalSM);return;}}
if(Action.mainState=="stop")Action.mainState="normal";SmcObj.show_outData();ScreenMan.finish_turnover();Action.aniLocking=false;}
function init_smc2(){PermitMan.aniSvg=true;anicnvDiv.style.visibility="visible";anicnvDiv.style.zIndex="10";anicnvDiv.innerHTML="<canvas id='anicnv' width='"+stageWidth+"' height='"+stageHeight+"'></canvas>";try{gl=document.getElementById("anicnv").getContext('experimental-webgl');if(!gl)gl=document.getElementById("anicnv").getContext('webgl');}
catch(e){alert("canvas webgl getContext() error : "+e.toString());}
gl.viewportWidth=stageWidth;gl.viewportHeight=stageHeight;aniSvg.pc=new PagingCont();aniSvg.pc.totalArticles=PageInfo.cataPages;aniSvg.pc.set_articlesOnPage(20);aniSvg.pc.set_currentPage(1);aniSvg.pMatrix=new Float32Array(16);aniSvg.perspectiveMatrix(20,gl.viewportWidth/gl.viewportHeight,0.1,100.0);aniSvg.mvMatrix=new Float32Array(16);aniSvg.prepareMatrix();aniSvg.normalMatrix=new Float32Array(9);if(aniSvg.init_shaders()===false)return;aniSvg.init_buffers();gl.enable(gl.DEPTH_TEST);aniSvg.init_textures();}
aniSvg={timer:undefined,drawInterval:30,changeInterval:15,seq:0,loaded:0,loadto:0,smcState:'stop',firstLoading:true,catTexture:[],arVertex:[],cnvPoint:[],shaderProgram:undefined,pMatrix:undefined,mvMatrix:undefined,normalMatrix:undefined,cubeVertexPositionBuffer:undefined,cubeVertexNormalBuffer:undefined,cubeVertexTextureCoordBuffer:undefined,cubeVertexIndexBuffer:undefined,ySpeed:-0.4,xRot:10.0,yRot:0.0,normalAlpha:1.0,overAlpha:0.95,pc:undefined,mouseDragged:false,befX:0,cnvPtLen:0,overIndex:-1};aniSvg.do_afterAllLoaded=function(){if(aniSvg.smcState==="stop"){aniSvg.smcState="swing";aniSvg.timer=setInterval(aniSvg.drawScene,aniSvg.drawInterval);if(aniSvg.firstLoading===true){aniSvg.drawScene();if(CataInfo.incview==="d"){anicnvDiv.addEventListener("mousedown",aniSvg.do_mouseDown,false);anicnvDiv.addEventListener("mousemove",aniSvg.do_mouseMove,false);anicnvDiv.addEventListener("mouseup",aniSvg.do_mouseUp,false);}
else{anicnvDiv.addEventListener("touchstart",aniSvg.do_touchStart,false);anicnvDiv.addEventListener("touchmove",aniSvg.do_touchMove,false);anicnvDiv.addEventListener("touchend",aniSvg.do_touchEnd,false);}
aniSvg.firstLoading=false;}}
else if(aniSvg.smcState==="swingchange"){aniSvg.timer=setInterval(aniSvg.swingchange_animateRear,aniSvg.changeInterval);}}
aniSvg.go_direct=function(n){aniSvg.go_swingChange(n,9,"direct");}
aniSvg.go_swingChange=function(n,drawC,s){if(aniSvg.get_swingPermission(s,n)==false){Action.aniLocking=false;return;}
Action.drawCondition=drawC;tempN=n;aniSvg.smcState="swingchange";aniSvg.timer=setInterval(aniSvg.swingchange_animateFrt,aniSvg.changeInterval);}
aniSvg.go_swingPage=function(skd,n){if(skd==="first")aniSvg.pc.set_currentPage(1);else if(skd==="prev")aniSvg.pc.set_currentPage(aniSvg.pc.currentPage-1);else if(skd==="next")aniSvg.pc.set_currentPage(aniSvg.pc.currentPage+1);else if(skd==="last")aniSvg.pc.set_currentPage(aniSvg.pc.finalPage);else aniSvg.pc.set_currentPage(n);aniSvg.init_textures();}
aniSvg.swingchange_animateFrt=function(){if(aniSvg.ySpeed>0)aniSvg.ySpeed+=0.8;else aniSvg.ySpeed-=0.8;aniSvg.normalAlpha-=0.1;if(aniSvg.normalAlpha<=0){clearInterval(aniSvg.timer);aniSvg.timer=undefined;if(Action.drawCondition===7)aniSvg.go_swingPage("prev",0);else if(Action.drawCondition===8)aniSvg.go_swingPage("next",0);else{aniSvg.go_swingPage("direct",aniSvg.pc.get_pageFromArticle(tempN-1));}}}
aniSvg.swingchange_animateRear=function(){if(aniSvg.ySpeed>0)aniSvg.ySpeed-=0.8;else aniSvg.ySpeed+=0.8;aniSvg.normalAlpha+=0.1;if(aniSvg.normalAlpha>=1.0){clearInterval(aniSvg.timer);aniSvg.timer=undefined;aniSvg.smcState="swing";Action.drawCondition=0;Action.aniLocking=false;MoveInfo.show_pageNumber();}}
aniSvg.set_rotateSpeed=function(time,distance){var fn=-distance/time*3;if(fn>2)aniSvg.ySpeed=2;else if(fn<-2)aniSvg.ySpeed=-2;else if(-0.3<fn&&fn<0.3)return false;else aniSvg.ySpeed=fn;return true;}
aniSvg.get_pageFromShowkind=function(){if(aniSvg.smcState==="catimage")return PageInfo.get_pageshowString(PageInfo.currentPage);return PageInfo.get_pageFromShowkind(aniSvg.pc.startArticle+1)+"-"+PageInfo.get_pageFromShowkind(aniSvg.pc.finalArticle+1);}
aniSvg.onresize_func=function(){document.getElementById("anicnv").width=stageWidth;document.getElementById("anicnv").height=stageHeight;gl.viewportWidth=stageWidth;gl.viewportHeight=stageHeight;aniSvg.pMatrix=new Float32Array(16);aniSvg.perspectiveMatrix(20,gl.viewportWidth/gl.viewportHeight,0.1,100.0);aniSvg.make_stopState();aniSvg.drawScene();}
aniSvg.make_stopState=function(){if(aniSvg.timer){clearInterval(aniSvg.timer);aniSvg.timer=undefined;}
aniSvg.smcState="stop";}
aniSvg.make_swingState=function(){aniSvg.timer=setInterval(aniSvg.drawScene,aniSvg.drawInterval);aniSvg.smcState="swing";}
aniSvg.make_catimageState=function(n){n=PageInfo.get_directPageNo(n);if(n<1)n=1;PageInfo.prevPage=PageInfo.currentPage;PageInfo.currentPage=n;Action.mouseDownBlock=true;SmcObj.onload_func2();smcDiv.style.visibility="visible";linkoutDiv.style.visibility="visible";aniSvg.smcState="catimage";}
aniSvg.escape_catimageState=function(){SmcObj.unload_func();smcDiv.style.visibility="hidden";linkoutDiv.style.visibility="hidden";MoveInfo.show_pageNumber();}
aniSvg.get_swingPermission=function(smove,n){if(smove==="next"&&aniSvg.pc.currentPage===aniSvg.pc.totalPages)return false;else if(smove==="prev"&&aniSvg.pc.currentPage===1)return false;else if(smove==="direct"&&aniSvg.pc.contain_article(n)===true)return false;return true;}
aniSvg.do_mouseDown=function(e){clickX=e.clientX;clickY=e.clientY;var now=new Date();Action.touchStartTime=now.getTime();Action.do_mouseDown("smc",e);}
aniSvg.do_mouseMove=function(e){var cx=e.clientX;var cy=e.clientY;if(aniSvg.smcState==="catimage")return;aniSvg.befX=cx;if(Action.mouseDowned===true){if(aniSvg.mouseDragged===false)aniSvg.mouseDragged=true;var ang=aniSvg.xRot+(cy-clickY)/300;if(ang>20)ang=20;else if(ang<-35)ang=-35;aniSvg.xRot=ang;if(aniSvg.smcState==="stop")aniSvg.drawScene();return;}
var overidx=-1;for(var i=0;i<aniSvg.cnvPtLen;i++){if(aniSvg.isPointInRectangle(cx,cy,aniSvg.cnvPoint[i])===true){overidx=i;break;}}
aniSvg.overIndex=overidx;if(overidx===-1){if(aniSvg.timer==undefined)aniSvg.make_swingState();}
else{aniSvg.make_stopState();aniSvg.drawScene();}}
aniSvg.do_mouseUp=function(e){aniSvg.mouseDragged=false;if(aniSvg.smcState==="catimage"){aniSvg.escape_catimageState();aniSvg.make_stopState();return;}
if(aniSvg.smcState==="swing"){var now=new Date();aniSvg.set_rotateSpeed(now.getTime()-Action.touchStartTime,aniSvg.befX-clickX);return;}
Action.do_mouseUp("smc",e);if(aniSvg.overIndex===-1)return;var n=aniSvg.pc.startArticle+aniSvg.overIndex+1;aniSvg.make_catimageState(n);}
aniSvg.do_touchStart=function(e){clickX=e.touches[0].clientX;clickY=e.touches[0].clientY;befX=clickX,befY=clickY;var now=new Date();Action.touchStartTime=now.getTime();Action.do_touchStart("smc",e);}
aniSvg.do_touchMove=function(e){befX=e.touches[0].clientX;befY=e.touches[0].clientY;if(aniSvg.smcState==="catimage")return;if(Action.mouseDowned===true){if(aniSvg.mouseDragged===false)aniSvg.mouseDragged=true;var ang=aniSvg.xRot+(befY-clickY)/300;if(ang>20)ang=20;else if(ang<-35)ang=-35;aniSvg.xRot=ang;if(aniSvg.smcState==="stop")aniSvg.drawScene();}}
aniSvg.do_touchEnd=function(){var overidx=-1;for(var i=0;i<aniSvg.cnvPtLen;i++){if(aniSvg.isPointInRectangle(befX,befY,aniSvg.cnvPoint[i])===true){overidx=i;break;}}
if(overidx===-1){if(aniSvg.smcState==="catimage")aniSvg.escape_catimageState();if(aniSvg.timer==undefined)aniSvg.make_swingState();else{var now=new Date();aniSvg.set_rotateSpeed(now.getTime()-Action.touchStartTime,befX-clickX);}}
else{aniSvg.overIndex=overidx;aniSvg.make_stopState();var n=aniSvg.pc.startArticle+aniSvg.overIndex+1;aniSvg.make_catimageState(n);}}
aniSvg.init_shaders=function(){var fragmentShader=aniSvg.get_fragmentShader();var vertexShader=aniSvg.get_vertexShader();aniSvg.shaderProgram=gl.createProgram();gl.attachShader(aniSvg.shaderProgram,vertexShader);gl.attachShader(aniSvg.shaderProgram,fragmentShader);gl.linkProgram(aniSvg.shaderProgram);if(!gl.getProgramParameter(aniSvg.shaderProgram,gl.LINK_STATUS)){alert("Could not initialise shaders");return false;}
gl.useProgram(aniSvg.shaderProgram);aniSvg.shaderProgram.vertexPositionAttribute=gl.getAttribLocation(aniSvg.shaderProgram,"aVertexPosition");gl.enableVertexAttribArray(aniSvg.shaderProgram.vertexPositionAttribute);aniSvg.shaderProgram.textureCoordAttribute=gl.getAttribLocation(aniSvg.shaderProgram,"aTextureCoord");gl.enableVertexAttribArray(aniSvg.shaderProgram.textureCoordAttribute);aniSvg.shaderProgram.pMatrixUniform=gl.getUniformLocation(aniSvg.shaderProgram,"uPMatrix");aniSvg.shaderProgram.mvMatrixUniform=gl.getUniformLocation(aniSvg.shaderProgram,"uMVMatrix");aniSvg.shaderProgram.samplerUniform=gl.getUniformLocation(aniSvg.shaderProgram,"uSampler");aniSvg.shaderProgram.alphaUniform=gl.getUniformLocation(aniSvg.shaderProgram,"uAlpha");return true;}
aniSvg.get_vertexShader=function(){var s="attribute vec3 aVertexPosition;"
+"attribute vec2 aTextureCoord;"
+"uniform mat4 uMVMatrix;"
+"uniform mat4 uPMatrix;"
+"varying vec2 vTextureCoord;"
+"void main(void){"
+"	gl_Position = uPMatrix * uMVMatrix * vec4(aVertexPosition, 1.0);"
+" vTextureCoord = aTextureCoord;"
+"}";var v=gl.createShader(gl.VERTEX_SHADER);gl.shaderSource(v,s);gl.compileShader(v);return v;}
aniSvg.get_fragmentShader=function(){var s="precision mediump float;"
+"varying highp vec2 vTextureCoord;"
+"uniform sampler2D uSampler;"
+"uniform float uAlpha;"
+"void main(void){"
+"	vec4 texColor = texture2D(uSampler, vTextureCoord);"
+" gl_FragColor = vec4(texColor.rgb, uAlpha);"
+"}";var f=gl.createShader(gl.FRAGMENT_SHADER);gl.shaderSource(f,s);gl.compileShader(f);return f;}
aniSvg.init_buffers=function(){aniSvg.cubeVertexPositionBuffer=new Array();aniSvg.cubeVertexTextureCoordBuffer=new Array();aniSvg.cubeVertexIndexBuffer=new Array();var unitH=(2*Math.PI/aniSvg.pc.articlesOnPage)/ScreenInfo.ratioWH*0.5*0.9;var phi1,phi2,phi3,phi4;for(var i=0;i<aniSvg.pc.articlesOnPage;i++){phi1=(20-i)*((2*Math.PI)/aniSvg.pc.articlesOnPage);phi2=(20-i-1)*((2*Math.PI)/aniSvg.pc.articlesOnPage);phi3=(phi1+phi2)/2;phi4=phi2-(phi2-phi3)*0.1;var vertices=[Math.cos(phi1),-unitH,Math.sin(phi1),Math.cos(phi1),unitH,Math.sin(phi1),Math.cos(phi4),unitH,Math.sin(phi4),Math.cos(phi4),-unitH,Math.sin(phi4)];aniSvg.arVertex[i]=new Array();aniSvg.arVertex[i]=vertices.slice(0);aniSvg.cnvPoint[i]=new Array(8);aniSvg.cubeVertexPositionBuffer[i]=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,aniSvg.cubeVertexPositionBuffer[i]);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array(vertices),gl.STATIC_DRAW);aniSvg.cubeVertexPositionBuffer[i].itemSize=3;aniSvg.cubeVertexPositionBuffer[i].numItems=4;var textureCoords=[0.0,0.0,0.0,1.0,1.0,1.0,1.0,0.0];aniSvg.cubeVertexTextureCoordBuffer[i]=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,aniSvg.cubeVertexTextureCoordBuffer[i]);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array(textureCoords),gl.STATIC_DRAW);aniSvg.cubeVertexTextureCoordBuffer[i].itemSize=2;aniSvg.cubeVertexTextureCoordBuffer[i].numItems=4;var cubeVertexIndices=[0,1,2,0,2,3];aniSvg.cubeVertexIndexBuffer[i]=gl.createBuffer();gl.bindBuffer(gl.ELEMENT_ARRAY_BUFFER,aniSvg.cubeVertexIndexBuffer[i]);gl.bufferData(gl.ELEMENT_ARRAY_BUFFER,new Uint16Array(cubeVertexIndices),gl.STATIC_DRAW);aniSvg.cubeVertexIndexBuffer[i].itemSize=1;aniSvg.cubeVertexIndexBuffer[i].numItems=6;}}
aniSvg.init_textures=function(){aniSvg.loaded=0;aniSvg.loadto=aniSvg.pc.finalArticle-aniSvg.pc.startArticle+1;var k=0;for(var i=aniSvg.pc.startArticle;i<=aniSvg.pc.finalArticle;i++){var aaa=FileInfo.thumbFilePath(i+1,"s","","*");if(ServerInfo.applyCipher===true)load_cipherImage('cube',k,aaa[0],aniSvg.initTexture2);else aniSvg.catTexture[k]=aniSvg.initTexture(aaa[0]);k++;}
}
aniSvg.initTexture=function(imgUrl){var crateImage=new Image();var texture=gl.createTexture();texture.image=crateImage;crateImage.src=imgUrl;crateImage.onload=function(){aniSvg.handleLoadedTexture(texture);}
return texture;}
aniSvg.initTexture2=function(skd,npage,urlsrc){var crateImage=new Image();var texture=gl.createTexture();texture.image=crateImage;crateImage.src=urlsrc;crateImage.onload=function(){aniSvg.handleLoadedTexture(texture);}
aniSvg.catTexture[npage]=texture;}
aniSvg.handleLoadedTexture=function(texture){gl.bindTexture(gl.TEXTURE_2D,texture);gl.pixelStorei(gl.UNPACK_FLIP_Y_WEBGL,true);gl.texImage2D(gl.TEXTURE_2D,0,gl.RGBA,gl.RGBA,gl.UNSIGNED_BYTE,texture.image);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MAG_FILTER,gl.LINEAR);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MIN_FILTER,gl.LINEAR);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_S,gl.CLAMP_TO_EDGE);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_T,gl.CLAMP_TO_EDGE);gl.bindTexture(gl.TEXTURE_2D,null);aniSvg.loaded++;if(aniSvg.loaded===aniSvg.loadto){aniSvg.do_afterAllLoaded();}}
aniSvg.drawScene=function(){if(aniSvg.overIndex===-1)aniSvg.yRot-=aniSvg.ySpeed;gl.viewport(0,0,gl.viewportWidth,gl.viewportHeight);gl.clear(gl.COLOR_BUFFER_BIT|gl.DEPTH_BUFFER_BIT);gl.blendFunc(gl.SRC_ALPHA,gl.ONE_MINUS_SRC_ALPHA);gl.enable(gl.BLEND);gl.disable(gl.DEPTH_TEST);aniSvg.rotateMatrixXY(get_radFromdeg(aniSvg.xRot),get_radFromdeg(aniSvg.yRot));var pt={x:0,y:0,z:0};for(var i=0;i<aniSvg.pc.articlesOnPage;i++){if(aniSvg.catTexture[i]==undefined)continue;if(i===aniSvg.overIndex)gl.uniform1f(aniSvg.shaderProgram.alphaUniform,aniSvg.overAlpha);else gl.uniform1f(aniSvg.shaderProgram.alphaUniform,aniSvg.normalAlpha);gl.bindBuffer(gl.ARRAY_BUFFER,aniSvg.cubeVertexPositionBuffer[i]);gl.vertexAttribPointer(aniSvg.shaderProgram.vertexPositionAttribute,aniSvg.cubeVertexPositionBuffer[i].itemSize,gl.FLOAT,false,0,0);gl.bindBuffer(gl.ARRAY_BUFFER,aniSvg.cubeVertexTextureCoordBuffer[i]);gl.vertexAttribPointer(aniSvg.shaderProgram.textureCoordAttribute,aniSvg.cubeVertexTextureCoordBuffer[i].itemSize,gl.FLOAT,false,0,0);gl.activeTexture(gl.TEXTURE0);gl.bindTexture(gl.TEXTURE_2D,aniSvg.catTexture[i]);gl.uniform1i(aniSvg.shaderProgram.samplerUniform,0);gl.bindBuffer(gl.ELEMENT_ARRAY_BUFFER,aniSvg.cubeVertexIndexBuffer[i]);gl.uniformMatrix4fv(aniSvg.shaderProgram.pMatrixUniform,false,aniSvg.pMatrix);gl.uniformMatrix4fv(aniSvg.shaderProgram.mvMatrixUniform,false,aniSvg.mvMatrix);gl.drawElements(gl.TRIANGLES,aniSvg.cubeVertexIndexBuffer[i].numItems,gl.UNSIGNED_SHORT,0);aniSvg.ptpersProject(aniSvg.arVertex[i][0],aniSvg.arVertex[i][1],aniSvg.arVertex[i][2],pt);aniSvg.cnvPoint[i][0]=pt.x;aniSvg.cnvPoint[i][1]=pt.y;aniSvg.ptpersProject(aniSvg.arVertex[i][3],aniSvg.arVertex[i][4],aniSvg.arVertex[i][5],pt);aniSvg.cnvPoint[i][2]=pt.x;aniSvg.cnvPoint[i][3]=pt.y;aniSvg.ptpersProject(aniSvg.arVertex[i][6],aniSvg.arVertex[i][7],aniSvg.arVertex[i][8],pt);aniSvg.cnvPoint[i][4]=pt.x;aniSvg.cnvPoint[i][5]=pt.y;aniSvg.ptpersProject(aniSvg.arVertex[i][9],aniSvg.arVertex[i][10],aniSvg.arVertex[i][11],pt);aniSvg.cnvPoint[i][6]=pt.x;aniSvg.cnvPoint[i][7]=pt.y;}
aniSvg.cnvPtLen=aniSvg.cnvPoint.length;}
aniSvg.perspectiveMatrix=function(fovy,aspect,near,far){var top=near*Math.tan(fovy*Math.PI/360.0);var right=top*aspect;var left=-right;var bottom=-top;var rl=(right-left);var tb=(top-bottom);var fn=(far-near);aniSvg.pMatrix[0]=(near*2)/rl;aniSvg.pMatrix[1]=0;aniSvg.pMatrix[2]=0;aniSvg.pMatrix[3]=0;aniSvg.pMatrix[4]=0;aniSvg.pMatrix[5]=(near*2)/tb;aniSvg.pMatrix[6]=0;aniSvg.pMatrix[7]=0;aniSvg.pMatrix[8]=(right+left)/rl;aniSvg.pMatrix[9]=(top+bottom)/tb;aniSvg.pMatrix[10]=-(far+near)/fn;aniSvg.pMatrix[11]=-1;aniSvg.pMatrix[12]=0;aniSvg.pMatrix[13]=0;aniSvg.pMatrix[14]=-(far*near*2)/fn;aniSvg.pMatrix[15]=0;}
aniSvg.prepareMatrix=function(){aniSvg.prepMatrix=new Float32Array(16);aniSvg.prepMatrix[0]=1;aniSvg.prepMatrix[1]=0;aniSvg.prepMatrix[2]=0;aniSvg.prepMatrix[3]=0;aniSvg.prepMatrix[4]=0;aniSvg.prepMatrix[5]=1;aniSvg.prepMatrix[6]=0;aniSvg.prepMatrix[7]=0;aniSvg.prepMatrix[8]=0;aniSvg.prepMatrix[9]=0;aniSvg.prepMatrix[10]=1;aniSvg.prepMatrix[11]=0;aniSvg.prepMatrix[12]=0;aniSvg.prepMatrix[13]=0;aniSvg.prepMatrix[14]=0;aniSvg.prepMatrix[15]=1;var x=0,y=0,z=-5;aniSvg.prepMatrix[12]=aniSvg.prepMatrix[0]*x+aniSvg.prepMatrix[4]*y+aniSvg.prepMatrix[8]*z+aniSvg.prepMatrix[12];aniSvg.prepMatrix[13]=aniSvg.prepMatrix[1]*x+aniSvg.prepMatrix[5]*y+aniSvg.prepMatrix[9]*z+aniSvg.prepMatrix[13];aniSvg.prepMatrix[14]=aniSvg.prepMatrix[2]*x+aniSvg.prepMatrix[6]*y+aniSvg.prepMatrix[10]*z+aniSvg.prepMatrix[14];aniSvg.prepMatrix[15]=aniSvg.prepMatrix[3]*x+aniSvg.prepMatrix[7]*y+aniSvg.prepMatrix[11]*z+aniSvg.prepMatrix[15];var phiX=get_radFromdeg(aniSvg.xRot);var s=Math.sin(phiX);var c=Math.cos(phiX);aniSvg.prepMatrix[4]=aniSvg.prepMatrix[4]*c+aniSvg.prepMatrix[8]*s;aniSvg.prepMatrix[5]=aniSvg.prepMatrix[5]*c+aniSvg.prepMatrix[9]*s;aniSvg.prepMatrix[6]=aniSvg.prepMatrix[6]*c+aniSvg.prepMatrix[10]*s;aniSvg.prepMatrix[7]=aniSvg.prepMatrix[7]*c+aniSvg.prepMatrix[11]*s;aniSvg.prepMatrix[8]=-aniSvg.prepMatrix[4]*s+aniSvg.prepMatrix[8]*c;aniSvg.prepMatrix[9]=-aniSvg.prepMatrix[5]*s+aniSvg.prepMatrix[9]*c;aniSvg.prepMatrix[10]=-aniSvg.prepMatrix[6]*s+aniSvg.prepMatrix[10]*c;aniSvg.prepMatrix[11]=-aniSvg.prepMatrix[7]*s+aniSvg.prepMatrix[11]*c;}
aniSvg.rotateMatrixXY=function(phiX,phiY){aniSvg.mvMatrix[4]=aniSvg.prepMatrix[4];aniSvg.mvMatrix[5]=aniSvg.prepMatrix[5];aniSvg.mvMatrix[6]=aniSvg.prepMatrix[6];aniSvg.mvMatrix[7]=aniSvg.prepMatrix[7];aniSvg.mvMatrix[12]=aniSvg.prepMatrix[12];aniSvg.mvMatrix[13]=aniSvg.prepMatrix[13];aniSvg.mvMatrix[14]=aniSvg.prepMatrix[14];aniSvg.mvMatrix[15]=aniSvg.prepMatrix[15];var s=Math.sin(phiX);var c=Math.cos(phiX);aniSvg.mvMatrix[4]=aniSvg.prepMatrix[4]*c+aniSvg.prepMatrix[8]*s;aniSvg.mvMatrix[5]=aniSvg.prepMatrix[5]*c+aniSvg.prepMatrix[9]*s;aniSvg.mvMatrix[6]=aniSvg.prepMatrix[6]*c+aniSvg.prepMatrix[10]*s;aniSvg.mvMatrix[7]=aniSvg.prepMatrix[7]*c+aniSvg.prepMatrix[11]*s;aniSvg.mvMatrix[8]=-aniSvg.prepMatrix[4]*s+aniSvg.prepMatrix[8]*c;aniSvg.mvMatrix[9]=-aniSvg.prepMatrix[5]*s+aniSvg.prepMatrix[9]*c;aniSvg.mvMatrix[10]=-aniSvg.prepMatrix[6]*s+aniSvg.prepMatrix[10]*c;aniSvg.mvMatrix[11]=-aniSvg.prepMatrix[7]*s+aniSvg.prepMatrix[11]*c;s=Math.sin(phiY);c=Math.cos(phiY);aniSvg.mvMatrix[0]=aniSvg.prepMatrix[0]*c-aniSvg.mvMatrix[8]*s;aniSvg.mvMatrix[1]=aniSvg.prepMatrix[1]*c-aniSvg.mvMatrix[9]*s;aniSvg.mvMatrix[2]=aniSvg.prepMatrix[2]*c-aniSvg.mvMatrix[10]*s;aniSvg.mvMatrix[3]=aniSvg.prepMatrix[3]*c-aniSvg.mvMatrix[11]*s;aniSvg.mvMatrix[8]=aniSvg.prepMatrix[0]*s+aniSvg.mvMatrix[8]*c;aniSvg.mvMatrix[9]=aniSvg.prepMatrix[1]*s+aniSvg.mvMatrix[9]*c;aniSvg.mvMatrix[10]=aniSvg.prepMatrix[2]*s+aniSvg.mvMatrix[10]*c;aniSvg.mvMatrix[11]=aniSvg.prepMatrix[3]*s+aniSvg.mvMatrix[11]*c;}
aniSvg.lightingMatrix=function(){var a00=aniSvg.mvMatrix[0],a01=aniSvg.mvMatrix[1],a02=aniSvg.mvMatrix[2];var a10=aniSvg.mvMatrix[4],a11=aniSvg.mvMatrix[5],a12=aniSvg.mvMatrix[6];var a20=aniSvg.mvMatrix[8],a21=aniSvg.mvMatrix[9],a22=aniSvg.mvMatrix[10];var b01=a22*a11-a12*a21;var b11=-a22*a10+a12*a20;var b21=a21*a10-a11*a20;var d=a00*b01+a01*b11+a02*b21;if(!d)return;var id=1/d;aniSvg.normalMatrix[0]=b01*id;aniSvg.normalMatrix[1]=(-a22*a01+a02*a21)*id;aniSvg.normalMatrix[2]=(a12*a01-a02*a11)*id;aniSvg.normalMatrix[3]=b11*id;aniSvg.normalMatrix[4]=(a22*a00-a02*a20)*id;aniSvg.normalMatrix[5]=(-a12*a00+a02*a10)*id;aniSvg.normalMatrix[6]=b21*id;aniSvg.normalMatrix[7]=(-a21*a00+a01*a20)*id;aniSvg.normalMatrix[8]=(a11*a00-a01*a10)*id;a01=aniSvg.normalMatrix[1],a02=aniSvg.normalMatrix[2],a12=aniSvg.normalMatrix[5];aniSvg.normalMatrix[1]=aniSvg.normalMatrix[3];aniSvg.normalMatrix[2]=aniSvg.normalMatrix[6];aniSvg.normalMatrix[3]=a01;aniSvg.normalMatrix[5]=aniSvg.normalMatrix[7];aniSvg.normalMatrix[6]=a02;aniSvg.normalMatrix[7]=a12;}
aniSvg.ptpersProject=function(objx,objy,objz,tcoord){var t=new Array(8);t[0]=aniSvg.mvMatrix[0]*objx+aniSvg.mvMatrix[4]*objy+aniSvg.mvMatrix[8]*objz+aniSvg.mvMatrix[12];t[1]=aniSvg.mvMatrix[1]*objx+aniSvg.mvMatrix[5]*objy+aniSvg.mvMatrix[9]*objz+aniSvg.mvMatrix[13];t[2]=aniSvg.mvMatrix[2]*objx+aniSvg.mvMatrix[6]*objy+aniSvg.mvMatrix[10]*objz+aniSvg.mvMatrix[14];t[3]=aniSvg.mvMatrix[3]*objx+aniSvg.mvMatrix[7]*objy+aniSvg.mvMatrix[11]*objz+aniSvg.mvMatrix[15];t[4]=aniSvg.pMatrix[0]*t[0]+aniSvg.pMatrix[4]*t[1]+aniSvg.pMatrix[8]*t[2]+aniSvg.pMatrix[12]*t[3];t[5]=aniSvg.pMatrix[1]*t[0]+aniSvg.pMatrix[5]*t[1]+aniSvg.pMatrix[9]*t[2]+aniSvg.pMatrix[13]*t[3];t[6]=aniSvg.pMatrix[2]*t[0]+aniSvg.pMatrix[6]*t[1]+aniSvg.pMatrix[10]*t[2]+aniSvg.pMatrix[14]*t[3];t[7]=-t[2];if(t[7]==0.0){tcoord.x=0,tcoord.y=0,tcoord.z=0;return;}
t[7]=1.0/t[7];t[4]*=t[7];t[5]*=t[7];t[6]*=t[7];tcoord.x=(t[4]*0.5+0.5)*stageWidth+0.0;tcoord.y=stageHeight-(t[5]*0.5+0.5)*stageHeight+0.0;tcoord.z=(1.0+t[6])*0.5;}
aniSvg.isPointInRectangle=function(newX,newY,arPt){var leftright=aniSvg.wsideLine(arPt[0],arPt[1],arPt[2],arPt[3],newX,newY);if(aniSvg.wsideLine(arPt[2],arPt[3],arPt[4],arPt[5],newX,newY)!==leftright)return false;if(aniSvg.wsideLine(arPt[4],arPt[5],arPt[6],arPt[7],newX,newY)!==leftright)return false;if(aniSvg.wsideLine(arPt[6],arPt[7],arPt[0],arPt[1],newX,newY)!==leftright)return false;return true;}
aniSvg.wsideLine=function(ax,ay,bx,by,cx,cy){if((bx-ax)*(cy-ay)-(by-ay)*(cx-ax)>0)return true;return false;}
aniSvg.showPoint=function(antx,cx,cy){antx.fillStyle="#0000FF";antx.beginPath();antx.moveTo(cx-5,cy+5);antx.lineTo(cx-5,cy-5);antx.lineTo(cx+5,cy-5);antx.lineTo(cx+5,cy+5);antx.fill();}
aniSvg.nextPermission=function(device){if(aniSvg.smcState==="catimage")return 0;if(MoveInfo.skipLastFirst===true&&aniSvg.pc.currentPage===aniSvg.pc.totalPages)return 2;return 1;}
aniSvg.prevPermission=function(device){if(aniSvg.smcState==="catimage")return 0;if(MoveInfo.skipLastFirst===true&&aniSvg.pc.currentPage===1)return 2;return 1;}
aniSvg.firstPermission=function(device){if(aniSvg.smcState==="catimage")return 0;if(aniSvg.pc.currentPage===1)return 2;return 1;}
aniSvg.lastPermission=function(device){if(aniSvg.smcState==="catimage")return 0;if(aniSvg.pc.currentPage===aniSvg.pc.totalPages)return 2;return 1;}
