function init_smc2(){}
function go_next(bool){if(bool===true)SmcObj.tempN=PageInfo.get_nextPageNo();Action.aniLocking=true;DragObj.do_dragStart('next');DragObj.cdragImg.style.left=smRect.x+"px";DragObj.pdragImg.style.left=(smRect.x-winRect.width)+"px";DragObj.ndragImg.style.left=(smRect.x+winRect.width)+"px";DragObj.cdragImg.style.top=smRect.y+"px";DragObj.pdragImg.style.top=smRect.y+"px";DragObj.ndragImg.style.top=smRect.y+"px";befX=0,clickX=0;DragObj.touchDirection=4;DragObj.moveX=-winRect.width;AniObj.seq=0;AniObj.timer=setInterval(DragObj.do_nextAnimate,DragObj.interval);}
function go_prev(bool){if(bool===true)SmcObj.tempN=PageInfo.get_prevPageNo();Action.aniLocking=true;DragObj.do_dragStart('prev');DragObj.cdragImg.style.left=smRect.x+"px";DragObj.pdragImg.style.left=(smRect.x-winRect.width)+"px";DragObj.ndragImg.style.left=(smRect.x+winRect.width)+"px";DragObj.cdragImg.style.top=smRect.y+"px";DragObj.pdragImg.style.top=smRect.y+"px";DragObj.ndragImg.style.top=smRect.y+"px";befX=0,clickX=0;DragObj.touchDirection=6;DragObj.moveX=winRect.width;AniObj.seq=0;AniObj.timer=setInterval(DragObj.do_prevAnimate,DragObj.interval);}
function go_direct(n){n=PageInfo.get_directPageNo(n);SmcObj.tempN=n;if(PageInfo.prevPage<n)go_next(false);else go_prev(false);}
function prepare_turnover(){if(glassesSvg)unload_glasses();if(soundctrlSvg)unload_soundcontrol();if(CoverObj.onsmrX!==NOMOVE)OnsmObj.set_visible("hidden","hidden");AniObj.seq=0;cntx.globalAlpha=1;SmcObj.prepare_turnover();}
function finish_turnover(){SmcObj.finish_turnover();}
function finish_turnover2(){Action.drawCondition=0;if(MoveInfo.pairEnlarge===true)Action.set_togetherEnlarge();MoveInfo.show_pageNumber();if(CoverObj.state===0)OnsmObj.set_visible("visible","visible");else CoverObj.set_cover();if(Action.mainState==="slide"){if(SmcObj.nextPermission("wheel")===false||PermitMan.access_memberZone(-1,"wheel")===false){Action.mainState="stop";}
else if(MoveInfo.loadLinkAtSlide===true){SmcObj.show_linkData();}
if(Action.mainState==="slide"){setTimeout("go_next(true)",MoveInfo.slideIntervalSM);return;}}
if(Action.mainState==="stop")Action.mainState="normal";SmcObj.show_outData();ScreenMan.finish_turnover();Action.aniLocking=false;}
