function init_smc2(){anicnvDiv.innerHTML="<svg id='anisvg' version='1.1' xmlns='http://www.w3.org/2000/svg' xmlns:xlink='http://www.w3.org/1999/xlink'></svg>";aniSvg=document.getElementById("anisvg");}
function go_next(bool){if(bool===true)PageInfo.reset_pageNext();Action.loaded=0;Action.loadto=0;SmcObj.direction="nextFrt";load_aniDiv(SmcObj.leftUrl,SmcObj.rightUrl);anicnvDiv.style.left=smRect.x+"px";anicnvDiv.style.top=smRect.y+"px";anicnvDiv.style.width=smRect.width+"px";anicnvDiv.style.height=smRect.height+"px";aniSvg.style.width=smRect.width+"px";aniSvg.style.height=smRect.height+"px";}
function after_nextFrontImageLoaded(){Action.drawCondition=2;prepare_turnover();AniObj.seq=0;AniObj.timer=setInterval(next_animateFrt,AniObj.transInterval);}
function next_animateFrt(){var angle=Math.floor(-90*AniObj.seq/AniObj.angleDiv);anicnvDiv.style.transform="perspective("+(smRect.width+10)+"px) rotateY("+angle+"deg)";anicnvDiv.style.webkitTransform="perspective("+(smRect.width+10)+"px) rotateY("+angle+"deg)";AniObj.seq++;if(AniObj.seq>=AniObj.angleDiv){clearInterval(AniObj.timer);var lefturl="",righturl="",appdix="s";if(SkinInfo.smcgallery===true||MoveInfo.bigImageOnly===true)appdix="";var aaa=FileInfo.cimgFilePath(PageInfo.currentPage,appdix,"","*");lefturl=aaa[0];if(ScreenInfo.onesmc===false){var aaa=FileInfo.cimgFilePath(PageInfo.currentPage+1,appdix,"","*");righturl=aaa[0];}
unload_aniDiv();SmcObj.direction="nextRear";load_aniDiv(lefturl,righturl);}}
function after_nextRearImageLoaded(){AniObj.seq=0;AniObj.timer=setInterval(next_animateRear,AniObj.transInterval);}
function next_animateRear(){var angle=-270-Math.floor(90*AniObj.seq/AniObj.angleDiv);anicnvDiv.style.transform="perspective("+(smRect.width+10)+"px) rotateY("+angle+"deg)";anicnvDiv.style.webkitTransform="perspective("+(smRect.width+10)+"px) rotateY("+angle+"deg)";AniObj.seq++;if(AniObj.seq===AniObj.angleDiv){clearInterval(AniObj.timer);finish_turnover();}}
function leftImgObjLoaded009(){console.log("smc009.js : left image loaded");loadComplete009();}
function rightImgObjLoaded009(){console.log("smc009.js : right image loaded");loadComplete009();}
function loadComplete009(){Action.loaded++;if(Action.loaded==Action.loadto){if(SmcObj.direction==="nextFrt")after_nextFrontImageLoaded();else if(SmcObj.direction==="nextRear")after_nextRearImageLoaded();else if(SmcObj.direction==="prevFrt")after_prevFrontImageLoaded();else after_prevRearImageLoaded();}}
function load_aniDiv(lefturl,righturl){var leftLoad=true,rightLoad=true;if(ScreenInfo.onesmc===true)rightLoad=false;if(leftLoad===true&&lefturl!=="")Action.loadto++;if(rightLoad===true&&righturl!=="")Action.loadto++;if(leftLoad===true){if(lefturl===""){var leftBackObj=document.createElementNS("http://www.w3.org/2000/svg","rect");leftBackObj.setAttribute("width",ScreenInfo.smImageWidth);leftBackObj.setAttribute("height",ScreenInfo.smImageHeight);leftBackObj.setAttribute("fill",ScreenInfo.blankColor);aniSvg.appendChild(leftBackObj);}
else{if(ServerInfo.applyCipher===true)load_cipherImage('btn',0,lefturl,go_nextLNCipher);else go_nextLNCipher(lefturl);}}
if(rightLoad===true){if(righturl===""){var rightBackObj=document.createElementNS("http://www.w3.org/2000/svg","rect");rightBackObj.setAttribute("x",ScreenInfo.smImageWidth);rightBackObj.setAttribute("width",ScreenInfo.smImageWidth);rightBackObj.setAttribute("height",ScreenInfo.smImageHeight);rightBackObj.setAttribute("fill",ScreenInfo.blankColor);aniSvg.appendChild(rightBackObj);}
else{if(ServerInfo.applyCipher===true)load_cipherImage('btn',0,righturl,go_nextRNCipher);else go_nextRNCipher(righturl);}}}
function go_nextLNCipher(skd,npage,urlsrc){var leftImgObj=document.createElementNS("http://www.w3.org/2000/svg","image");leftImgObj.setAttributeNS("http://www.w3.org/1999/xlink","xlink:href",urlsrc);leftImgObj.setAttribute("width",ScreenInfo.smImageWidth);leftImgObj.setAttribute("height",ScreenInfo.smImageHeight);leftImgObj.addEventListener("load",leftImgObjLoaded009());aniSvg.appendChild(leftImgObj);}
function go_nextRNCipher(skd,npage,urlsrc){var rightImgObj=document.createElementNS("http://www.w3.org/2000/svg","image");rightImgObj.setAttributeNS("http://www.w3.org/1999/xlink","xlink:href",urlsrc);rightImgObj.setAttribute("x",ScreenInfo.smImageWidth);rightImgObj.setAttribute("width",ScreenInfo.smImageWidth);rightImgObj.setAttribute("height",ScreenInfo.smImageHeight);rightImgObj.addEventListener("load",rightImgObjLoaded009());aniSvg.appendChild(rightImgObj);}
function unload_aniDiv(){var nodes=aniSvg.childNodes;for(var i=nodes.length-1;i>=0;i--){aniSvg.removeChild(nodes[i]);}}
function go_prev(bool){if(bool===true)PageInfo.reset_pagePrev();Action.loaded=0;Action.loadto=0;SmcObj.direction="prevFrt";load_aniDiv(SmcObj.leftUrl,SmcObj.rightUrl);anicnvDiv.style.left=smRect.x+"px";anicnvDiv.style.top=smRect.y+"px";anicnvDiv.style.width=smRect.width+"px";anicnvDiv.style.height=smRect.height+"px";aniSvg.style.width=smRect.width+"px";aniSvg.style.height=smRect.height+"px";}
function after_prevFrontImageLoaded(){Action.drawCondition=1;prepare_turnover();AniObj.seq=0;AniObj.timer=setInterval(prev_animateFrt,AniObj.transInterval);}
function prev_animateFrt(){var angle=Math.floor(90*AniObj.seq/AniObj.angleDiv);anicnvDiv.style.transform="perspective("+(smRect.width+10)+"px) rotateY("+angle+"deg)";anicnvDiv.style.webkitTransform="perspective("+(smRect.width+10)+"px) rotateY("+angle+"deg)";AniObj.seq++;if(AniObj.seq===AniObj.angleDiv){clearInterval(AniObj.timer);var lefturl="",righturl="",appdix="s";if(SkinInfo.smcgallery===true||MoveInfo.bigImageOnly===true)appdix="";var aaa=FileInfo.cimgFilePath(PageInfo.currentPage,appdix,"","*");lefturl=aaa[0];if(ScreenInfo.onesmc===false){var bbb=FileInfo.cimgFilePath(PageInfo.currentPage+1,appdix,"","*");righturl=bbb[0];}
unload_aniDiv();SmcObj.direction="prevRear";load_aniDiv(lefturl,righturl);}}
function after_prevRearImageLoaded(){AniObj.seq=0;AniObj.timer=setInterval(prev_animateRear,AniObj.transInterval);}
function prev_animateRear(){var angle=270+Math.floor(90*AniObj.seq/AniObj.angleDiv);anicnvDiv.style.transform="perspective("+(smRect.width+10)+"px) rotateY("+angle+"deg)";anicnvDiv.style.webkitTransform="perspective("+(smRect.width+10)+"px) rotateY("+angle+"deg)";AniObj.seq++;if(AniObj.seq===AniObj.angleDiv){clearInterval(AniObj.timer);finish_turnover();}}
function go_direct(n){n=PageInfo.get_directPageNo(n);PageInfo.prevPage=PageInfo.currentPage;PageInfo.currentPage=n;if(PageInfo.prevPage<n)go_next(false);else go_prev(false);}
function prepare_turnover(){if(glassesSvg)unload_glasses();if(soundctrlSvg)unload_soundcontrol();if(CoverObj.onsmrX!==NOMOVE)OnsmObj.set_visible("hidden","hidden");anicnvDiv.style.visibility="visible";CoverObj.hide_bothPage();AniObj.seq=0;cntx.globalAlpha=1;SmcObj.prepare_turnover();}
function finish_turnover(){SmcObj.finish_turnover();}
function finish_turnover2(){unload_aniDiv();anicnvDiv.style.visibility="hidden";anicnvDiv.style.left="-100px";anicnvDiv.style.top="-100px";anicnvDiv.style.width="1px";anicnvDiv.style.height="1px";Action.drawCondition=0;if(MoveInfo.pairEnlarge===true)Action.set_togetherEnlarge();MoveInfo.show_pageNumber();if(CataInfo.openingAnimation===true){if(PageInfo.blank_imageFromLeft(PageInfo.currentPage)===0)CoverObj.hide_leftPage();else if(PageInfo.blank_imageFromLeft(PageInfo.currentPage)===1)CoverObj.hide_rightPage();}
CoverObj.set_cover();if(Action.mainState==="slide"){if(SmcObj.nextPermission("wheel")===false||PermitMan.access_memberZone(-1,"wheel")===false){Action.mainState="stop";}
else if(MoveInfo.loadLinkAtSlide===true){SmcObj.show_linkData();}
if(Action.mainState==="slide"){setTimeout("go_next(true)",MoveInfo.slideIntervalSM);return;}}
if(Action.mainState==="stop")Action.mainState="normal";SmcObj.show_outData();ScreenMan.finish_turnover();Action.aniLocking=false;}
