function go_next(bool){PageInfo.reset_pageNext();aniSvg.go_direct();}
function go_prev(bool){PageInfo.reset_pagePrev();aniSvg.go_direct();}
function go_direct(n){n=PageInfo.get_directPageNo(n);if(n<1)n=1;PageInfo.prevPage=PageInfo.currentPage;PageInfo.currentPage=n;aniSvg.go_direct();}
function prepare_turnover(){if(glassesSvg!=undefined)unload_glasses();if(soundctrlSvg!=undefined)unload_soundcontrol();SmcObj.prepare_turnover();smcDiv.style.visibility="hidden";}
function finish_turnover(){SmcObj.finish_turnover();}
function finish_turnover2(){Action.drawCondition=0;if(MoveInfo.pairEnlarge==true)Action.set_togetherEnlarge();MoveInfo.show_pageNumber();if(Action.mainState=="slide"){if(SmcObj.nextPermission("wheel")==false||PermitMan.access_memberZone(-1,"wheel")==false){Action.mainState="stop";}
else if(MoveInfo.loadLinkAtSlide==true){SmcObj.show_linkData();}
if(Action.mainState=="slide"){setTimeout("go_next(true)",MoveInfo.slideIntervalSM);return;}}
if(Action.mainState=="stop")Action.mainState="normal";smcDiv.style.visibility="visible";SmcObj.show_outData();ScreenMan.finish_turnover();Action.aniLocking=false;}
function init_smc2(){anicnvDiv.style.visibility="visible";anicnvDiv.style.zIndex="10";aniSvg.thumbWidth=ScreenInfo.smImageWidth;aniSvg.thumbHeight=ScreenInfo.smImageHeight;aniSvg.mainWidth=aniSvg.thumbWidth+41;aniSvg.mainHeight=aniSvg.thumbHeight+66;aniSvg.sheetWidth=Math.floor(aniSvg.mainWidth*aniSvg.basicScale)+1;aniSvg.sheetHeight=Math.floor(aniSvg.mainHeight*aniSvg.basicScale)+1;aniSvg.arEpsPointX=new Int32Array(23);aniSvg.arEpsPointY=new Int32Array(23);aniSvg.set_arEpsPoint();ScreenInfo.set_smRectDrag(aniSvg.arEpsPointX[11]-ScreenInfo.smImageWidthHalf-1,aniSvg.arEpsPointY[11]+15);aniSvg.pc=new PagingContCabinet(21,11);aniSvg.pc.totalArticles=PageInfo.cataPages;aniSvg.pc.set_startArticle(PageInfo.startPage);PageInfo.currentPage=aniSvg.pc.get_mainArticle()+1;if(ServerInfo.applyCipher===true){for(var i=aniSvg.pc.startArticle+1;i<=aniSvg.pc.finalArticle+1;i++){var aaa=FileInfo.cimgFilePath(i,"s","","*");load_cipherImage('cabinet',i,aaa[0],aniSvg.load_imageCipher);}}
else{for(var i=aniSvg.pc.startArticle+1;i<=aniSvg.pc.finalArticle+1;i++){aniSvg.load_image(i);}}}
aniSvg={thumbWidth:0,thumbHeight:0,mainWidth:0,mainHeight:0,sheetWidth:0,sheetHeight:0,pc:undefined,smcState:'',timer:undefined,interval:15,seq:0,transLen:8,basicScale:0.85,arEpsPointX:[],arEpsPointY:[],arDivobj:[],finalidxLoaded:false,startidxLoaded:false,leaveDiffY:0,comeDiffY:0,si:0,fi:0,firstPeriod:false,lastPeriod:false,arBackColor:["#FFFFFF","#FEFEFE","#FDFDFD","#FCFCFC","#FBFBFB","#FAFAFA","#FAFAFA","#F9F9F9","#F8F8F8","#F7F7F7","#F6F6F6","#F6F6F6"]};aniSvg.load_image=function(pno){var idx=aniSvg.pc.get_idxFromPage(pno);if(idx===aniSvg.pc.mainidx){aniSvg.load_image2(pno,idx,aniSvg.arEpsPointX[idx]-ScreenInfo.smImageWidthHalf-20,aniSvg.arEpsPointY[idx]-30,aniSvg.mainWidth,aniSvg.mainHeight);}
else{aniSvg.load_image2(pno,idx,aniSvg.arEpsPointX[idx]-Math.floor(ScreenInfo.smImageWidthHalf*aniSvg.basicScale)-20,aniSvg.arEpsPointY[idx],aniSvg.sheetWidth,aniSvg.sheetHeight);}}
aniSvg.load_imageCipher=function(skd,npage,urlsrc){var idx=aniSvg.pc.get_idxFromPage(npage);if(idx===aniSvg.pc.mainidx){aniSvg.load_image2(npage,idx,aniSvg.arEpsPointX[idx]-ScreenInfo.smImageWidthHalf-20,aniSvg.arEpsPointY[idx]-30,aniSvg.mainWidth,aniSvg.mainHeight);}
else{aniSvg.load_image2(npage,idx,aniSvg.arEpsPointX[idx]-Math.floor(ScreenInfo.smImageWidthHalf*aniSvg.basicScale)-20,aniSvg.arEpsPointY[idx],aniSvg.sheetWidth,aniSvg.sheetHeight);}}
aniSvg.load_image2=function(pno,idx,posx,posy,tw,th,urlsrc){var cidx=Math.abs(aniSvg.pc.mainidx-idx);var zidx=12-cidx;var aaa=[];var logsrc="";var aaa=FileInfo.cimgFilePath(pno,"s","","*");logsrc=aaa[0];if(urlsrc==undefined)urlsrc=aaa[0];else logsrc=aaa[0]+" cipher ";var s="<svg version='1.1' id='cabisvg"+pno+"' xmlns='http://www.w3.org/2000/svg' xmlns:xlink='http://www.w3.org/1999/xlink'>"
+"<g id='cabig"+pno+"' class='cabig' onclick=\"aniSvg.do_itemClick("+pno+")\">"
+"<rect id='cabirect"+pno+"' x='0.5' y='0.5' rx='15' width='"+(aniSvg.thumbWidth+40)+"' height='"+(aniSvg.thumbHeight+65)+"' fill='"+aniSvg.arBackColor[cidx]+"' stroke='#555555' stroke-width='2' />"
+"<line x1='10' y1='32.5' x2='"+(aniSvg.thumbWidth+30)+"' y2='32.5' stroke='#929292' stroke-width='1' stroke-opacity='1' />"
+"<rect x='22' y='47' width='"+(aniSvg.thumbWidth+2)+"' height='"+(aniSvg.thumbHeight+2)+"' fill='#E5E5E5' />"
+"<text x='19' y='24'>"+pno+" page</text>"
+"<image x='"+(aniSvg.thumbWidth-3)+"' y='11' xlink:href='./skin5/etc/smc008_bookmark.png' width='23' height='18' onclick=\"aniSvg.do_spacerbtnClick("+pno+");\" cursor='pointer' />"
+"<image x='19' y='45' width='"+aniSvg.thumbWidth+"' height='"+aniSvg.thumbHeight+"' xlink:href='"+urlsrc+"' onload=\"aniSvg.leftImageLoad("+pno+",'"+logsrc+"');\" />"
+"</g></svg>";var divNode=document.createElement("div");divNode.setAttribute("data-pno",pno);divNode.style.cssText="z-index:"+zidx+";display:block;position:absolute;left:"+posx+"px;top:"+posy+"px;width:"+tw+"px;height:"+th+"px;";divNode.innerHTML=s;anicnvDiv.appendChild(divNode);if(cidx!=0){document.getElementById('cabig'+pno).setAttribute('transform','scale('+aniSvg.basicScale+')');}
aniSvg.arDivobj[idx]=divNode;}
aniSvg.leftImageLoad=function(pno,s){console.log("smc008.js : "+s+" : loaded");if(aniSvg.smcState===""){}
else if(aniSvg.smcState==="next"){aniSvg.go_nextAni(true);}
else if(aniSvg.smcState==="prev"){aniSvg.do_rotatePrev(true);}}
aniSvg.load_nextImage=function(){if(aniSvg.pc.contain_finalArticle()===true){aniSvg.go_nextAni(false);}
else{aniSvg.load_image2(aniSvg.pc.loadArticle+1,22,aniSvg.arEpsPointX[22]-Math.floor(ScreenInfo.smImageWidthHalf*aniSvg.basicScale)-20,aniSvg.arEpsPointY[22],aniSvg.sheetWidth,aniSvg.sheetHeight);}}
aniSvg.load_prevImage=function(){if(aniSvg.pc.contain_startArticle()===true){aniSvg.do_rotatePrev(false);}
else{aniSvg.load_image2(aniSvg.pc.loadArticle+1,0,aniSvg.arEpsPointX[0]-Math.floor(ScreenInfo.smImageWidthHalf*aniSvg.basicScale)-20,aniSvg.arEpsPointY[0],aniSvg.sheetWidth,aniSvg.sheetHeight);}}
aniSvg.do_itemClick=function(n){if(PermitMan.normalPerm(0)===false)return;if(Action.drawCondition>0)return;if(n===PageInfo.currentPage)return;go_direct(n);}
aniSvg.go_direct=function(){aniSvg.pc.set_targetArticle(PageInfo.currentPage);prepare_turnover();if(aniSvg.pc.targetArticle>aniSvg.pc.get_mainArticle()){aniSvg.smcState="next";aniSvg.pc.loadArticle=(aniSvg.pc.get_jumpContinueNext()===true)?aniSvg.pc.targetArticle-11:aniSvg.pc.finalArticle+1;aniSvg.load_nextImage();}
else{aniSvg.smcState="prev";aniSvg.pc.loadArticle=(aniSvg.pc.get_jumpContinuePrev()===true)?aniSvg.pc.targetArticle+11:aniSvg.pc.startArticle-1;aniSvg.load_prevImage();}}
aniSvg.top_zindex=function(idx){aniSvg.arDivobj[idx].style.zIndex=12;var k=11;var alen=aniSvg.arDivobj.length;for(var i=idx+1;i<alen;i++){if(aniSvg.arDivobj[i]){aniSvg.arDivobj[i].style.zIndex=k;k--;}}
k=11;for(i=idx-1;i>=0;i--){if(aniSvg.arDivobj[i]){aniSvg.arDivobj[i].style.zIndex=k;k--;}}}
aniSvg.do_spacerbtnClick=function(pno){if(PermitMan.normalPerm(0)===false)return;load_spacer('left',true);}
aniSvg.do_afterFirstAllLoaded=function(){Action.aniLocking=false;}
aniSvg.go_nextAni=function(bool){aniSvg.finalidxLoaded=bool;aniSvg.si=aniSvg.pc.startidx;aniSvg.fi=(bool===true)?aniSvg.pc.finalidx+1:aniSvg.pc.finalidx;aniSvg.leaveDiffY=aniSvg.arEpsPointY[10]-(aniSvg.arEpsPointY[11]-30);aniSvg.comeDiffY=(aniSvg.arEpsPointY[11]-30)-aniSvg.arEpsPointY[12];aniSvg.firstPeriod=(aniSvg.pc.get_mainPage()-PageInfo.prevPage===0)?true:false;aniSvg.lastPeriod=(PageInfo.currentPage-aniSvg.pc.get_mainPage()===1)?true:false;aniSvg.seq=1;aniSvg.timer=setInterval(aniSvg.next_animate,aniSvg.interval);}
aniSvg.next_animate=function(){var ratio=aniSvg.seq/aniSvg.transLen;var x1,y1,x2,y2,divNode,pno,svgobj;for(var i=aniSvg.si;i<=aniSvg.fi;i++){x1=aniSvg.arEpsPointX[i],y1=aniSvg.arEpsPointY[i];x2=aniSvg.arEpsPointX[i-1],y2=aniSvg.arEpsPointY[i-1];divNode=aniSvg.arDivobj[i];if(i===12)divNode.style.left=(x1-(x1-x2)*ratio-ScreenInfo.smImageWidthHalf-20)+"px";else divNode.style.left=(x1-(x1-x2)*ratio-ScreenInfo.smImageWidthHalf*aniSvg.basicScale-20)+"px";divNode.style.top=(y1-(y1-y2)*ratio)+"px";}
if(aniSvg.seq===4)aniSvg.top_zindex(12);var scale=0.0;if(aniSvg.firstPeriod===true){divNode=aniSvg.arDivobj[11];divNode.style.top=(aniSvg.arEpsPointY[10]+aniSvg.leaveDiffY*(1-ratio))+"px";pno=divNode.getAttribute("data-pno");scale=1-(1-aniSvg.basicScale)*ratio;svgobj=document.getElementById('cabisvg'+pno);svgobj.style.width=Math.floor(aniSvg.mainWidth*scale)+"px";svgobj.style.height=Math.floor(aniSvg.mainHeight*scale)+"px";document.getElementById('cabig'+pno).setAttribute('transform','scale('+scale+')');}
if(aniSvg.lastPeriod===true){divNode=aniSvg.arDivobj[12];divNode.style.top=(aniSvg.arEpsPointY[11]-30+aniSvg.comeDiffY*(1-ratio))+"px";pno=divNode.getAttribute("data-pno");scale=1-(1-aniSvg.basicScale)*(1-ratio);svgobj=document.getElementById('cabisvg'+pno);svgobj.style.width=Math.floor(aniSvg.mainWidth*scale)+"px";svgobj.style.height=Math.floor(aniSvg.mainHeight*scale)+"px";document.getElementById('cabig'+pno).setAttribute('transform','scale('+scale+')');}
aniSvg.seq++;if(aniSvg.seq===aniSvg.transLen+1){clearInterval(aniSvg.timer);aniSvg.next_animateComplete();}}
aniSvg.next_animateComplete=function(){var divNode,pno,cidx;for(var i=aniSvg.si;i<=aniSvg.fi;i++){cidx=Math.abs(aniSvg.pc.mainidx-i);divNode=aniSvg.arDivobj[i];pno=divNode.getAttribute("data-pno");document.getElementById('cabirect'+pno).setAttribute("fill",aniSvg.arBackColor[cidx]);aniSvg.arDivobj[i-1]=divNode;}
if(aniSvg.arDivobj[0]){aniSvg.arDivobj[0].innerHTML="";anicnvDiv.removeChild(aniSvg.arDivobj[0]);aniSvg.arDivobj[0]=undefined;aniSvg.pc.startArticle=parseInt(aniSvg.arDivobj[1].getAttribute("data-pno"))-1;}
else{aniSvg.pc.startidx--;}
if(aniSvg.finalidxLoaded===true){aniSvg.arDivobj[22]=undefined;aniSvg.pc.finalArticle=parseInt(aniSvg.arDivobj[21].getAttribute("data-pno"))-1;}
else{aniSvg.arDivobj[aniSvg.fi]=undefined;aniSvg.pc.finalidx--;}
if(aniSvg.pc.get_reachTarget()===true){aniSvg.smcState="";finish_turnover();}
else{aniSvg.pc.loadArticle++;aniSvg.load_nextImage();}}
aniSvg.do_rotatePrev=function(bool){aniSvg.startidxLoaded=bool;aniSvg.si=(bool===true)?aniSvg.pc.startidx-1:aniSvg.pc.startidx;aniSvg.fi=aniSvg.pc.finalidx;aniSvg.leaveDiffY=aniSvg.arEpsPointY[12]-(aniSvg.arEpsPointY[11]-30);aniSvg.comeDiffY=aniSvg.arEpsPointY[11]-30-aniSvg.arEpsPointY[10];aniSvg.firstPeriod=(aniSvg.pc.get_mainPage()-PageInfo.prevPage===0)?true:false;aniSvg.lastPeriod=(aniSvg.pc.get_mainPage()-PageInfo.currentPage===1)?true:false;aniSvg.seq=1;aniSvg.timer=setInterval(aniSvg.prev_animate,aniSvg.interval);}
aniSvg.prev_animate=function(){var ratio=aniSvg.seq/aniSvg.transLen;var x1,y1,x2,y2,divNode;for(var i=aniSvg.si;i<=aniSvg.fi;i++){x1=aniSvg.arEpsPointX[i],y1=aniSvg.arEpsPointY[i];x2=aniSvg.arEpsPointX[i+1],y2=aniSvg.arEpsPointY[i+1];divNode=aniSvg.arDivobj[i];if(i===10)divNode.style.left=(x1+(x2-x1)*ratio-ScreenInfo.smImageWidthHalf-20)+"px";else divNode.style.left=(x1+(x2-x1)*ratio-ScreenInfo.smImageWidthHalf*aniSvg.basicScale-20)+"px";divNode.style.top=(y1+(y2-y1)*ratio)+"px";}
if(aniSvg.seq===4)aniSvg.top_zindex(10);var scale=0.0;if(aniSvg.firstPeriod===true){divNode=aniSvg.arDivobj[11];divNode.style.top=(aniSvg.arEpsPointY[12]+aniSvg.leaveDiffY*(1-ratio))+"px";pno=divNode.getAttribute("data-pno");scale=1-(1-aniSvg.basicScale)*ratio;svgobj=document.getElementById('cabisvg'+pno);svgobj.style.width=Math.floor(aniSvg.mainWidth*scale)+"px";svgobj.style.height=Math.floor(aniSvg.mainHeight*scale)+"px";document.getElementById('cabig'+pno).setAttribute('transform','scale('+scale+')');}
if(aniSvg.lastPeriod===true){divNode=aniSvg.arDivobj[10];divNode.style.top=(aniSvg.arEpsPointY[11]-30+aniSvg.comeDiffY*(1-ratio))+"px";pno=divNode.getAttribute("data-pno");scale=1-(1-aniSvg.basicScale)*(1-ratio);svgobj=document.getElementById('cabisvg'+pno);svgobj.style.width=Math.floor(aniSvg.mainWidth*scale)+"px";svgobj.style.height=Math.floor(aniSvg.mainHeight*scale)+"px";document.getElementById('cabig'+pno).setAttribute('transform','scale('+scale+')');}
aniSvg.seq++;if(aniSvg.seq===aniSvg.transLen+1){clearInterval(aniSvg.timer);aniSvg.prev_animateComplete();}}
aniSvg.prev_animateComplete=function(){var divNode,pno,cidx;for(var i=aniSvg.fi;i>=aniSvg.si;i--){cidx=Math.abs(aniSvg.pc.mainidx-i);divNode=aniSvg.arDivobj[i];pno=divNode.getAttribute("data-pno");document.getElementById('cabirect'+pno).setAttribute("fill",aniSvg.arBackColor[cidx]);aniSvg.arDivobj[i+1]=divNode;}
if(aniSvg.arDivobj[22]){aniSvg.arDivobj[22].innerHTML="";anicnvDiv.removeChild(aniSvg.arDivobj[22]);aniSvg.arDivobj[22]=undefined;aniSvg.pc.finalArticle=parseInt(aniSvg.arDivobj[21].getAttribute("data-pno"))-1;}
else{aniSvg.pc.finalidx++;}
if(aniSvg.startidxLoaded===true){aniSvg.arDivobj[0]=undefined;aniSvg.pc.startArticle=parseInt(aniSvg.arDivobj[1].getAttribute("data-pno"))-1;}
else{aniSvg.arDivobj[aniSvg.si]=undefined;aniSvg.pc.startidx++;}
if(aniSvg.pc.get_reachTarget()===true){aniSvg.smcState="";finish_turnover();}
else{aniSvg.pc.loadArticle--;aniSvg.load_prevImage();}}
aniSvg.get_pageFromShowkind=function(){return PageInfo.get_pageFromShowkind(aniSvg.pc.startArticle+1)+"-"+PageInfo.get_pageFromShowkind(aniSvg.pc.finalArticle+1);}
aniSvg.onresize_func=function(){aniSvg.set_arEpsPoint();var x1,y1,divNode;for(var i=aniSvg.pc.startidx;i<=aniSvg.pc.finalidx;i++){x1=aniSvg.arEpsPointX[i];y1=aniSvg.arEpsPointY[i];divNode=aniSvg.arDivobj[i];if(i===11){divNode.style.left=(x1-ScreenInfo.smImageWidthHalf-20)+"px";divNode.style.top=(y1-30)+"px";}
else{divNode.style.left=(x1-ScreenInfo.smImageWidthHalf*aniSvg.basicScale-20)+"px";divNode.style.top=y1+"px";}}
ScreenInfo.set_smRectDrag(aniSvg.arEpsPointX[11]-ScreenInfo.smImageWidthHalf-1,aniSvg.arEpsPointY[11]+15);}
aniSvg.set_arEpsPoint=function(){var cx=cataRect.centerPt.x;var cy=cataRect.centerPt.y-(aniSvg.thumbHeight+125)/2;var a=Math.floor((cataRect.width-aniSvg.thumbWidth-120)/2);var b=90;aniSvg.arEpsPointX[4]=cx-a,aniSvg.arEpsPointY[4]=cy;aniSvg.arEpsPointX[18]=cx+a,aniSvg.arEpsPointY[18]=cy;var i,tx,ty;for(i=5;i<11;i++){ty=b*(i-4)/7;tx=aniSvg.get_ellipseXpoint(ty,a,b);aniSvg.arEpsPointX[i]=cx-tx,aniSvg.arEpsPointY[i]=cy+ty;aniSvg.arEpsPointX[22-i]=cx+tx,aniSvg.arEpsPointY[22-i]=cy+ty;}
for(i=0;i<4;i++){ty=b*(4-i)/7;tx=aniSvg.get_ellipseXpoint(ty,a,b);aniSvg.arEpsPointX[i]=cx-tx,aniSvg.arEpsPointY[i]=cy-ty;aniSvg.arEpsPointX[22-i]=cx+tx,aniSvg.arEpsPointY[22-i]=cy-ty;}
aniSvg.arEpsPointX[11]=cx,aniSvg.arEpsPointY[11]=cy+b;}
aniSvg.get_ellipseXpoint=function(ay,a,b){return Math.sqrt((1-(ay*ay)/(b*b))*a*a);}
aniSvg.get_ellipseYpoint=function(ax,a,b){return Math.sqrt((1-(ax*ax)/(a*a))*b*b);}
