function go_next(bool){if(aniSvg.smcState==="catimage"){if(bool===true)PageInfo.reset_pageNext();go_next2();}
else{aniSvg.go_swingChange(0,8,"next");}}
function go_next2(){Action.loaded=0;Action.loadto=0;var aaa=FileInfo.cimgFilePath(PageInfo.prevPage,"s","","*");if(aaa[0]===""){SmcObj.drawL=1;}
else{Action.loadto++;SmcObj.drawL=0;}
var bbb=FileInfo.cimgFilePath(PageInfo.prevPage+1,"s","","*");if(bbb[0]===""){SmcObj.drawR=1;}
else{Action.loadto++;SmcObj.drawR=0;}
if(SmcObj.drawL===0){catImageLN=new Image();if(ServerInfo.applyCipher===true){load_cipherImage('btn',0,aaa[0],go_prevLNCipher);}
else{catImageLN.src=aaa[0];catImageLN.onload=go_next3;}}
if(SmcObj.drawR===0){catImageRN=new Image();if(ServerInfo.applyCipher===true){load_cipherImage('btn',0,bbb[0],go_prevRNCipher);}
else{catImageRN.src=bbb[0];catImageRN.onload=go_next3;}}}
function go_nextLNCipher(skd,npage,urlsrc){catImageLN.src=urlsrc;catImageLN.onload=go_next3;}
function go_nextRNCipher(skd,npage,urlsrc){catImageRN.src=urlsrc;catImageRN.onload=go_next3;}
function go_next3(){Action.loaded++;if(Action.loadto===Action.loaded){Action.drawCondition=2;prepare_turnover();AniObj.seq=0;next_animateR();smcDiv.style.visibility="hidden";AniObj.seq=0;AniObj.timer=setInterval(next_animateR,AniObj.transInterval);}}
function next_animateR(){clear_canvas();var percent=AniObj.transPercent[AniObj.seq];if(SmcObj.drawL===1){cntx.fillStyle=ScreenInfo.blankColor;cntx.fillRect(smRect.x,smRect.y+ScreenInfo.smImageHeight*percent*0.5,ScreenInfo.smImageWidth,ScreenInfo.smImageHeight*percent);}
else{cntx.drawImage(catImageLN,0,0,ScreenInfo.smImageOriWidth,ScreenInfo.smImageOriHeight,smRect.x,smRect.y+ScreenInfo.smImageHeight*percent*0.5,ScreenInfo.smImageWidth,ScreenInfo.smImageHeight*(1-percent));}
if(ScreenInfo.onesmc===false){if(SmcObj.drawR===1){cntx.fillStyle=ScreenInfo.blankColor;cntx.fillRect(smRect.centerPt.x,smRect.y+ScreenInfo.smImageHeight*percent*0.5,ScreenInfo.smImageWidth,ScreenInfo.smImageHeight*percent);}
else{cntx.drawImage(catImageRN,0,0,ScreenInfo.smImageOriWidth,ScreenInfo.smImageOriHeight,smRect.centerPt.x,smRect.y+ScreenInfo.smImageHeight*percent*0.5,ScreenInfo.smImageWidth,ScreenInfo.smImageHeight*(1-percent));}}
AniObj.seq++;if(AniObj.seq==AniObj.transLen-1){clearInterval(AniObj.timer);after_nextRanimateComplete();}}
function after_nextRanimateComplete(){Action.loaded=0;Action.loadto=0;var aaa=FileInfo.cimgFilePath(PageInfo.currentPage,"s","","*");if(aaa[0]===""){SmcObj.drawL=1;}
else{Action.loadto++;SmcObj.drawL=0;}
var bbb=FileInfo.cimgFilePath(PageInfo.currentPage+1,"s","","*");if(bbb[0]===""){SmcObj.drawR=1;}
else{Action.loadto++;SmcObj.drawR=0;}
if(SmcObj.drawL===0){catImageLN=new Image();if(ServerInfo.applyCipher===true){load_cipherImage('btn',0,aaa[0],go_prevLNCipher);}
else{catImageLN.src=aaa[0];catImageLN.onload=go_next4;}}
if(SmcObj.drawR===0){catImageRN=new Image();if(ServerInfo.applyCipher===true){load_cipherImage('btn',0,bbb[0],go_prevRNCipher);}
else{catImageRN.src=bbb[0];catImageRN.onload=go_next4;}}}
function go_prevLNCipher(skd,npage,urlsrc){catImageLN.src=urlsrc;catImageLN.onload=go_next4;}
function go_prevRNCipher(skd,npage,urlsrc){catImageRN.src=urlsrc;catImageRN.onload=go_next4;}
function go_next4(){Action.loaded++;if(Action.loadto===Action.loaded){AniObj.seq=0;AniObj.timer=setInterval(next_animateL,AniObj.transInterval);}}
function next_animateL(){clear_canvas();var percent=AniObj.transPercent[AniObj.seq];if(SmcObj.drawL===1){cntx.fillStyle=ScreenInfo.blankColor;cntx.fillRect(smRect.x,smRect.y+ScreenInfo.smImageWidth*(1-percent),ScreenInfo.smImageWidth,ScreenInfo.smImageHeight*percent);}
else{cntx.drawImage(catImageLN,0,0,ScreenInfo.smImageOriWidth,ScreenInfo.smImageOriHeight,smRect.x,smRect.y+ScreenInfo.smImageHeight*(1-percent)*0.5,ScreenInfo.smImageWidth,ScreenInfo.smImageHeight*percent);}
if(ScreenInfo.onesmc===false){if(SmcObj.drawR===1){cntx.fillStyle=ScreenInfo.blankColor;cntx.fillRect(smRect.centerPt.x,smRect.y+ScreenInfo.smImageWidth*(1-percent),ScreenInfo.smImageWidth,ScreenInfo.smImageHeight*percent);}
else{cntx.drawImage(catImageRN,0,0,ScreenInfo.smImageOriWidth,ScreenInfo.smImageOriHeight,smRect.centerPt.x,smRect.y+ScreenInfo.smImageHeight*(1-percent)*0.5,ScreenInfo.smImageWidth,ScreenInfo.smImageHeight*percent);}}
AniObj.seq++;if(AniObj.seq===AniObj.transPercent.length-1){clearInterval(AniObj.timer);finish_turnover();}}
function go_prev(bool){if(aniSvg.smcState==="catimage"){if(bool==true)PageInfo.reset_pagePrev();go_next2();}
else{aniSvg.go_swingChange(0,7,"prev");}}
function go_direct(n){if(aniSvg.smcState==="catimage"){n=PageInfo.get_directPageNo(n);if(n<1)n=1;PageInfo.prevPage=PageInfo.currentPage;PageInfo.currentPage=n;go_next2();}
else{aniSvg.go_direct(n);}}
function prepare_turnover(){if(glassesSvg!=undefined)unload_glasses();if(soundctrlSvg!=undefined)unload_soundcontrol();AniObj.seq=0;cntx.globalAlpha=1;if(mainCnv.width!==winRect.width){maincnvDiv.style.width=winRect.width+"px";maincnvDiv.style.height=winRect.height+"px";mainCnv.width=winRect.width;mainCnv.height=winRect.height;}
SmcObj.prepare_turnover();}
function finish_turnover(){SmcObj.finish_turnover();}
function finish_turnover2(){smcDiv.style.visibility="visible";clear_canvas();mainCnv.width=1;mainCnv.height=1;maincnvDiv.style.width="1px";maincnvDiv.style.height="1px";Action.drawCondition=0;if(MoveInfo.pairEnlarge==true)Action.set_togetherEnlarge();MoveInfo.show_pageNumber();CoverObj.set_cover();if(Action.mainState==="slide"){if(SmcObj.nextPermission("wheel")===false||PermitMan.access_memberZone(-1,"wheel")===false){Action.mainState="stop";}
else if(MoveInfo.loadLinkAtSlide==true){SmcObj.show_linkData();}
if(Action.mainState==="slide"){setTimeout("go_next(true)",MoveInfo.slideIntervalSM);return;}}
if(Action.mainState==="stop")Action.mainState="normal";SmcObj.show_outData();ScreenMan.finish_turnover();Action.aniLocking=false;}
function init_smc2(){PermitMan.aniSvg=true;anicnvDiv.style.visibility="visible";anicnvDiv.style.zIndex="10";anicnvDiv.innerHTML="<canvas id='anicnv' width='"+stageWidth+"' height='"+stageHeight+"'></canvas>";try{gl=document.getElementById("anicnv").getContext('experimental-webgl');if(!gl)gl=document.getElementById("anicnv").getContext('webgl');}
catch(e){alert("canvas webgl getContext() error : "+e.toString());}
gl.viewportWidth=stageWidth;gl.viewportHeight=stageHeight;aniSvg.pc=new PagingCont();aniSvg.pc.totalArticles=PageInfo.cataPages;aniSvg.pc.set_articlesOnPage(6);aniSvg.pc.set_currentPage(1);aniSvg.pMatrix=new Float32Array(16);aniSvg.perspectiveMatrix(50,gl.viewportWidth/gl.viewportHeight,0.1,100.0);aniSvg.mvMatrix=new Float32Array(16);aniSvg.prepareMatrix();aniSvg.normalMatrix=new Float32Array(9);if(aniSvg.init_shaders()===false)return;aniSvg.init_buffers();gl.enable(gl.DEPTH_TEST);aniSvg.init_textures();}
aniSvg={timer:undefined,drawInterval:30,changeInterval:15,seq:0,loaded:0,loadto:0,smcState:'stop',firstLoading:true,catTexture:[],arVertex:[],cnvPoint:[],shaderProgram:undefined,pMatrix:undefined,mvMatrix:undefined,normalMatrix:undefined,cubeVertexPositionBuffer:undefined,cubeVertexNormalBuffer:undefined,cubeVertexTextureCoordBuffer:undefined,cubeVertexIndexBuffer:undefined,ySpeed:-0.5,xRot:20,yRot:0,normalAlpha:1.0,overAlpha:0.95,pc:undefined,mouseDragged:false,befX:0,overIndex:-1};aniSvg.do_afterAllLoaded=function(){if(aniSvg.smcState==="stop"){aniSvg.smcState="swing";aniSvg.timer=setInterval(aniSvg.drawScene,aniSvg.drawInterval);if(aniSvg.firstLoading===true){aniSvg.drawScene();if(CataInfo.incview==="d"){anicnvDiv.addEventListener("mousedown",aniSvg.do_mouseDown,false);anicnvDiv.addEventListener("mousemove",aniSvg.do_mouseMove,false);anicnvDiv.addEventListener("mouseup",aniSvg.do_mouseUp,false);}
else{anicnvDiv.addEventListener("touchstart",aniSvg.do_touchStart,false);anicnvDiv.addEventListener("touchmove",aniSvg.do_touchMove,false);anicnvDiv.addEventListener("touchend",aniSvg.do_touchEnd,false);}
aniSvg.firstLoading=false;}}
else if(aniSvg.smcState==="swingchange"){aniSvg.timer=setInterval(aniSvg.swingchange_animateRear,aniSvg.changeInterval);}}
aniSvg.go_direct=function(n){aniSvg.go_swingChange(n,9,"direct");}
aniSvg.go_swingChange=function(n,drawC,s){if(aniSvg.get_swingPermission(s,n)==false){Action.aniLocking=false;return;}
Action.drawCondition=drawC;tempN=n;aniSvg.smcState="swingchange";aniSvg.timer=setInterval(aniSvg.swingchange_animateFrt,aniSvg.changeInterval);}
aniSvg.go_swingPage=function(skd,n){if(skd==="first")aniSvg.pc.set_currentPage(1);else if(skd==="prev")aniSvg.pc.set_currentPage(aniSvg.pc.currentPage-1);else if(skd==="next")aniSvg.pc.set_currentPage(aniSvg.pc.currentPage+1);else if(skd==="last")aniSvg.pc.set_currentPage(aniSvg.pc.finalPage);else aniSvg.pc.set_currentPage(n);aniSvg.init_textures();}
aniSvg.swingchange_animateFrt=function(){if(aniSvg.ySpeed>0)aniSvg.ySpeed+=0.8;else aniSvg.ySpeed-=0.8;aniSvg.normalAlpha-=0.1;if(aniSvg.normalAlpha<=0){clearInterval(aniSvg.timer);aniSvg.timer=undefined;if(Action.drawCondition===7)aniSvg.go_swingPage("prev",0);else if(Action.drawCondition===8)aniSvg.go_swingPage("next",0);else{aniSvg.go_swingPage("direct",aniSvg.pc.get_pageFromArticle(tempN-1));}}}
aniSvg.swingchange_animateRear=function(){if(aniSvg.ySpeed>0)aniSvg.ySpeed-=0.8;else aniSvg.ySpeed+=0.8;aniSvg.normalAlpha+=0.1;if(aniSvg.normalAlpha>=1.0){clearInterval(aniSvg.timer);aniSvg.timer=undefined;aniSvg.smcState="swing";Action.drawCondition=0;Action.aniLocking=false;MoveInfo.show_pageNumber();}}
aniSvg.set_rotateSpeed=function(time,distance){var fn=-distance/time*3;if(fn>2)aniSvg.ySpeed=2;else if(fn<-2)aniSvg.ySpeed=-2;else if(-0.3<fn&&fn<0.3)return false;else aniSvg.ySpeed=fn;return true;}
aniSvg.get_pageFromShowkind=function(){if(aniSvg.smcState==="catimage")return PageInfo.get_pageshowString(PageInfo.currentPage);return PageInfo.get_pageFromShowkind(aniSvg.pc.startArticle+1)+"-"+PageInfo.get_pageFromShowkind(aniSvg.pc.finalArticle+1);}
aniSvg.onresize_func=function(){document.getElementById("anicnv").width=stageWidth;document.getElementById("anicnv").height=stageHeight;gl.viewportWidth=stageWidth;gl.viewportHeight=stageHeight;aniSvg.pMatrix=new Float32Array(16);aniSvg.perspectiveMatrix(50,gl.viewportWidth/gl.viewportHeight,0.1,100.0);aniSvg.make_stopState();aniSvg.drawScene();}
aniSvg.make_stopState=function(){if(aniSvg.timer){clearInterval(aniSvg.timer);aniSvg.timer=undefined;}
aniSvg.smcState="stop";}
aniSvg.make_swingState=function(){aniSvg.timer=setInterval(aniSvg.drawScene,aniSvg.drawInterval);aniSvg.smcState="swing";}
aniSvg.make_catimageState=function(n){n=PageInfo.get_directPageNo(n);if(n<1)n=1;PageInfo.prevPage=PageInfo.currentPage;PageInfo.currentPage=n;Action.mouseDownBlock=true;SmcObj.onload_func2();smcDiv.style.visibility="visible";linkoutDiv.style.visibility="visible";aniSvg.smcState="catimage";}
aniSvg.escape_catimageState=function(){SmcObj.unload_func();smcDiv.style.visibility="hidden";linkoutDiv.style.visibility="hidden";MoveInfo.show_pageNumber();}
aniSvg.get_swingPermission=function(smove,n){if(smove==="next"&&aniSvg.pc.currentPage===aniSvg.pc.totalPages)return false;else if(smove==="prev"&&aniSvg.pc.currentPage===1)return false;else if(smove==="direct"&&aniSvg.pc.contain_article(n)===true)return false;return true;}
aniSvg.do_mouseDown=function(e){clickX=e.clientX;clickY=e.clientY;Action.touchStartTime=MoveInfo.get_currTime();}
aniSvg.do_mouseMove=function(e){var cx=e.clientX;var cy=e.clientY;if(aniSvg.smcState==="catimage")return;aniSvg.befX=cx;if(Action.mouseDowned===true){if(aniSvg.mouseDragged===false)aniSvg.mouseDragged=true;var ang=aniSvg.xRot+(cy-clickY)/300;if(ang>20)ang=20;else if(ang<-35)ang=-35;aniSvg.xRot=ang;if(aniSvg.smcState==="stop")aniSvg.drawScene();return;}
var arRealseq=[0,2,4,5,3,1];var arSideseq=[];if(aniSvg.xRot>-3.9)arSideseq.push(2);else if(aniSvg.xRot<-24)arSideseq.push(3);var yRotRem=aniSvg.yRot%360;if(yRotRem<78)arSideseq.push(0,5);else if(yRotRem<168)arSideseq.push(5,1);else if(yRotRem<258)arSideseq.push(1,4);else if(yRotRem<348)arSideseq.push(4,0);else arSideseq.push(0,5);var k=0;var overidx=-1;for(var i=0;i<arSideseq.length;i++){k=arSideseq[i];if(aniSvg.isPointInRectangle(cx,cy,aniSvg.cnvPoint,k)===true){overidx=arRealseq[k];break;}}
aniSvg.overIndex=overidx;if(overidx===-1){if(aniSvg.timer==undefined)aniSvg.make_swingState();}
else{aniSvg.make_stopState();}}
aniSvg.do_mouseUp=function(e){if(aniSvg.smcState==="catimage"){aniSvg.escape_catimageState();aniSvg.make_stopState();aniSvg.mouseDragged=false;return;}
if(aniSvg.smcState==="swing"){aniSvg.set_rotateSpeed(MoveInfo.get_currTime()-Action.touchStartTime,aniSvg.befX-clickX);aniSvg.mouseDragged=false;return;}
if(aniSvg.overIndex===-1)return;if(aniSvg.mouseDragged===true){aniSvg.mouseDragged=false;return;}
var n=aniSvg.pc.startArticle+aniSvg.overIndex+1;aniSvg.make_catimageState(n);}
aniSvg.do_touchStart=function(e){clickX=e.touches[0].clientX;clickY=e.touches[0].clientY;befX=clickX,befY=clickY;Action.touchStartTime=MoveInfo.get_currTime();Action.do_touchStart("smc",e);}
aniSvg.do_touchMove=function(e){befX=e.touches[0].clientX;befY=e.touches[0].clientY;if(aniSvg.smcState==="catimage")return;if(Action.mouseDowned===true){if(aniSvg.mouseDragged===false)aniSvg.mouseDragged=true;var ang=aniSvg.xRot+(befY-clickY)/300;if(ang>20)ang=20;else if(ang<-35)ang=-35;aniSvg.xRot=ang;if(aniSvg.smcState==="stop")aniSvg.drawScene();}}
aniSvg.do_touchEnd=function(){var arRealseq=[0,2,4,5,3,1];var arSideseq=[];if(aniSvg.xRot>-3.9)arSideseq.push(2);else if(aniSvg.xRot<-24)arSideseq.push(3);var yRotRem=aniSvg.yRot%360;if(yRotRem<78)arSideseq.push(0,5);else if(yRotRem<168)arSideseq.push(5,1);else if(yRotRem<258)arSideseq.push(1,4);else if(yRotRem<348)arSideseq.push(4,0);else arSideseq.push(0,5);var k=0;var overidx=-1;for(var i=0;i<arSideseq.length;i++){k=arSideseq[i];if(aniSvg.isPointInRectangle(befX,befY,aniSvg.cnvPoint,k)===true){overidx=arRealseq[k];break;}}
if(overidx===-1){if(aniSvg.smcState==="catimage")aniSvg.escape_catimageState();if(aniSvg.timer==undefined)aniSvg.make_swingState();else{aniSvg.set_rotateSpeed(MoveInfo.get_currTime()-Action.touchStartTime,befX-clickX);}}
else{if(aniSvg.mouseDragged===true){aniSvg.mouseDragged=false;return;}
aniSvg.overIndex=overidx;aniSvg.make_stopState();var n=aniSvg.pc.startArticle+aniSvg.overIndex+1;aniSvg.make_catimageState(n);}}
aniSvg.init_shaders=function(){var fragmentShader=aniSvg.get_fragmentShader();var vertexShader=aniSvg.get_vertexShader();aniSvg.shaderProgram=gl.createProgram();gl.attachShader(aniSvg.shaderProgram,vertexShader);gl.attachShader(aniSvg.shaderProgram,fragmentShader);gl.linkProgram(aniSvg.shaderProgram);if(!gl.getProgramParameter(aniSvg.shaderProgram,gl.LINK_STATUS)){alert("Could not initialise shaders");return false;}
gl.useProgram(aniSvg.shaderProgram);aniSvg.shaderProgram.vertexPositionAttribute=gl.getAttribLocation(aniSvg.shaderProgram,"aVertexPosition");gl.enableVertexAttribArray(aniSvg.shaderProgram.vertexPositionAttribute);aniSvg.shaderProgram.vertexNormalAttribute=gl.getAttribLocation(aniSvg.shaderProgram,"aVertexNormal");gl.enableVertexAttribArray(aniSvg.shaderProgram.vertexNormalAttribute);aniSvg.shaderProgram.textureCoordAttribute=gl.getAttribLocation(aniSvg.shaderProgram,"aTextureCoord");gl.enableVertexAttribArray(aniSvg.shaderProgram.textureCoordAttribute);aniSvg.shaderProgram.pMatrixUniform=gl.getUniformLocation(aniSvg.shaderProgram,"uPMatrix");aniSvg.shaderProgram.mvMatrixUniform=gl.getUniformLocation(aniSvg.shaderProgram,"uMVMatrix");aniSvg.shaderProgram.nMatrixUniform=gl.getUniformLocation(aniSvg.shaderProgram,"uNMatrix");aniSvg.shaderProgram.samplerUniform=gl.getUniformLocation(aniSvg.shaderProgram,"uSampler");aniSvg.shaderProgram.alphaUniform=gl.getUniformLocation(aniSvg.shaderProgram,"uAlpha");aniSvg.shaderProgram.ambientColorUniform=gl.getUniformLocation(aniSvg.shaderProgram,"uAmbientColor");aniSvg.shaderProgram.lightingDirectionUniform=gl.getUniformLocation(aniSvg.shaderProgram,"uLightingDirection");aniSvg.shaderProgram.directionalColorUniform=gl.getUniformLocation(aniSvg.shaderProgram,"uDirectionalColor");return true;}
aniSvg.get_vertexShader=function(){var s="attribute vec3 aVertexPosition;"
+"attribute vec2 aTextureCoord;"
+"attribute vec3 aVertexNormal;"
+"uniform mat4 uMVMatrix;"
+"uniform mat4 uPMatrix;"
+"uniform mat3 uNMatrix;"
+"uniform vec3 uAmbientColor;"
+"uniform vec3 uLightingDirection;"
+"uniform vec3 uDirectionalColor;"
+"varying vec2 vTextureCoord;"
+"varying vec3 vLightWeighting;"
+"void main(void){"
+"	gl_Position = uPMatrix * uMVMatrix * vec4(aVertexPosition, 1.0);"
+" vTextureCoord = aTextureCoord;"
+"	vec3 transformedNormal = uNMatrix * aVertexNormal;"
+"	float directionalLightWeighting = max(dot(transformedNormal, uLightingDirection), 0.0);"
+"	vLightWeighting = uAmbientColor + uDirectionalColor * directionalLightWeighting;"
+"}";var v=gl.createShader(gl.VERTEX_SHADER);gl.shaderSource(v,s);gl.compileShader(v);return v;}
aniSvg.get_fragmentShader=function(){var s="precision mediump float;"
+"varying highp vec2 vTextureCoord;"
+"varying highp vec3 vLightWeighting;"
+"uniform sampler2D uSampler;"
+"uniform float uAlpha;"
+"void main(void){"
+"	vec4 texColor = texture2D(uSampler, vTextureCoord);"
+" gl_FragColor = vec4(texColor.rgb*vLightWeighting, uAlpha);"
+"}";var f=gl.createShader(gl.FRAGMENT_SHADER);gl.shaderSource(f,s);gl.compileShader(f);return f;}
aniSvg.init_buffers=function(){var vertices=[-1.0,-1.0,1.0,1.0,-1.0,1.0,1.0,1.0,1.0,-1.0,1.0,1.0,-1.0,-1.0,-1.0,-1.0,1.0,-1.0,1.0,1.0,-1.0,1.0,-1.0,-1.0,-1.0,1.0,-1.0,-1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,-1.0,-1.0,-1.0,-1.0,1.0,-1.0,-1.0,1.0,-1.0,1.0,-1.0,-1.0,1.0,1.0,-1.0,-1.0,1.0,1.0,-1.0,1.0,1.0,1.0,1.0,-1.0,1.0,-1.0,-1.0,-1.0,-1.0,-1.0,1.0,-1.0,1.0,1.0,-1.0,1.0,-1.0];aniSvg.arVertex=vertices.slice(0);aniSvg.cubeVertexPositionBuffer=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,aniSvg.cubeVertexPositionBuffer);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array(vertices),gl.STATIC_DRAW);aniSvg.cubeVertexPositionBuffer.itemSize=3;aniSvg.cubeVertexPositionBuffer.numItems=24;var vertexNormals=[0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,-1.0,0.0,0.0,-1.0,0.0,0.0,-1.0,0.0,0.0,-1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,-1.0,0.0,0.0,-1.0,0.0,0.0,-1.0,0.0,0.0,-1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,-1.0,0.0,0.0,-1.0,0.0,0.0,-1.0,0.0,0.0,-1.0,0.0,0.0];aniSvg.cubeVertexNormalBuffer=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,aniSvg.cubeVertexNormalBuffer);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array(vertexNormals),gl.STATIC_DRAW);aniSvg.cubeVertexNormalBuffer.itemSize=3;aniSvg.cubeVertexNormalBuffer.numItems=24;var textureCoords=[0.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,1.0,1.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0];aniSvg.cubeVertexTextureCoordBuffer=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,aniSvg.cubeVertexTextureCoordBuffer);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array(textureCoords),gl.STATIC_DRAW);aniSvg.cubeVertexTextureCoordBuffer.itemSize=2;aniSvg.cubeVertexTextureCoordBuffer.numItems=24;var cubeVertexIndices=[0,1,2,0,2,3,4,5,6,4,6,7,8,9,10,8,10,11,12,13,14,12,14,15,16,17,18,16,18,19,20,21,22,20,22,23];aniSvg.cubeVertexIndexBuffer=gl.createBuffer();gl.bindBuffer(gl.ELEMENT_ARRAY_BUFFER,aniSvg.cubeVertexIndexBuffer);gl.bufferData(gl.ELEMENT_ARRAY_BUFFER,new Uint16Array(cubeVertexIndices),gl.STATIC_DRAW);aniSvg.cubeVertexIndexBuffer.itemSize=1;aniSvg.cubeVertexIndexBuffer.numItems=36;}
aniSvg.init_textures=function(){aniSvg.loaded=0;aniSvg.loadto=6;var k=0;for(var i=aniSvg.pc.startArticle;i<=aniSvg.pc.finalArticle;i++){var aaa=FileInfo.thumbFilePath(i+1,"s","","*");if(ServerInfo.applyCipher===true)load_cipherImage('cube',k,aaa[0],aniSvg.initTexture2);else aniSvg.catTexture[k]=aniSvg.initTexture(aaa[0]);k++;}
for(i=5;i>=k;i--){aniSvg.catTexture[i]=aniSvg.initTexture(FileInfo.skin5FilePath("etc/grey.png"));}}
aniSvg.initTexture=function(imgUrl){var crateImage=new Image();var texture=gl.createTexture();texture.image=crateImage;crateImage.src=imgUrl;crateImage.onload=function(){aniSvg.handleLoadedTexture(texture);}
return texture;}
aniSvg.initTexture2=function(skd,npage,urlsrc){var crateImage=new Image();var texture=gl.createTexture();texture.image=crateImage;crateImage.src=urlsrc;crateImage.onload=function(){aniSvg.handleLoadedTexture(texture);}
aniSvg.catTexture[npage]=texture;}
aniSvg.handleLoadedTexture=function(texture){gl.bindTexture(gl.TEXTURE_2D,texture);gl.pixelStorei(gl.UNPACK_FLIP_Y_WEBGL,true);gl.texImage2D(gl.TEXTURE_2D,0,gl.RGBA,gl.RGBA,gl.UNSIGNED_BYTE,texture.image);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MAG_FILTER,gl.LINEAR);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MIN_FILTER,gl.LINEAR);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_S,gl.CLAMP_TO_EDGE);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_T,gl.CLAMP_TO_EDGE);gl.bindTexture(gl.TEXTURE_2D,null);aniSvg.loaded++;if(aniSvg.loaded===aniSvg.loadto){aniSvg.do_afterAllLoaded();}}
aniSvg.drawScene=function(){if(aniSvg.smcState!=="stop")aniSvg.yRot-=aniSvg.ySpeed;gl.viewport(0,0,gl.viewportWidth,gl.viewportHeight);gl.clear(gl.COLOR_BUFFER_BIT|gl.DEPTH_BUFFER_BIT);aniSvg.rotateMatrixXY(get_radFromdeg(aniSvg.xRot),get_radFromdeg(aniSvg.yRot));aniSvg.lightingMatrix();gl.uniform1f(aniSvg.shaderProgram.alphaUniform,aniSvg.normalAlpha);gl.bindBuffer(gl.ARRAY_BUFFER,aniSvg.cubeVertexPositionBuffer);gl.vertexAttribPointer(aniSvg.shaderProgram.vertexPositionAttribute,aniSvg.cubeVertexPositionBuffer.itemSize,gl.FLOAT,false,0,0);gl.bindBuffer(gl.ARRAY_BUFFER,aniSvg.cubeVertexNormalBuffer);gl.vertexAttribPointer(aniSvg.shaderProgram.vertexNormalAttribute,aniSvg.cubeVertexNormalBuffer.itemSize,gl.FLOAT,false,0,0);gl.bindBuffer(gl.ARRAY_BUFFER,aniSvg.cubeVertexTextureCoordBuffer);gl.vertexAttribPointer(aniSvg.shaderProgram.textureCoordAttribute,aniSvg.cubeVertexTextureCoordBuffer.itemSize,gl.FLOAT,false,0,0);gl.bindBuffer(gl.ELEMENT_ARRAY_BUFFER,aniSvg.cubeVertexIndexBuffer);gl.uniformMatrix4fv(aniSvg.shaderProgram.pMatrixUniform,false,aniSvg.pMatrix);gl.uniformMatrix4fv(aniSvg.shaderProgram.mvMatrixUniform,false,aniSvg.mvMatrix);gl.uniformMatrix3fv(aniSvg.shaderProgram.nMatrixUniform,false,aniSvg.normalMatrix);gl.activeTexture(gl.TEXTURE0);gl.uniform1i(aniSvg.shaderProgram.samplerUniform,0);gl.bindTexture(gl.TEXTURE_2D,aniSvg.catTexture[0]);gl.drawElements(gl.TRIANGLES,6,gl.UNSIGNED_SHORT,0);gl.bindTexture(gl.TEXTURE_2D,aniSvg.catTexture[2]);gl.drawElements(gl.TRIANGLES,6,gl.UNSIGNED_SHORT,12);gl.bindTexture(gl.TEXTURE_2D,aniSvg.catTexture[4]);gl.drawElements(gl.TRIANGLES,6,gl.UNSIGNED_SHORT,24);gl.bindTexture(gl.TEXTURE_2D,aniSvg.catTexture[5]);gl.drawElements(gl.TRIANGLES,6,gl.UNSIGNED_SHORT,36);gl.bindTexture(gl.TEXTURE_2D,aniSvg.catTexture[3]);gl.drawElements(gl.TRIANGLES,6,gl.UNSIGNED_SHORT,48);gl.bindTexture(gl.TEXTURE_2D,aniSvg.catTexture[1]);gl.drawElements(gl.TRIANGLES,6,gl.UNSIGNED_SHORT,60);gl.uniform1i(aniSvg.shaderProgram.useLightingUniform,0);gl.uniform3f(aniSvg.shaderProgram.ambientColorUniform,0.6,0.6,0.6);gl.uniform3f(aniSvg.shaderProgram.lightingDirectionUniform,0.57,0.57,0.57);gl.uniform3f(aniSvg.shaderProgram.directionalColorUniform,0.6,0.6,0.6);var pt={x:0,y:0,z:0};for(var i=0;i<72;i+=3){aniSvg.ptpersProject(aniSvg.arVertex[i],aniSvg.arVertex[i+1],aniSvg.arVertex[i+2],pt);aniSvg.cnvPoint[i]=pt.x;aniSvg.cnvPoint[i+1]=pt.y;aniSvg.cnvPoint[i+2]=pt.z;}
}
aniSvg.perspectiveMatrix=function(fovy,aspect,near,far){var top=near*Math.tan(fovy*Math.PI/360.0);var right=top*aspect;var left=-right;var bottom=-top;var rl=(right-left);var tb=(top-bottom);var fn=(far-near);aniSvg.pMatrix[0]=(near*2)/rl;aniSvg.pMatrix[1]=0;aniSvg.pMatrix[2]=0;aniSvg.pMatrix[3]=0;aniSvg.pMatrix[4]=0;aniSvg.pMatrix[5]=(near*2)/tb;aniSvg.pMatrix[6]=0;aniSvg.pMatrix[7]=0;aniSvg.pMatrix[8]=(right+left)/rl;aniSvg.pMatrix[9]=(top+bottom)/tb;aniSvg.pMatrix[10]=-(far+near)/fn;aniSvg.pMatrix[11]=-1;aniSvg.pMatrix[12]=0;aniSvg.pMatrix[13]=0;aniSvg.pMatrix[14]=-(far*near*2)/fn;aniSvg.pMatrix[15]=0;}
aniSvg.prepareMatrix=function(){aniSvg.prepMatrix=new Float32Array(16);aniSvg.prepMatrix[0]=1;aniSvg.prepMatrix[1]=0;aniSvg.prepMatrix[2]=0;aniSvg.prepMatrix[3]=0;aniSvg.prepMatrix[4]=0;aniSvg.prepMatrix[5]=1;aniSvg.prepMatrix[6]=0;aniSvg.prepMatrix[7]=0;aniSvg.prepMatrix[8]=0;aniSvg.prepMatrix[9]=0;aniSvg.prepMatrix[10]=1;aniSvg.prepMatrix[11]=0;aniSvg.prepMatrix[12]=0;aniSvg.prepMatrix[13]=0;aniSvg.prepMatrix[14]=0;aniSvg.prepMatrix[15]=1;var x=0,y=0,z=-5;aniSvg.prepMatrix[12]=aniSvg.prepMatrix[0]*x+aniSvg.prepMatrix[4]*y+aniSvg.prepMatrix[8]*z+aniSvg.prepMatrix[12];aniSvg.prepMatrix[13]=aniSvg.prepMatrix[1]*x+aniSvg.prepMatrix[5]*y+aniSvg.prepMatrix[9]*z+aniSvg.prepMatrix[13];aniSvg.prepMatrix[14]=aniSvg.prepMatrix[2]*x+aniSvg.prepMatrix[6]*y+aniSvg.prepMatrix[10]*z+aniSvg.prepMatrix[14];aniSvg.prepMatrix[15]=aniSvg.prepMatrix[3]*x+aniSvg.prepMatrix[7]*y+aniSvg.prepMatrix[11]*z+aniSvg.prepMatrix[15];var phiX=get_radFromdeg(aniSvg.xRot);var s=Math.sin(phiX);var c=Math.cos(phiX);aniSvg.prepMatrix[4]=aniSvg.prepMatrix[4]*c+aniSvg.prepMatrix[8]*s;aniSvg.prepMatrix[5]=aniSvg.prepMatrix[5]*c+aniSvg.prepMatrix[9]*s;aniSvg.prepMatrix[6]=aniSvg.prepMatrix[6]*c+aniSvg.prepMatrix[10]*s;aniSvg.prepMatrix[7]=aniSvg.prepMatrix[7]*c+aniSvg.prepMatrix[11]*s;aniSvg.prepMatrix[8]=-aniSvg.prepMatrix[4]*s+aniSvg.prepMatrix[8]*c;aniSvg.prepMatrix[9]=-aniSvg.prepMatrix[5]*s+aniSvg.prepMatrix[9]*c;aniSvg.prepMatrix[10]=-aniSvg.prepMatrix[6]*s+aniSvg.prepMatrix[10]*c;aniSvg.prepMatrix[11]=-aniSvg.prepMatrix[7]*s+aniSvg.prepMatrix[11]*c;}
aniSvg.rotateMatrixXY=function(phiX,phiY){aniSvg.mvMatrix[4]=aniSvg.prepMatrix[4];aniSvg.mvMatrix[5]=aniSvg.prepMatrix[5];aniSvg.mvMatrix[6]=aniSvg.prepMatrix[6];aniSvg.mvMatrix[7]=aniSvg.prepMatrix[7];aniSvg.mvMatrix[12]=aniSvg.prepMatrix[12];aniSvg.mvMatrix[13]=aniSvg.prepMatrix[13];aniSvg.mvMatrix[14]=aniSvg.prepMatrix[14];aniSvg.mvMatrix[15]=aniSvg.prepMatrix[15];var s=Math.sin(phiX);var c=Math.cos(phiX);aniSvg.mvMatrix[4]=aniSvg.prepMatrix[4]*c+aniSvg.prepMatrix[8]*s;aniSvg.mvMatrix[5]=aniSvg.prepMatrix[5]*c+aniSvg.prepMatrix[9]*s;aniSvg.mvMatrix[6]=aniSvg.prepMatrix[6]*c+aniSvg.prepMatrix[10]*s;aniSvg.mvMatrix[7]=aniSvg.prepMatrix[7]*c+aniSvg.prepMatrix[11]*s;aniSvg.mvMatrix[8]=-aniSvg.prepMatrix[4]*s+aniSvg.prepMatrix[8]*c;aniSvg.mvMatrix[9]=-aniSvg.prepMatrix[5]*s+aniSvg.prepMatrix[9]*c;aniSvg.mvMatrix[10]=-aniSvg.prepMatrix[6]*s+aniSvg.prepMatrix[10]*c;aniSvg.mvMatrix[11]=-aniSvg.prepMatrix[7]*s+aniSvg.prepMatrix[11]*c;s=Math.sin(phiY);c=Math.cos(phiY);aniSvg.mvMatrix[0]=aniSvg.prepMatrix[0]*c-aniSvg.mvMatrix[8]*s;aniSvg.mvMatrix[1]=aniSvg.prepMatrix[1]*c-aniSvg.mvMatrix[9]*s;aniSvg.mvMatrix[2]=aniSvg.prepMatrix[2]*c-aniSvg.mvMatrix[10]*s;aniSvg.mvMatrix[3]=aniSvg.prepMatrix[3]*c-aniSvg.mvMatrix[11]*s;aniSvg.mvMatrix[8]=aniSvg.prepMatrix[0]*s+aniSvg.mvMatrix[8]*c;aniSvg.mvMatrix[9]=aniSvg.prepMatrix[1]*s+aniSvg.mvMatrix[9]*c;aniSvg.mvMatrix[10]=aniSvg.prepMatrix[2]*s+aniSvg.mvMatrix[10]*c;aniSvg.mvMatrix[11]=aniSvg.prepMatrix[3]*s+aniSvg.mvMatrix[11]*c;}
aniSvg.lightingMatrix=function(){var a00=aniSvg.mvMatrix[0],a01=aniSvg.mvMatrix[1],a02=aniSvg.mvMatrix[2];var a10=aniSvg.mvMatrix[4],a11=aniSvg.mvMatrix[5],a12=aniSvg.mvMatrix[6];var a20=aniSvg.mvMatrix[8],a21=aniSvg.mvMatrix[9],a22=aniSvg.mvMatrix[10];var b01=a22*a11-a12*a21;var b11=-a22*a10+a12*a20;var b21=a21*a10-a11*a20;var d=a00*b01+a01*b11+a02*b21;if(!d)return;var id=1/d;aniSvg.normalMatrix[0]=b01*id;aniSvg.normalMatrix[1]=(-a22*a01+a02*a21)*id;aniSvg.normalMatrix[2]=(a12*a01-a02*a11)*id;aniSvg.normalMatrix[3]=b11*id;aniSvg.normalMatrix[4]=(a22*a00-a02*a20)*id;aniSvg.normalMatrix[5]=(-a12*a00+a02*a10)*id;aniSvg.normalMatrix[6]=b21*id;aniSvg.normalMatrix[7]=(-a21*a00+a01*a20)*id;aniSvg.normalMatrix[8]=(a11*a00-a01*a10)*id;a01=aniSvg.normalMatrix[1],a02=aniSvg.normalMatrix[2],a12=aniSvg.normalMatrix[5];aniSvg.normalMatrix[1]=aniSvg.normalMatrix[3];aniSvg.normalMatrix[2]=aniSvg.normalMatrix[6];aniSvg.normalMatrix[3]=a01;aniSvg.normalMatrix[5]=aniSvg.normalMatrix[7];aniSvg.normalMatrix[6]=a02;aniSvg.normalMatrix[7]=a12;}
aniSvg.ptpersProject=function(objx,objy,objz,tcoord){var t=new Array(8);t[0]=aniSvg.mvMatrix[0]*objx+aniSvg.mvMatrix[4]*objy+aniSvg.mvMatrix[8]*objz+aniSvg.mvMatrix[12];t[1]=aniSvg.mvMatrix[1]*objx+aniSvg.mvMatrix[5]*objy+aniSvg.mvMatrix[9]*objz+aniSvg.mvMatrix[13];t[2]=aniSvg.mvMatrix[2]*objx+aniSvg.mvMatrix[6]*objy+aniSvg.mvMatrix[10]*objz+aniSvg.mvMatrix[14];t[3]=aniSvg.mvMatrix[3]*objx+aniSvg.mvMatrix[7]*objy+aniSvg.mvMatrix[11]*objz+aniSvg.mvMatrix[15];t[4]=aniSvg.pMatrix[0]*t[0]+aniSvg.pMatrix[4]*t[1]+aniSvg.pMatrix[8]*t[2]+aniSvg.pMatrix[12]*t[3];t[5]=aniSvg.pMatrix[1]*t[0]+aniSvg.pMatrix[5]*t[1]+aniSvg.pMatrix[9]*t[2]+aniSvg.pMatrix[13]*t[3];t[6]=aniSvg.pMatrix[2]*t[0]+aniSvg.pMatrix[6]*t[1]+aniSvg.pMatrix[10]*t[2]+aniSvg.pMatrix[14]*t[3];t[7]=-t[2];if(t[7]==0.0){tcoord.x=0,tcoord.y=0,tcoord.z=0;return;}
t[7]=1.0/t[7];t[4]*=t[7];t[5]*=t[7];t[6]*=t[7];tcoord.x=(t[4]*0.5+0.5)*stageWidth+0.0;tcoord.y=stageHeight-(t[5]*0.5+0.5)*stageHeight+0.0;tcoord.z=(1.0+t[6])*0.5;}
aniSvg.isPointInRectangle=function(newX,newY,arPt,ii){var k=ii*12;var leftright=aniSvg.wsideLine(arPt[k],arPt[k+1],arPt[k+3],arPt[k+4],newX,newY);if(aniSvg.wsideLine(arPt[k+3],arPt[k+4],arPt[k+6],arPt[k+7],newX,newY)!==leftright)return false;if(aniSvg.wsideLine(arPt[k+6],arPt[k+7],arPt[k+9],arPt[k+10],newX,newY)!==leftright)return false;if(aniSvg.wsideLine(arPt[k+9],arPt[k+10],arPt[k],arPt[k+1],newX,newY)!==leftright)return false;return true;}
aniSvg.wsideLine=function(ax,ay,bx,by,cx,cy){if((bx-ax)*(cy-ay)-(by-ay)*(cx-ax)>0)return true;return false;}
aniSvg.showPoint=function(antx,cx,cy){antx.fillStyle="#0000FF";antx.beginPath();antx.moveTo(cx-5,cy+5);antx.lineTo(cx-5,cy-5);antx.lineTo(cx+5,cy-5);antx.lineTo(cx+5,cy+5);antx.fill();}
aniSvg.nextPermission=function(device){if(aniSvg.smcState==="catimage")return 0;if(MoveInfo.skipLastFirst===true&&aniSvg.pc.currentPage===aniSvg.pc.totalPages)return 2;return 1;}
aniSvg.prevPermission=function(device){if(aniSvg.smcState==="catimage")return 0;if(MoveInfo.skipLastFirst===true&&aniSvg.pc.currentPage===1)return 2;return 1;}
aniSvg.firstPermission=function(device){if(aniSvg.smcState==="catimage")return 0;if(aniSvg.pc.currentPage===1)return 2;return 1;}
aniSvg.lastPermission=function(device){if(aniSvg.smcState==="catimage")return 0;if(aniSvg.pc.currentPage===aniSvg.pc.totalPages)return 2;return 1;}
