var NOMOVE=999999;var stageWidth,stageHeight;var backDiv,logoDiv,hideDiv,printpageSvg,licenseSvg,specialSvg;var smctrDiv,ushapeDiv;var searchDiv,guideDiv,downDiv,descriptDiv;var backGrad;var menuSide,MenuObj,lowerSide,thumbDiv,pgthumbDiv,popthumbDiv,thumbSvg,mmpopDiv,BBwObj;var smcntDiv,smcDiv,encDiv,smcLinkDiv,LinkObj,Link2Obj,LinkPtrObj,dragDiv,ctrwinSvg,ImgwinObj,SoundItemObj;var maincnvDiv,mainCnv,anicnvDiv,aniSvg,gl;var onsmlDiv,onsmrDiv,OnsmObj;var mediaDiv,MediaObj,mediaPlayer;var soundDiv,soundctrlSvg;var bookdecoDiv,DecoObj;var splbtnDiv,SpacerObj,sprbtnDiv,splSvg,sprSvg,splbtnX,sprbtnX,splbtnY,sprbtnY;var linkoutDiv,linkoutObj;var cursorDiv,CursorObj,tooltipDiv;var comboDiv,combopopDiv,ComboObj,combopopObj,combopopSvg,combopop2Svg;var newinDiv,newin2Div,NewinObj,Newin2Obj,newinTmp,helpSvg,expSvg,spacerSvg,printSvg,searchSvg,mailSvg,noteSvg;var alertDiv,alertSvg,indexDiv,indexSvg,glassesDiv,glassesSvg,snsSvg;var pageiconDiv,debugDiv,expandDiv,snsDiv,loginDiv;var bboardSvg,colpkSvg,bbwDiv,memoDiv;var loaded=0;var loadto=0;var clickObj,clickX,clickY,befX,befY,bef2X,bef2Y;var tempW,tempH,tempN;var tempB,tempS;var arIndexText=[];var idxSeq=0;function go_general(n,skd){if(Action.mainState==="expand"){window.location="#epdiv"+n;return;}
Action.aniLocking=true;if(skd==="user"&&PageInfo.showStartPage>0)n=PageInfo.get_realFromShowPage(n);if(Action.drawCondition===-1)CoverObj.do_coverAnimation(""+n);else if(Action.drawCondition===0)go_direct(n);else if(MoveInfo.pairEnlarge===true||ScreenInfo.onesmc===true)go_directEnc(n);else if(Action.drawCondition===10&&n===(PageInfo.currentPage+1))go_nearEnc(4);else if(Action.drawCondition===11&&n===PageInfo.currentPage)go_nearEnc(3);else go_directEnc(n);}
function go_nudepage(s){if(s=="first")firstbtnClick();else if(s=="prev")prevbtnClick();else if(s=="next")nextbtnClick();else if(s=="last")lastbtnClick();else if(s=="slide")slidebtnClick();else if(s=="explorer")expbtnClick();else if(s=="print")printbtnClick();}
function go_nudedirect(s){var n=PermitMan.get_directGoPerm("showboard",s,"","");if(n<0)return false;go_general(n,"user");}
function onsmimage_leftClick(){if(PermitMan.normalPerm(-1)===false)return;if(SmcObj.prevPermission("onsmimageL")===false)return;if(PermitMan.access_memberZone(-2,"onsmimageL")===false)return;Action.aniLocking=true;go_prev();}
function onsmimage_rightClick(){if(PermitMan.normalPerm(-1)===false)return;if(SmcObj.nextPermission("nextbtn")===false)return;if(PermitMan.access_memberZone(-1,"nextbtn")===false)return;Action.aniLocking=true;if(Action.drawCondition===-1)do_coverAnimation("next");else go_next(true);}
NewinObj={titleHeight:0,svgWidth:0,svgHeight:0,dragGap:0,alertX:0,alertY:0,alertW:300,alertH:180,indexX:0,indexY:0,openAni:0,scrollbarWidth:0,xpdWidth:0,xpdHeight:0,xpdSize:'s'};NewinObj.get_url=function(w,h,appdix,nwclass,fname,aqstr){var qstr="w="+w+"&h="+h+"&d="+SkinInfo.mainmenu+"."+nwclass+"."+CataInfo.incview+"."+CataInfo.cataLang+aqstr;return"<div id='newin_frame"+appdix+"'></div><iframe class='newinobjE"+nwclass+"' src='./skin5/"+fname+"?"+qstr+"'></iframe>";}
NewinObj.do_mousedownTitle=function(e,obj){clickX=e.clientX;clickY=e.clientY;Action.mouseDragClip=obj;}
NewinObj.do_mouseDrag=function(e){e.preventDefault();var posX=e.clientX-clickX+befX;var posY=e.clientY-clickY+befY;if(posX<cataRect.x)posX=cataRect.x;else if(posX>cataRect.right-NewinObj.svgWidth-NewinObj.dragGap)posX=cataRect.right-NewinObj.svgWidth-NewinObj.dragGap;if(posY<cataRect.y)posY=cataRect.y;else if(posY>cataRect.bottom-NewinObj.svgHeight-NewinObj.dragGap)posY=cataRect.bottom-NewinObj.svgHeight-NewinObj.dragGap;newinDiv.style.left=posX+"px";newinDiv.style.top=posY+"px";return true;}
NewinObj.do_mouseUp=function(e){befX+=e.clientX-clickX;befY+=e.clientY-clickY;}
NewinObj.newin_close=function(){unload_newin('');}
NewinObj.onresize_func=function(){if(alertSvg)load_alert('',false);if(Action.mainState==="print")load_print(false);else if(Action.mainState==="index"){if(NewinObj.openAni===1)load_indexa(false);else load_indexm(false);}
else if(Action.mainState==="combo")load_combo(false);else if(Action.mainState==="mail")load_mail(false);else if(Action.mainState==="help")load_help(false);else if(Action.mainState==="explorer")load_explorer(false);else if(Action.mainState==="spacer")load_spacer('',false);else if(Action.mainState==="sns")load_sns(false);else if(Action.mainState==="note")load_note(false);else if(Action.mainState==="search")load_search(100,0);else if(Action.mainState==="expand")load_expand(false);else if(Action.mainState==="special")load_special(false);if(document.getElementById('fadesect').style.visibility=="visible")resize_fadeback();}
Newin2Obj={svgWidth:0,svgHeight:0,cobj:undefined,uidx:-1};Newin2Obj.do_mousedownTitle=function(e,obj,objstr){clickX=e.clientX;clickY=e.clientY;Action.mouseDragClip=Newin2Obj;Newin2Obj.cobj=document.getElementById(objstr);bef2X=parseInt(Newin2Obj.cobj.style.left.replace("px",""));bef2Y=parseInt(Newin2Obj.cobj.style.top.replace("px",""));Newin2Obj.svgWidth=Newin2Obj.cobj.clientWidth;Newin2Obj.svgHeight=Newin2Obj.cobj.clientHeight;}
Newin2Obj.do_mouseDrag=function(e){e.preventDefault();var posX=e.clientX-clickX+bef2X;var posY=e.clientY-clickY+bef2Y;if(posX<winRect.x)posX=winRect.x;else if(posX>winRect.right-Newin2Obj.svgWidth-NewinObj.dragGap)posX=winRect.right-Newin2Obj.svgWidth-NewinObj.dragGap;if(posY<winRect.y)posY=winRect.y;else if(posY>winRect.bottom-Newin2Obj.svgHeight-NewinObj.dragGap)posY=winRect.bottom-Newin2Obj.svgHeight-NewinObj.dragGap;Newin2Obj.cobj.style.left=posX+"px";Newin2Obj.cobj.style.top=posY+"px";return true;}
Newin2Obj.do_mouseUp=function(e){Newin2Obj.cobj=undefined;bef2X+=e.clientX-clickX;bef2Y+=e.clientY-clickY;}
Newin2Obj.do_touchEnd=function(){}
function load_license(){document.getElementById("licensesect").innerHTML="<iframe src='"+FileInfo.skin5FilePath("license.svg")+"'></iframe>";}
function load_alert(mgoo,bool){NewinObj.alertX=Math.floor((stageWidth-NewinObj.alertW)/2);NewinObj.alertY=Math.floor((stageHeight-NewinObj.alertH)/2);if(bool===true){DebugMan.strTitle=mgoo;Action.set_mainState("alert");alertDiv.innerHTML=NewinObj.get_url(NewinObj.alertW,NewinObj.alertH,"Alert",SkinInfo.nwclass,"alert001."+ServerInfo.progExt,"");alertDiv.style.visibility="visible";if(WinInfo.newinFade===true)show_fadeback();}
alertDiv.style.left=NewinObj.alertX+"px";alertDiv.style.top=NewinObj.alertY+"px";}
function unload_alert(){Action.restoreState();alertSvg=undefined;if(WinInfo.newinFade===true)hide_fadeback();alertDiv.style.left="-310px";alertDiv.style.top="-190px";alertDiv.innerHTML="";alertDiv.style.visibility="hidden";}
function load_index(){var tw=MenuInfo.indexWidth;if(tw<220)tw=220;else if(tw>stageWidth-20)tw=stageWidth-20;var th=MenuInfo.indexHeight;if(th<250)th=250;else if(th>stageHeight-20)th=stageHeight-20;if(MenuInfo.idxPos==="center"){NewinObj.indexX=Math.floor((stageWidth-tw)/2);NewinObj.indexY=Math.floor((stageHeight-th)/2);}
else if(MenuInfo.idxPos==="button"){var areaRect=document.getElementById('indexbtn').getBoundingClientRect();NewinObj.indexX=areaRect.left;NewinObj.indexY=areaRect.bottom+1;}
else{NewinObj.indexX=cataRect.x;NewinObj.indexY=cataRect.y;}
indexDiv.style.width=tw+"px";indexDiv.style.height=th+"px";indexDiv.style.left=NewinObj.indexX+"px";indexDiv.style.top=NewinObj.indexY+"px";indexDiv.innerHTML=NewinObj.get_url(tw,th,"Index",SkinInfo.nwclass,"index"+SkinInfo.indexmc+"."+ServerInfo.progExt,"");indexDiv.style.visibility="visible";}
function load_indexm(bool){var tw=300;var th=winRect.height-20;if(CataInfo.incview==="m"&&th>WinInfo.m_maxWinHeight)th=WinInfo.m_maxWinHeight;NewinObj.indexX=Math.floor((stageWidth-tw)/2);NewinObj.indexY=Math.floor((stageHeight-th)/2);if(NewinObj.indexY<0)NewinObj.indexY=10;if(bool===true){Action.set_mainState("index");indexDiv.innerHTML=NewinObj.get_url(tw,th,"Index",SkinInfo.nwclass,"index001."+ServerInfo.progExt,"");indexDiv.style.visibility="visible";if(WinInfo.newinFade===true)show_fadeback();}
indexDiv.style.width=tw+"px";indexDiv.style.height=th+"px";indexDiv.style.left=NewinObj.indexX+"px";indexDiv.style.top=NewinObj.indexY+"px";if(bool===false)indexSvg.refresh_size(tw,th);}
function unload_index(){if(CataInfo.incview==="m"){if(WinInfo.newinFade===true)hide_fadeback();Action.restoreState();}
indexSvg=undefined;NewinObj.openAni=0;indexDiv.style.left=(-20-indexDiv.clientWidth)+"px";indexDiv.style.top=(-20-indexDiv.clientHeight)+"px";indexDiv.innerHTML="";indexDiv.style.visibility="hidden";}
function load_indexa(bool){var tw=winRect.width;var th=Math.floor(winRect.height/2);if(th<300)th=300;NewinObj.indexX=Math.floor((stageWidth-tw)/2);NewinObj.indexY=winRect.bottom-th-5;if(bool===true){Action.set_mainState("index");indexDiv.innerHTML=NewinObj.get_url(tw,th,"Index",SkinInfo.nwclass,"index001."+ServerInfo.progExt,"");indexDiv.style.visibility="visible";}
indexDiv.style.width=tw+"px";indexDiv.style.height=th+"px";indexDiv.style.left=NewinObj.indexX+"px";if(bool===true){indexDiv.style.top=winRect.bottom+"px";if(WinInfo.newinFade===true)do_newinAnimate("show",winRect.bottom,-th-5,indexDiv,show_fadeback);else do_newinAnimate("show",winRect.bottom,-th-5,indexDiv,undefined);}
else{indexDiv.style.top=NewinObj.indexY+"px";indexSvg.refresh_size(tw,th);}}
function load_print(bool){var tw,th;if(CataInfo.incview==="m")tw=280,th=190;else{tw=280,th=300;if(SkinInfo.nw2class==="016"||SkinInfo.nw2class==="018"||SkinInfo.nw2class==="014")tw+=6,th+=15;}
befX=Math.floor((stageWidth-tw)/2);befY=Math.floor((stageHeight-th)/2);if(bool===true){Action.set_mainState("print");newinDiv.className="newinE"+SkinInfo.nwclass;newinDiv.innerHTML=NewinObj.get_url(tw,th,"",SkinInfo.nwclass,"print001."+ServerInfo.progExt,"");newinDiv.style.visibility="visible";newinDiv.style.width=tw+"px";newinDiv.style.height=th+"px";if(WinInfo.newinFade===true)show_fadeback();}
newinDiv.style.left=befX+"px";newinDiv.style.top=befY+"px";}
function load_partprint(){tempH=newinDiv.style.top;newinDiv.style.top=ScreenInfo.codeHeight+"px";newinDiv.style.visibility="hidden";if(WinInfo.newinFade===true)hide_fadeback();ushapeDiv.innerHTML="<iframe src='"+FileInfo.skin5FilePath("printpart.svg")+"'></iframe>";ushapeDiv.style.width=stageWidth+"px";ushapeDiv.style.height=stageHeight+"px";Action.keyDownFunc=do_partprintKeydown;}
function do_partprintKeydown(e){if(e.keyCode===27){PrintInfo.partPrint=false;unload_partprint(false);}
Action.keyDownFunc=undefined;}
function unload_partprint(bool){if(Action.mainState==="print"){newinDiv.style.top=tempH;newinDiv.style.visibility="visible";if(WinInfo.newinFade===true)show_fadeback();}
if(bool===false){unload_ushape();unload_newin("printpage");printSvg=undefined;return;}
if(Action.mainState==="print")printSvg.start_ani();if(Action.mainState==="capture")load_capture(true);else load_printpage();unload_ushape();}
function unload_ushape(){ushapeDiv.innerHTML="";ushapeDiv.style.width="1px";ushapeDiv.style.height="1px";ushapeDiv.style.visibility="hidden";}
function load_printpage(){var urlstr=FileInfo.skin5FilePath("printpage001.html");if(PrintInfo.newinPage===false){hideDiv.innerHTML="<iframe src='"+urlstr+"'></iframe>\n";hideDiv.style.top=ScreenInfo.codeHeight+"px";hideDiv.style.visibility="visible";}
else{if(CataInfo.cdmake===true)urlstr="../"+urlstr;if(PrintInfo.newinObj)PrintInfo.newinObj.location=urlstr;else PrintInfo.newinObj=window.open(urlstr);}}
function unload_printpage(){if(PrintInfo.newinPage===false){hideDiv.innerHTML="";hideDiv.style.visibility="hidden";}
else{if(PrintInfo.newinObj)PrintInfo.newinObj.close();PrintInfo.newinObj=undefined;}}
function load_capture(bool){var tw=PrintInfo.partWidth+2;var th=PrintInfo.partHeight+24;if(SkinInfo.nw2class==="016"||SkinInfo.nw2class==="018")tw+=14,th+=15;if(tw>cataRect.width-20)tw=cataRect.width-20;if(th>cataRect.height-20)th=cataRect.height-20;befX=Math.floor((stageWidth-tw)/2);befY=Math.floor((stageHeight-th)/2);if(bool===true){newinDiv.innerHTML=NewinObj.get_url(tw,th,"",SkinInfo.nwclass,"capture001."+ServerInfo.progExt,"");newinDiv.className="newinE"+SkinInfo.nwclass;newinDiv.style.visibility="visible";newinDiv.style.width=tw+"px";newinDiv.style.height=th+"px";}
newinDiv.style.left=befX+"px";newinDiv.style.top=befY+"px";}
function load_help(bool){var tw,th;if(CataInfo.incview==="m")tw=255,th=360;else{if(MenuInfo.helpWidth!==0)tw=MenuInfo.helpWidth,th=MenuInfo.helpHeight+WinInfo.get_titleHeight(SkinInfo.nw2class);else if(SkinInfo.helpmc==="002")tw=700,th=450;else tw=500,th=430;if(SkinInfo.nw2class==="016"||SkinInfo.nw2class==="018"||SkinInfo.nw2class==="014")tw+=14,th+=15;}
befX=Math.floor((stageWidth-tw)/2);befY=Math.floor((stageHeight-th)/2);if(befY<0)befY=10;if(bool===true){Action.set_mainState("help");newinDiv.className="newinE"+SkinInfo.nwclass;newinDiv.style.width=tw+"px";newinDiv.style.height=th+"px";newinDiv.innerHTML=NewinObj.get_url(tw,th,"",SkinInfo.nwclass,"help001."+ServerInfo.progExt,"."+SkinInfo.helpmc);newinDiv.style.visibility="visible";if(WinInfo.newinFade===true)show_fadeback();}
newinDiv.style.left=befX+"px";newinDiv.style.top=befY+"px";}
function load_helpm002(){var s="";var tw=93+40;var th=121+40;if(MoveInfo.spDrag===true){s+="<img src='./skin5/help/m2_draglr"+CataInfo.loLang+".png' class='helpimg5mE002'>";th+=161;}
s+=(ScreenInfo.pchZoom===true)?"<img src='./skin5/help/m2_pinchen"+CataInfo.loLang+".png' class='helpimg5mE002'>":"<img src='./skin5/help/m2_clicken"+CataInfo.loLang+".png' class='helpimg5mE002'>";befX=Math.floor((stageWidth-tw)/2);befY=Math.floor((stageHeight-th)/2);if(befY<0)befY=10;cursorDiv.className="help5mE002";cursorDiv.style.left=befX+"px";cursorDiv.style.top=befY+"px";cursorDiv.style.width=tw+"px";cursorDiv.style.height=th+"px";cursorDiv.innerHTML=s;cursorDiv.style.visibility="visible";}
function unload_helpm002(){cursorDiv.style.left="-1px";cursorDiv.style.top="-1px";cursorDiv.style.width="1px";cursorDiv.style.height="1px";cursorDiv.innerHTML="";cursorDiv.style.visibility="hidden";}
function load_mail(bool){var tw,th;if(CataInfo.incview==="m")tw=300,th=350;else{tw=390,th=330;if(SkinInfo.nw2class==="016"||SkinInfo.nw2class==="018"||SkinInfo.nw2class==="014")tw+=14,th+=11;}
befX=Math.floor((stageWidth-tw)/2);befY=Math.floor((stageHeight-th)/2);if(befY<0)befY=10;if(bool===true){Action.set_mainState("mail");newinDiv.className="newinE"+SkinInfo.nwclass;newinDiv.style.width=tw+"px";newinDiv.style.height=th+"px";newinDiv.innerHTML=NewinObj.get_url(tw,th,"",SkinInfo.nwclass,"mail001."+ServerInfo.progExt,"");newinDiv.style.visibility="visible";if(WinInfo.newinFade===true)show_fadeback();}
newinDiv.style.left=befX+"px";newinDiv.style.top=befY+"px";}
function load_search(searchCustom,openingSearch){var tw,th;if(CataInfo.incview==="m"){tw=stageWidth-20;th=stageHeight-20;}
else{if(MenuInfo.searchWidth===0)tw=500,th=530;else tw=MenuInfo.searchWidth,th=MenuInfo.searchHeight;if(SkinInfo.nw2class==="016"||SkinInfo.nw2class==="018"||SkinInfo.nw2class==="014")tw+=14,th+=15;}
befX=Math.floor((stageWidth-tw)/2);befY=Math.floor((stageHeight-th)/2);if(searchCustom!==100){Action.set_mainState("search");newinDiv.className="newinE"+SkinInfo.nwclass;newinDiv.innerHTML=NewinObj.get_url(tw,th,"",SkinInfo.nwclass,"search001."+ServerInfo.progExt,"."+searchCustom+"."+openingSearch);newinDiv.style.visibility="visible";if(WinInfo.newinFade===true)show_fadeback();}
else{searchSvg.refresh_size(tw,th);}
newinDiv.style.width=tw+"px";newinDiv.style.height=th+"px";newinDiv.style.left=befX+"px";newinDiv.style.top=befY+"px";}
function load_sns(bool){var tw,th;if(CataInfo.incview==="m"){if(NewinObj.openAni===1){tw=winRect.width;th=180;}
else{tw=stageWidth-20;th=stageHeight-20;}}
else{tw=370,th=180;if(SkinInfo.nw2class==="016"||SkinInfo.nw2class==="018")tw+=6,th+=15;}
befX=Math.floor((stageWidth-tw)/2);befY=(NewinObj.openAni===1)?winRect.bottom-th-5:Math.floor((stageHeight-th)/2);if(bool===true){Action.set_mainState("sns");newinDiv.className="newinE"+SkinInfo.nwsns;newinDiv.innerHTML=NewinObj.get_url(tw,th,"",SkinInfo.nwsns,"sns001."+ServerInfo.progExt,"");newinDiv.style.visibility="visible";if(WinInfo.newinFade===true)show_fadeback();}
else{snsSvg.refresh_size(tw,th);}
newinDiv.style.width=tw+"px";newinDiv.style.height=th+"px";newinDiv.style.left=befX+"px";if(bool===true&&NewinObj.openAni===1){newinDiv.style.top=winRect.bottom+"px";do_newinAnimate("show",winRect.bottom,-th-5,newinDiv,undefined);}
else{newinDiv.style.top=befY+"px";}}
function load_note(bool){var tw=stageWidth-20;var th=stageHeight-20;befX=Math.floor((stageWidth-tw)/2);befY=Math.floor((stageHeight-th)/2);if(bool===true){newinTmp={thumbWidth:0,thumbHeight:0,spacingII:10,colQty:1,winpadR:7,winpadL:7};newinTmp.thumbWidth=MenuInfo.m_thumbWidth;newinTmp.thumbHeight=Math.round(newinTmp.thumbWidth/ScreenInfo.ratioWH);newinTmp.colQty=ScreenInfo.get_thumbQtyFromWidth(tw,newinTmp.winpadL+newinTmp.winpadR,newinTmp.thumbWidth,newinTmp.spacingII);Action.set_mainState("note");newinDiv.className="newinE"+SkinInfo.nwclass;newinDiv.innerHTML=NewinObj.get_url(tw,th,"",SkinInfo.nwclass,"note001."+ServerInfo.progExt,"");newinDiv.style.visibility="visible";if(WinInfo.newinFade===true)show_fadeback();}
else{newinTmp.colQty=ScreenInfo.get_thumbQtyFromWidth(tw,newinTmp.winpadL+newinTmp.winpadR,newinTmp.thumbWidth,newinTmp.spacingII);noteSvg.refresh_size(tw,th);}
newinDiv.style.width=tw+"px";newinDiv.style.height=th+"px";newinDiv.style.left=befX+"px";newinDiv.style.top=befY+"px";}
function load_colorPicker(){var tw,th;if(CataInfo.incview==="m"){if(stageWidth<=320){tw=stageWidth;th=stageHeight;}
else{tw=stageWidth-20;th=stageHeight-20;}}
else{tw=400,th=300;if(SkinInfo.nw2class==="016"||SkinInfo.nw2class==="018")tw+=14,th+=15;}
befX=Math.floor((stageWidth-tw)/2);befY=Math.floor((stageHeight-th)/2);Action.set_mainState("colpick");newinDiv.className="newinE"+SkinInfo.nwclass;newinDiv.style.width=tw+"px";newinDiv.style.height=th+"px";newinDiv.style.left=befX+"px";newinDiv.style.top=befY+"px";newinDiv.innerHTML=NewinObj.get_url(tw,th,"",SkinInfo.nwclass,"colorpicker001."+ServerInfo.progExt,"");newinDiv.style.visibility="visible";}
function load_blackboard(bool,sevt){if(BBwInfo.loc==="win"){if(Action.drawCondition<0&&PageInfo.currentPage===0&&CataInfo.openingAnimation===true){bbwDiv.style.left=(winRect.x-ScreenInfo.smImageWidthHalf)+"px";}
bbwDiv.style.width=winRect.width+"px";bbwDiv.style.height=winRect.height+"px";}
else if(BBwInfo.loc==="smcsync"){bbwDiv.style.left=(Action.drawCondition<0&&PageInfo.currentPage===0&&CataInfo.openingAnimation===true)?(smRect.x-ScreenInfo.smImageWidthHalf)+"px":smRect.x+"px";bbwDiv.style.top=smRect.y+"px";bbwDiv.style.width=smRect.width+"px";bbwDiv.style.height=smRect.height+"px";}
if(bool===true)bbwDiv.innerHTML="<iframe src='"+FileInfo.skin5FilePath("blackboard.html")+"'></iframe>";else{if(bboardSvg){if(BBwInfo.loc==="win")bboardSvg.set_location(winRect.width,winRect.height);else if(BBwInfo.loc==="smcsync")bboardSvg.set_location(smRect.width,smRect.height);}}
if(sevt!==""){bbwDiv.style.pointerEvents=sevt;if(sevt==="auto")Action.set_mainState("blackboard");}}
function unload_blackboard(){bbwDiv.innerHTML="";bbwDiv.style.width="1px";bbwDiv.style.height="1px";bbwDiv.style.visibility="hidden";bboardSvg=undefined;if(Action.mainState==="blackboard")Action.restoreState();}
function load_combo(bool,cm,custom){var tw=300;var th=winRect.height-20;if(CataInfo.incview==="m"){if(NewinObj.openAni===1){tw=winRect.width;th=Math.floor(winRect.height/2);if(th<300)th=300;}
else{if(th>WinInfo.m_maxWinHeight)th=WinInfo.m_maxWinHeight;}}
befX=Math.floor((stageWidth-tw)/2);befY=Math.floor((stageHeight-th)/2);if(befY<0)befY=10;if(NewinObj.openAni===1)befY=winRect.bottom-th-5;if(bool===true){var qstr="w="+tw+"&h="+th+"&d="+SkinInfo.mainmenu+"."+SkinInfo.nwclass+"."+CataInfo.incview+"."+CataInfo.cataLang+"."+SkinInfo.combokind+"."+cm+"."+custom;var skinNum=(custom.length>2)?custom:"001";var s="<div id='newin_frame'></div>"
+"<iframe id='nwcomboobj' class='newinobjE"+SkinInfo.nwclass+"' src='./skin5/combo"+skinNum+"."+ServerInfo.progExt+"?"+qstr+"'></iframe>";Action.set_mainState("combo");newinDiv.className="newinE"+SkinInfo.nwclass;newinDiv.style.width=tw+"px";newinDiv.style.height=th+"px";newinDiv.innerHTML=s;newinDiv.style.visibility="visible";}
else{newinDiv.style.height=th+"px";combopopSvg.refresh_size(th);}
newinDiv.style.left=befX+"px";if(bool===true&&NewinObj.openAni===1){newinDiv.style.top=winRect.bottom+"px";do_newinAnimate("show",winRect.bottom,-th-5,newinDiv,undefined);}
else{newinDiv.style.top=befY+"px";}}
function load_explorer(bool){newinTmp={thumbWidth:0,thumbHeight:0,totalWidth:0,totalHeight:0,contWidth:0,contHeight:0,colQty:1,rowQty:1,spacingII:10,spacingIP:12,winpadT:8,winpadR:10,winpadB:10,winpadL:8,pgHeight:14,pgY:0,alignH:'center',alignV:'top'};if(SkinInfo.nw2class==="016")newinTmp.winpadB=15;else if(SkinInfo.nw2class==="018"){newinTmp.winpadR=12;newinTmp.winpadB=20;}
NewinObj.titleHeight=WinInfo.get_titleHeight(SkinInfo.nw2class);var pgh=newinTmp.pgHeight+newinTmp.spacingIP;var tw,th;if(CataInfo.incview==="m"){newinTmp.thumbWidth=MenuInfo.m_thumbWidth;newinTmp.thumbHeight=Math.round(newinTmp.thumbWidth/ScreenInfo.ratioWH);if(NewinObj.openAni===1){tw=winRect.width;}
else{tw=stageWidth-20;th=stageHeight-20;}
newinTmp.colQty=ScreenInfo.get_thumbQtyFromWidth(tw,newinTmp.winpadL+newinTmp.winpadR,newinTmp.thumbWidth,newinTmp.spacingII);newinTmp.contWidth=newinTmp.thumbWidth*newinTmp.colQty+newinTmp.spacingII*(newinTmp.colQty-1);if(newinTmp.alignH==="center")newinTmp.winpadL=Math.floor((tw-newinTmp.contWidth)/2);newinTmp.winpadR=tw-newinTmp.contWidth-newinTmp.winpadL;if(MenuInfo.currShowMenu==="explorer"){var reh=NewinObj.titleHeight+newinTmp.winpadT+newinTmp.winpadB+pgh;newinTmp.rowQty=ScreenInfo.get_thumbQtyFromHeight(th,reh,newinTmp.thumbHeight,newinTmp.spacingII);if(newinTmp.colQty*newinTmp.rowQty>=PageInfo.cataPages)pgh=0;}
else{newinTmp.rowQty=Math.floor((PageInfo.cataPages-1)/newinTmp.colQty)+1;pgh=0;}
if(NewinObj.openAni===1){th=NewinObj.titleHeight+newinTmp.thumbHeight+newinTmp.winpadT+newinTmp.winpadB;newinTmp.rowQty=1;pgh=0;}
else{newinTmp.contHeight=newinTmp.thumbHeight*newinTmp.rowQty+newinTmp.spacingII*(newinTmp.rowQty-1)+pgh;}
if(pgh!==0)newinTmp.pgY=th-NewinObj.titleHeight-newinTmp.winpadB-newinTmp.pgHeight;}
else{newinTmp.thumbHeight=MenuInfo.thumbHeight;newinTmp.thumbWidth=Math.round(newinTmp.thumbHeight*ScreenInfo.ratioWH);newinTmp.colQty=ScreenInfo.get_thumbQtyFromWidth(0,newinTmp.winpadL+newinTmp.winpadR,newinTmp.thumbWidth,newinTmp.spacingII);if(newinTmp.colQty>10)newinTmp.colQty=10;newinTmp.contWidth=newinTmp.thumbWidth*newinTmp.colQty+newinTmp.spacingII*(newinTmp.colQty-1);tw=newinTmp.winpadL+newinTmp.contWidth+newinTmp.winpadR;if(MenuInfo.currShowMenu==="explorer"){newinTmp.rowQty=1;if(newinTmp.colQty>=PageInfo.cataPages)pgh=0;}
else{newinTmp.rowQty=Math.floor((PageInfo.cataPages-1)/newinTmp.colQty)+1;pgh=0;}
newinTmp.contHeight=newinTmp.thumbHeight*newinTmp.rowQty+newinTmp.spacingII*(newinTmp.rowQty-1)+pgh;if(pgh!==0)newinTmp.pgY=newinTmp.winpadT+newinTmp.contHeight-newinTmp.pgHeight;th=NewinObj.titleHeight+newinTmp.winpadT+newinTmp.contHeight+newinTmp.winpadB;if(th>cataRect.height-20){th=cataRect.height-20;tw+=15;}
newinTmp.totalHeight=th;newinTmp.totalWidth=tw;}
befX=Math.floor((stageWidth-tw)/2);befY=(NewinObj.openAni===1)?winRect.bottom-th-5:Math.floor((stageHeight-th)/2);if(bool===true){Action.set_mainState("explorer");newinDiv.className="newinE"+SkinInfo.nwclass;newinDiv.style.width=tw+"px";newinDiv.style.height=th+"px";newinDiv.innerHTML=NewinObj.get_url(tw,th,"",SkinInfo.nwclass,"explorer001."+ServerInfo.progExt,"."+MenuInfo.applyMax);newinDiv.style.visibility="visible";if(WinInfo.newinFade===true)show_fadeback();}
else{newinDiv.style.width=tw+"px";newinDiv.style.height=th+"px";expSvg.refresh_size(tw,th);}
newinDiv.style.left=befX+"px";if(bool===true&&NewinObj.openAni===1){newinDiv.style.top=winRect.bottom+"px";do_newinAnimate("show",winRect.bottom,-th-5,newinDiv,undefined);}
else{newinDiv.style.top=befY+"px";}
Action.aniLocking=false;}
function calc_totalwindow(){newinTmp.rowQty=Math.floor((PageInfo.cataPages-1)/newinTmp.colQty)+1;newinTmp.contHeight=newinTmp.thumbHeight*newinTmp.rowQty+newinTmp.spacingII*(newinTmp.rowQty-1);var th=NewinObj.titleHeight+newinTmp.winpadT+newinTmp.contHeight+newinTmp.winpadB;if(th>cataRect.height-20)th=cataRect.height-20;newinTmp.totalHeight=th;befY=Math.floor((stageHeight-th)/2);newinDiv.style.height=th+"px";newinDiv.style.left=befX+"px";newinDiv.style.top=befY+"px";}
function calc_expwindow(){var pgh=newinTmp.pgHeight+newinTmp.spacingIP;newinTmp.rowQty=1;if(newinTmp.colQty>=PageInfo.cataPages)pgh=0;newinTmp.contHeight=newinTmp.thumbHeight*newinTmp.rowQty+newinTmp.spacingII*(newinTmp.rowQty-1)+pgh;if(pgh!==0)newinTmp.pgY=newinTmp.winpadT+newinTmp.contHeight-newinTmp.pgHeight;var th=NewinObj.titleHeight+newinTmp.winpadT+newinTmp.contHeight+newinTmp.winpadB;newinTmp.totalHeight=th;befY=Math.floor((stageHeight-th)/2);newinDiv.style.height=th+"px";newinDiv.style.left=befX+"px";newinDiv.style.top=befY+"px";}
function load_spacer(kd,bool){if(SkinInfo.spacerbtn==="000")return;newinTmp={thumbWidth:0,thumbHeight:0,totalWidth:0,totalHeight:0,contWidth:0,contHeight:0,colQty:1,rowQty:1,spacingII:10,spacingIP:12,winpadT:8,winpadR:11,winpadB:11,winpadL:8,pgHeight:14,pgY:0,alignH:'center',alignV:'top'};if(SkinInfo.nw2class==="016"||SkinInfo.nw2class==="018")newinTmp.winpadB=15;NewinObj.titleHeight=WinInfo.get_titleHeight(SkinInfo.nw2class);var tw,th;if(CataInfo.incview==="m"){tw=stageWidth-20;th=stageHeight-20;newinTmp.thumbWidth=MenuInfo.m_thumbWidth;newinTmp.thumbHeight=Math.round(newinTmp.thumbWidth/ScreenInfo.ratioWH);newinTmp.colQty=ScreenInfo.get_thumbQtyFromWidth(tw,newinTmp.winpadL+newinTmp.winpadR,newinTmp.thumbWidth,newinTmp.spacingII);newinTmp.contWidth=newinTmp.thumbWidth*newinTmp.colQty+newinTmp.spacingII*(newinTmp.colQty-1);if(newinTmp.alignH==="center")newinTmp.winpadL=Math.floor((tw-newinTmp.contWidth)/2);newinTmp.winpadR=tw-newinTmp.contWidth-newinTmp.winpadL;newinTmp.rowQty=Math.floor((SpacerInfo.maxItems-1)/newinTmp.colQty)+1;newinTmp.contHeight=newinTmp.thumbHeight*newinTmp.rowQty+newinTmp.spacingII*(newinTmp.rowQty-1);}
else{newinTmp.thumbHeight=MenuInfo.thumbHeight;newinTmp.thumbWidth=Math.round(newinTmp.thumbHeight*ScreenInfo.ratioWH);newinTmp.colQty=SpacerInfo.maxItems;newinTmp.contWidth=newinTmp.thumbWidth*newinTmp.colQty+newinTmp.spacingII*(newinTmp.colQty-1);tw=newinTmp.winpadL+newinTmp.contWidth+newinTmp.winpadR;newinTmp.totalWidth=tw;newinTmp.rowQty=1;newinTmp.contHeight=newinTmp.thumbHeight*newinTmp.rowQty+newinTmp.spacingII*(newinTmp.rowQty-1);th=NewinObj.titleHeight+newinTmp.winpadT+newinTmp.contHeight+newinTmp.winpadB;newinTmp.totalHeight=th;}
befX=Math.floor((stageWidth-tw)/2);befY=Math.floor((stageHeight-th)/2);if(bool===true){Action.set_mainState("spacer");newinDiv.className="newinE"+SkinInfo.nwclass;newinDiv.style.width=tw+"px";newinDiv.style.height=th+"px";newinDiv.innerHTML=NewinObj.get_url(tw,th,"",SkinInfo.nwclass,"spacer001."+ServerInfo.progExt,"."+kd);newinDiv.style.visibility="visible";if(WinInfo.newinFade===true)show_fadeback();}
else{newinDiv.style.width=tw+"px";newinDiv.style.height=th+"px";spacerSvg.refresh_size(tw,th);}
newinDiv.style.left=befX+"px";newinDiv.style.top=befY+"px";Action.aniLocking=false;}
function unload_newin(skd){NewinObj.openAni=0;newinDiv.style.left="-1px";newinDiv.style.top="-1px";newinDiv.style.width="1px";newinDiv.style.height="1px";newinDiv.innerHTML="";newinDiv.style.visibility="hidden";if(WinInfo.newinFade===true)hide_fadeback();Action.restoreState();}
function load_glasses(){glassesDiv.innerHTML="<iframe width='"+stageWidth+"' height='"+stageHeight+"' src='"+FileInfo.skin5FilePath("glasses001.svg")+"'></iframe>";}
function unload_glasses(){glassesSvg=undefined;glassesDiv.innerHTML="";glassesDiv.style.visibility="hidden";}
function load_expand(bool){if(bool===true){Action.set_mainState("expand");if(Action.drawCondition>9){encDiv.style.visibility="hidden";guideDiv.style.visibility="hidden";}
else{smcDiv.style.visibility="hidden";if(CoverObj.bookdecoX!==NOMOVE)bookdecoDiv.style.visibility="hidden";if(Action.drawCondition>=0){if(splbtnDiv&&ScreenInfo.onesmc===false)splbtnDiv.style.visibility="hidden";if(sprbtnDiv)sprbtnDiv.style.visibility="hidden";if(smctrDiv)smctrDiv.style.visibility="hidden";}}
if(pageiconDiv)pageiconDiv.style.visibility="hidden";if(NewinObj.xpdWidth===0){set_expandDim();}
var csstext="display:block;width:"+NewinObj.xpdWidth+"px;height:"+NewinObj.xpdHeight+"px;margin:2px auto 0 auto;";var s="";var page_str=get_sentence(CataInfo.cataLang,"page","");for(var i=1;i<=PageInfo.cataPages;i++){var aaa=(NewinObj.xpdSize==="s")?SmcObj.get_imageUrl(i):FileInfo.cimgFilePath(i,"","","*");;if(PermitMan.check_memberZone("expand")===true&&PageInfo.is_previewPage(i)===false){s+="<div id='xpdiv"+i+"' style=\""+csstext+"\" data-load='0' data-apprvd='0'>"
+"<img src='"+aaa[0]+"' style=\"display:block;filter:brightness(0.1);\" alt='"+i+page_str+"'></div>\n";}
else{s+="<div id='xpdiv"+i+"' style=\""+csstext+"\" data-load='0' data-apprvd='1'>"
+"<img src='"+aaa[0]+"' style=\"display:block;\" alt='"+i+page_str+"'></div>\n";}}
expandDiv.style.width="100%";expandDiv.innerHTML=s;expandDiv.style.visibility="visible";}
expandDiv.style.top=cataRect.y+"px";expandDiv.style.height=cataRect.height+"px";}
function set_expandDim(){if(NewinObj.xpdSize==="s"){NewinObj.xpdWidth=ScreenInfo.smImageWidth;NewinObj.xpdHeight=ScreenInfo.smImageHeight;}
else if(NewinObj.xpdSize==="b"){NewinObj.xpdWidth=ScreenInfo.bigImageWidth;NewinObj.xpdHeight=ScreenInfo.bigImageHeight;}
else if(NewinObj.xpdSize==="w"){NewinObj.xpdWidth=cataRect.width-MenuObj.get_scrollbarWidth();NewinObj.xpdHeight=Math.floor(cataRect.width/ScreenInfo.ratioWH);}
else if(NewinObj.xpdSize==="h"){NewinObj.xpdHeight=cataRect.height;NewinObj.xpdWidth=Math.floor(cataRect.height*ScreenInfo.ratioWH);}}
function unload_expand(){Action.restoreState();if(Action.drawCondition>9){encDiv.style.visibility="visible";guideDiv.style.visibility="visible";}
else{smcDiv.style.visibility="visible";if(CoverObj.bookdecoX!==NOMOVE)bookdecoDiv.style.visibility="visible";if(Action.drawCondition>=0){if(splbtnDiv&&ScreenInfo.onesmc===false)splbtnDiv.style.visibility="visible";if(sprbtnDiv)sprbtnDiv.style.visibility="visible";if(smctrDiv)smctrDiv.style.visibility="visible";}}
if(pageiconDiv)pageiconDiv.style.visibility="visible";var nodes=expandDiv.childNodes;for(var i=nodes.length-1;i>=0;i--){expandDiv.removeChild(nodes[i]);}
expandDiv.innerHTML="";expandDiv.style.width="1px";expandDiv.style.height="1px";expandDiv.style.visibility="hidden";}
function do_horimokchaData(restr){var lines=restr.split("\n");var alen=lines.length;var pos,tstr,spage,adds;var sumstr="";var k=0;for(var i=0;i<alen;i++){tstr=lines[i].trim();if(tstr==undefined||tstr==="")continue;if(tstr==="nextline"){arIndexText[k]=sumstr;k++;sumstr="";}
else{pos=tstr.indexOf(":");if(pos===-1)continue;if(tstr.substr(0,3)==="---")spage=tstr.substr(3,pos);else if(tstr.substr(0,2)==="--")spage=tstr.substr(2,pos);else if(tstr.substr(0,1)==="-")spage=tstr.substr(1,pos);else spage=tstr.substr(0,pos);adds=(sumstr==="")?"":" | ";sumstr+=adds+" <a href=\"javascript:mokchaItemClick('"+spage+"');\">"+tstr.substr(pos+1)+"</a>";}}
if(sumstr!="")arIndexText[k]=sumstr;document.getElementById("horidx_txt").innerHTML=arIndexText[0];idxSeq=0;}
function do_mhorimokchaData(restr){if(!document.getElementById("horidx_div"))return;var lines=restr.split("\n");var alen=lines.length;var pos,tstr,spage;var sumstr="";for(var i=0;i<alen;i++){tstr=lines[i].trim();if(tstr==undefined||tstr===""||tstr==="nextline")continue;pos=tstr.indexOf(":");if(pos===-1)continue;if(tstr.substr(0,3)==="---")spage=tstr.substr(3,pos);else if(tstr.substr(0,2)==="--")spage=tstr.substr(2,pos);else if(tstr.substr(0,1)==="-")spage=tstr.substr(1,pos);else spage=tstr.substr(0,pos);sumstr+="<li data-page='"+spage+"' class='horidx_a_next'><a href=\"javascript:void(0);\" onclick=\"mmokchaItemClick('"+spage+"',event);\">"+tstr.substr(pos+1)+"</a></li>";}
document.getElementById("horidx_div").innerHTML="<ul>"+sumstr+"</ul>";}
function mokchaItemClick(pno){var n=PermitMan.get_directGoPerm("index",pno,"","");if(n<0)return;go_general(n,"user");}
function mmokchaItemClick(pno,e){var n=PermitMan.get_directGoPerm("index",pno,"","");if(n<0)return;go_general(n,"user");if(MenuInfo.indexType==="H"&&e.currentTarget.parentNode.parentNode.parentNode.id=="indexsect")MenuObj.horidxmoreClick();}
function go_indexUpper(){idxSeq--;if(idxSeq<0)idxSeq=0;document.getElementById("horidx_txt").innerHTML=arIndexText[idxSeq];}
function go_indexLower(){idxSeq++;if(idxSeq>arIndexText.length-1)idxSeq=arIndexText.length-1;document.getElementById("horidx_txt").innerHTML=arIndexText[idxSeq];}
function show_currIndex(pageno){if(pageno==undefined||pageno===-1){pageno=(PageInfo.showStartPage===0)?PageInfo.currentPage:PageInfo.get_showPageFromReal(PageInfo.currentPage);}
if(document.getElementById("horidx")){var arliobj=document.getElementById("horidx_div").getElementsByTagName("LI");var alen=arliobj.length;var nprev=0,n=0,spage,obj
var objprev=undefined;for(var i=0;i<alen;i++){obj=arliobj[i];obj.className="horidx_a_next";if(!obj.hasAttribute("data-page"))continue;spage=obj.getAttribute("data-page");if(spage=="")continue;n=parseInt(spage);if(i===alen-1&&pageno>=n){set_currIndex(obj);}
else if(nprev<=pageno&&pageno<n){if(objprev)set_currIndex(objprev);}
nprev=n;objprev=obj;}
if(indexDiv.style.visibility=="hidden")return;objprev=undefined;arliobj=indexDiv.getElementsByTagName("LI");alen=arliobj.length;nprev=0,n=0;for(i=0;i<alen;i++){obj=arliobj[i];obj.className="horidx_a_next";if(!obj.hasAttribute("data-page"))continue;spage=obj.getAttribute("data-page");if(spage=="")continue;n=parseInt(spage);if(i===alen-1&&pageno>=n){obj.className="horidx_a_curr";}
else if(nprev<=pageno&&pageno<n){if(objprev)objprev.className="horidx_a_curr";}
nprev=n;objprev=obj;}}}
function set_currIndex(obj){obj.className="horidx_a_curr";var areaRect=obj.getBoundingClientRect();var nwidth=document.getElementById("horidx_div").clientWidth;var nleft=document.getElementById("horidx_div").scrollLeft;if(areaRect.left<0||areaRect.right>nwidth){document.getElementById("horidx_div").scrollLeft=(nleft+areaRect.left)-cataRect.centerPt.x+obj.clientWidth/2;}
}
function do_afterMediaDataLoaded(){MediaObj.sndSeq=0;mediaPlayer.setAttribute("src",FileInfo.mediaFilePath(MediaObj.arMediaFile[MediaObj.sndSeq]));if(CataInfo.incview==="m")return;if(SoundInfo.openingMusicPlay==="Y"){MediaObj.currMode="play";mediaPlayer.play();mediaPlayer.addEventListener('ended',MediaObj.soundEnded);MediaObj.timer=setInterval(MediaObj.waveAnime,100);}}
function set_mediaObj(){MediaObj={arMediaTitle:[],arMediaFile:[],aniObj:[],aniSeq:0,sndSeq:0,currMode:'stop',timer:undefined};MediaObj.aniObj[0]=document.getElementById("mediarect1");MediaObj.aniObj[1]=document.getElementById("mediarect2");MediaObj.aniObj[2]=document.getElementById("mediarect3");MediaObj.aniObj[3]=document.getElementById("mediarect4");MediaObj.aniObj[4]=document.getElementById("mediarect5");MediaObj.aniObj[5]=document.getElementById("mediarect6");MediaObj.aniObj[6]=document.getElementById("mediarect7");MediaObj.aniObj[7]=document.getElementById("mediarect8");MediaObj.aniObj[8]=document.getElementById("mediarect9");MediaObj.aniObj[9]=document.getElementById("mediarect10");MediaObj.aniObj[10]=document.getElementById("mediarect11");MediaObj.aniObj[11]=document.getElementById("mediarect12");MediaObj.aniObj[12]=document.getElementById("mediarect13");MediaObj.aniObj[13]=document.getElementById("mediarect14");MediaObj.aniObj[14]=document.getElementById("mediarect15");ConnectMan.load_mediaData();MediaObj.waveAnime=function(){if(MediaObj.aniSeq%5===1){MediaObj.aniObj[1].setAttribute("visibility","hidden");MediaObj.aniObj[2].setAttribute("visibility","hidden");MediaObj.aniObj[5].setAttribute("visibility","hidden");}
else if(MediaObj.aniSeq%5===2){MediaObj.aniObj[0].setAttribute("visibility","hidden");MediaObj.aniObj[3].setAttribute("visibility","hidden");MediaObj.aniObj[4].setAttribute("visibility","hidden");MediaObj.aniObj[8].setAttribute("visibility","hidden");MediaObj.aniObj[11].setAttribute("visibility","hidden");}
else if(MediaObj.aniSeq%5===3){MediaObj.aniObj[5].setAttribute("visibility","visible");MediaObj.aniObj[7].setAttribute("visibility","hidden");MediaObj.aniObj[8].setAttribute("visibility","visible");MediaObj.aniObj[10].setAttribute("visibility","hidden");MediaObj.aniObj[11].setAttribute("visibility","visible");}
else if(MediaObj.aniSeq%5===4){MediaObj.aniObj[4].setAttribute("visibility","visible");MediaObj.aniObj[5].setAttribute("visibility","hidden");MediaObj.aniObj[6].setAttribute("visibility","hidden");MediaObj.aniObj[7].setAttribute("visibility","visible");MediaObj.aniObj[10].setAttribute("visibility","visible");}
else if(MediaObj.aniSeq%5===0){MediaObj.aniObj[1].setAttribute("visibility","visible");MediaObj.aniObj[2].setAttribute("visibility","visible");MediaObj.aniObj[3].setAttribute("visibility","visible");MediaObj.aniObj[5].setAttribute("visibility","visible");MediaObj.aniObj[6].setAttribute("visibility","visible");}
MediaObj.aniSeq++;}
MediaObj.playFromList=function(n){mediaPlayer.removeEventListener('ended',MediaObj.soundEnded);MediaObj.sndSeq=n;if(MediaObj.sndSeq>=MediaObj.arMediaFile.length)MediaObj.sndSeq=0;MediaObj.playSound();}
MediaObj.backbtnClick=function(){mediaPlayer.removeEventListener('ended',MediaObj.soundEnded);MediaObj.sndSeq--;if(MediaObj.sndSeq<0)MediaObj.sndSeq=MediaObj.arMediaFile.length-1;MediaObj.playSound();}
MediaObj.playbtnClick=function(){if(MediaObj.currMode==="play")return;mediaPlayer.play();if(MediaObj.currMode==="stop")mediaPlayer.addEventListener('ended',MediaObj.soundEnded);MediaObj.timer=setInterval(MediaObj.waveAnime,100);}
MediaObj.nextbtnClick=function(){mediaPlayer.removeEventListener('ended',MediaObj.soundEnded);MediaObj.sndSeq++;if(MediaObj.sndSeq>=MediaObj.arMediaFile.length)MediaObj.sndSeq=0;MediaObj.playSound();}
MediaObj.stopbtnClick=function(){MediaObj.currMode="pause";clearInterval(MediaObj.timer);MediaObj.timer=undefined;mediaPlayer.pause();}
MediaObj.listbtnClick=function(){if(PermitMan.normalPerm(-1)===false)return;if(CataInfo.incview==="m"){load_combo(true,'m','0');}
else{mediaClick();}}
MediaObj.soundEnded=function(){mediaPlayer.removeEventListener('ended',MediaObj.soundEnded);MediaObj.sndSeq++;if(MediaObj.sndSeq>=MediaObj.arMediaFile.length)MediaObj.sndSeq=0;MediaObj.playSound();}
MediaObj.setSeqfromFile=function(fname){MediaObj.sndSeq=MediaObj.arMediaFile.indexOf(fname);}
MediaObj.playSound=function(){MediaObj.currMode="play";mediaPlayer.setAttribute("src",FileInfo.mediaFilePath(MediaObj.arMediaFile[MediaObj.sndSeq]));mediaPlayer.load();mediaPlayer.play();mediaPlayer.addEventListener('ended',MediaObj.soundEnded);if(!MediaObj.timer)MediaObj.timer=setInterval(MediaObj.waveAnime,100);}}
function comboClick(s){if(SkinInfo.combokind==="000")return;if(combopopSvg)return;ComboObj.scaller=(s==undefined)?"click":s;if(combopopSvg==undefined){if(DataMan.cataboxData===4){if(SkinInfo.combokind==="001")ComboObj.set_comboData();else ComboObj.set_expComboData();DataMan.cataboxData=5;}
ComboObj.callobj=comboDiv;if(SkinInfo.combokind==="001"){var comboWidth=comboDiv.hasAttribute("data-width")?comboDiv.getAttribute("data-width"):"display";var w=0;if(comboWidth==="display")w=comboDiv.clientWidth-1;else if(comboWidth==="content")w=150;else w=parseInt(comboWidth);var h=comboDiv.hasAttribute("data-height")?parseInt(comboDiv.getAttribute("data-height")):150;load_combopop(w,h,"catakind");}
else{load_combopop(180,200,"catakind");}}
}
function mediaClick(s){if(combopopSvg)return;ComboObj.scaller=(s==undefined)?"click":s;if(combopopSvg==undefined){ComboObj.callobj=mediaDiv;var comboWidth=mediaDiv.getAttribute("data-width");var w=0;if(comboWidth==="display")w=mediaDiv.clientWidth;else if(comboWidth==="content")w=150;else w=parseInt(comboWidth);load_combopop(w,150,"media");}
}
function load_combopop(tw,th,kd){ComboObj.skd=kd;ComboObj.direction=ComboObj.callobj.getAttribute("data-direction");var comboCustom=ComboObj.callobj.hasAttribute("data-custom")?ComboObj.callobj.getAttribute("data-custom"):"0";var fname=(kd==="catakind"&&SkinInfo.combokind==="002")?"combopopexp001."+ServerInfo.progExt:"combopop001."+ServerInfo.progExt;var qstr="w="+(tw-2)+"&h="+(th-2)+"&d="+SkinInfo.mainmenu+"."+SkinInfo.nwclass+"."+CataInfo.incview+"."+CataInfo.cataLang+"."+SkinInfo.cbpopskin+"."+comboCustom;combopopDiv.innerHTML="<iframe id='combopopobj' width='"+(tw-2)+"' height='"+(th-2)+"' src='./skin5/"+fname+"?"+qstr+"'></iframe>";combopopObj=document.getElementById('combopopobj');}
function unload_combopop(){Action.keyDownFunc=undefined;if(ComboObj.scaller==="over")combopopDiv.removeEventListener("mouseout",ComboObj.do_mouseOut);if(ComboObj.direction==="top"){var topPos=parseInt(combopopDiv.style.top.replace("px",""));ComboObj.baseY=topPos;combopopDiv.style.overflowY="hidden";ComboObj.aniSeq=0;ComboObj.timer=setInterval(ComboObj.take_animateTop,20);}
else if(ComboObj.direction==="bottom"){var topPos=parseInt(combopopDiv.style.top.replace("px",""));ComboObj.baseY=topPos;combopopDiv.style.overflowY="hidden";ComboObj.aniSeq=0;ComboObj.timer=setInterval(ComboObj.take_animateBottom,20);}
else if(ComboObj.direction==="right"){var leftPos=parseInt(combopopDiv.style.left.replace("px",""));ComboObj.baseX=leftPos;combopopDiv.style.overflowY="hidden";ComboObj.aniSeq=0;ComboObj.timer=setInterval(ComboObj.take_animateRight,20);}}
ComboObj={direction:'',scaller:'',callobj:undefined,aniSeq:0,timer:undefined,skd:'',baseX:0,baseY:0,baseW:0,baseH:0,clipW:0,clipH:0};ComboObj.after_combopopLoad=function(kd,tw,th){var comboAlign=ComboObj.callobj.getAttribute("data-align");var areaRect=ComboObj.callobj.getBoundingClientRect();var leftPos;if(ComboObj.direction==="top"||ComboObj.direction==="bottom"){if(comboAlign==="right")leftPos=areaRect.right-tw-3;else if(comboAlign==="center")leftPos=areaRect.left-(tw-areaRect.width)/2;else leftPos=areaRect.left;}
else if(ComboObj.direction==="right"){leftPos=areaRect.left;}
if(ComboObj.callobj.hasAttribute("data-hpos"))leftPos+=parseInt(ComboObj.callobj.getAttribute("data-hpos"));var topPos=(ComboObj.direction==="bottom")?areaRect.bottom:areaRect.top;if(ComboObj.callobj.hasAttribute("data-vpos"))topPos+=parseInt(ComboObj.callobj.getAttribute("data-vpos"));ComboObj.baseX=leftPos;ComboObj.baseY=topPos;ComboObj.baseW=tw;ComboObj.baseH=th;ComboObj.clipW=tw;ComboObj.clipH=th;if(ComboObj.callobj.hasAttribute("data-hclip"))ComboObj.clipW+=parseInt(ComboObj.callobj.getAttribute("data-hclip"));if(ComboObj.callobj.hasAttribute("data-vclip"))ComboObj.clipH+=parseInt(ComboObj.callobj.getAttribute("data-vclip"));if(ComboObj.direction==="top"){combopopObj.width=tw;combopopDiv.style.width=tw+"px";combopopDiv.style.height="0px";combopopDiv.style.left=leftPos+"px";combopopDiv.style.top=(topPos-1)+"px";combopopDiv.style.visibility="visible";ComboObj.aniSeq=0;ComboObj.timer=setInterval(ComboObj.expand_animateTop,20);}
else if(ComboObj.direction==="bottom"){combopopObj.width=tw;combopopDiv.style.width=tw+"px";combopopDiv.style.height=th+"px";combopopDiv.style.left=leftPos+"px";combopopDiv.style.top=(topPos-th)+"px";combopopDiv.style.clip="rect("+ComboObj.baseH+"px "+ComboObj.clipW+"px "+ComboObj.clipH+"px 0px)";combopopDiv.style.visibility="visible";ComboObj.aniSeq=0;ComboObj.timer=setInterval(ComboObj.expand_animateBottom,20);}
else if(ComboObj.direction==="right"){combopopDiv.style.width="1px";combopopDiv.style.height=th+"px";combopopDiv.style.left=leftPos+"px";combopopDiv.style.top=topPos+"px";combopopDiv.style.visibility="visible";combopopObj.width=tw+"px";combopopObj.style.left=-tw+"px";ComboObj.aniSeq=0;ComboObj.timer=setInterval(ComboObj.expand_animateRight,20);}}
ComboObj.expand_animateTop=function(){var posY=ComboObj.baseH*AniObj.normalPercent[ComboObj.aniSeq];combopopDiv.style.top=(ComboObj.baseY-posY-1)+"px";combopopDiv.style.height=posY+"px";ComboObj.aniSeq++;if(ComboObj.aniSeq===AniObj.normalPercent.length){clearInterval(ComboObj.timer);ComboObj.timer=undefined;combopopObj.height=posY;combopopDiv.style.clip="auto";combopopDiv.style.overflowY="auto";ComboObj.set_takeEvent();}}
ComboObj.take_animateTop=function(){var posY=ComboObj.baseH*AniObj.normalPercent[ComboObj.aniSeq];combopopDiv.style.top=(ComboObj.baseY+posY-1)+"px";combopopDiv.style.height=(ComboObj.baseH-posY+1)+"px";ComboObj.aniSeq++;if(ComboObj.aniSeq===AniObj.normalPercent.length){clearInterval(ComboObj.timer);ComboObj.timer=undefined;ComboObj.after_takeAni("top");}}
ComboObj.expand_animateBottom=function(){var ty=ComboObj.baseH*AniObj.normalPercent[ComboObj.aniSeq];var posY=ComboObj.baseY-ComboObj.baseH+ty;combopopDiv.style.top=posY+"px";combopopDiv.style.clip="rect("+(ComboObj.baseY-posY)+"px "+ComboObj.clipW+"px "+ComboObj.clipH+"px 0px)";ComboObj.aniSeq++;if(ComboObj.aniSeq===AniObj.normalPercent.length){clearInterval(ComboObj.timer);ComboObj.timer=undefined;combopopDiv.style.clip="auto";combopopDiv.style.overflowY="auto";ComboObj.set_takeEvent();}}
ComboObj.take_animateBottom=function(){var ty=ComboObj.baseH*AniObj.normalPercent[ComboObj.aniSeq];var posY=ComboObj.baseY-ty;combopopDiv.style.top=posY+"px";combopopDiv.style.clip="rect("+(ComboObj.baseY-posY)+"px "+ComboObj.clipW+"px "+ComboObj.clipH+"px 0px)";ComboObj.aniSeq++;if(ComboObj.aniSeq===AniObj.normalPercent.length){clearInterval(ComboObj.timer);ComboObj.timer=undefined;ComboObj.after_takeAni("bottom");}}
ComboObj.expand_animateRight=function(){var posX=ComboObj.baseW*(1-AniObj.normalPercent[ComboObj.aniSeq]);combopopObj.style.left=-posX+"px";combopopDiv.style.width=(ComboObj.baseW-posX)+"px";ComboObj.aniSeq++;if(ComboObj.aniSeq===AniObj.normalPercent.length){clearInterval(ComboObj.timer);ComboObj.timer=undefined;combopopDiv.style.clip="auto";combopopDiv.style.overflowY="auto";ComboObj.set_takeEvent();}}
ComboObj.take_animateRight=function(){var posX=ComboObj.baseW*AniObj.normalPercent[ComboObj.aniSeq];combopopObj.style.left=-posX+"px";combopopDiv.style.width=(ComboObj.baseW-posX)+"px";ComboObj.aniSeq++;if(ComboObj.aniSeq===AniObj.normalPercent.length){clearInterval(ComboObj.timer);ComboObj.timer=undefined;ComboObj.after_takeAni("right");}}
ComboObj.set_takeEvent=function(){Action.keyDownFunc=ComboObj.do_keydown;if(ComboObj.scaller==="over"){combopopDiv.addEventListener("mouseout",ComboObj.do_mouseOut,true);}}
ComboObj.after_takeAni=function(s){combopopSvg.finish_mousedown();combopopDiv.innerHTML="";combopopDiv.style.visibility="hidden";combopopSvg=undefined;combopopObj=undefined;}
ComboObj.do_mouseOut=function(e){if(ComboObj.contain_combopop(e)===true||ComboObj.contain_combo(e)===true)return;var obj=e.relatedTarget;while(obj){if(obj==this)return;obj=obj.parentNode;}
unload_combopop();}
ComboObj.do_focusOut=function(e){if(!combopopObj)return;unload_combopop();}
ComboObj.do_keydown=function(e){var ncode=e.keyCode;if(ncode===27||ncode===9){unload_combopop();}
else if(ncode===13||ncode===38||ncode===40){combopopSvg.let_keydown(ncode);}}
ComboObj.mouseDownRoot=function(e){if(ComboObj.contain_combopop(e)===true)return;unload_combopop();}
ComboObj.contain_combopop=function(e){var areaRect=combopopDiv.getBoundingClientRect();var _x=e.clientX;var _y=e.clientY;if(areaRect.left<=_x&&_x<=areaRect.right&&areaRect.top<=_y&&_y<=areaRect.bottom)return true;return false;}
ComboObj.contain_combo=function(e){var areaRect=comboDiv.getBoundingClientRect();var _x=e.clientX;var _y=e.clientY;if(areaRect.left<=_x&&_x<=areaRect.right&&areaRect.top<=_y&&_y<=areaRect.bottom)return true;return false;}
ComboObj.set_expComboData=function(){var callmodefrt=CataInfo.get_cataCallModeFront();var alen=cataBoxData.expCode.length;var tcode,str,linestr,pcode,cstep;for(var i=0;i<alen;i++){tcode=cataBoxData.expCode[i];str=cataBoxData.expData[tcode];if(callmodefrt==="normal"&&str.substr(11,1)==="D")continue;pcode=PageInfo.get_parentCode(tcode);if(cataBoxData.linkCate[pcode]==undefined){cstep=PageInfo.get_currentStep(tcode);cataBoxData.linkCate[pcode]=new Array();}
cataBoxData.linkCate[pcode].push(tcode);}
cstep=PageInfo.get_currentStep("");for(i=0;i<cstep;i++){tcode=PageInfo.cateCode.substr(i*2,2)+repeat_string("00",4-i);cataBoxData.expView[tcode]=true;}}
ComboObj.set_comboData=function(){var codeStep=PageInfo.get_currentStep("");var callmodefrt=CataInfo.get_cataCallModeFront();var alen=cataBoxData.expCode.length;var k=0;var tcode,str,linestr,pnCode,p4Code;if(MenuInfo.moveInDist===true){if(codeStep===1){pnCode=PageInfo.cateCode.substr(0,2);for(var i=0;i<alen;i++){tcode=cataBoxData.expCode[i];str=cataBoxData.expData[tcode];if(callmodefrt==="normal"&&str.substr(11,1)==="D")continue;if(str.substr(13,1)!=="0")continue;linestr=str.split("|");if(tcode.substr(2,8)==="00000000"){if(PageInfo.cateCode===tcode){cataBoxData.currIndex=k;PageInfo.cateName=linestr[2];}
cataBoxData.arCataTitle[k]=linestr[2];cataBoxData.arCataDir[k]=tcode;k++;}}}
else{var slen=codeStep*2;var rlen=10-slen-2;var scomp="0000000000".substr(0,rlen);pnCode=PageInfo.cateCode.substr(0,slen);for(var i=0;i<alen;i++){tcode=cataBoxData.expCode[i];str=cataBoxData.expData[tcode];if(callmodefrt==="normal"&&str.substr(11,1)==="D")continue;if(str.substr(13,1)!=="0")continue;linestr=str.split("|");if(tcode.substr(0,slen)===pnCode&&tcode.substr(slen+2,rlen)===scomp){if(PageInfo.cateCode===tcode){cataBoxData.currIndex=k;PageInfo.cateName=linestr[2];}
cataBoxData.arCataTitle[k]=linestr[2];cataBoxData.arCataDir[k]=tcode;k++;}}}}
else{var slen=codeStep*2;var rlen=10-slen-2;var scomp="0000000000".substr(0,rlen);pnCode=PageInfo.cateCode.substr(0,slen);for(var i=0;i<alen;i++){tcode=cataBoxData.expCode[i];str=cataBoxData.expData[tcode];if(callmodefrt==="normal"&&str.substr(11,1)==="D")continue;if(str.substr(13,1)==="0")continue;linestr=str.split("|");if(tcode.substr(0,slen)===pnCode&&tcode.substr(slen+2,rlen)===scomp){if(PageInfo.cateCode===tcode){cataBoxData.currIndex=k;PageInfo.cateName=linestr[2];}
cataBoxData.arCataTitle[k]=linestr[2];cataBoxData.arCataDir[k]=linestr[3];k++;}}}}
function firstbtnClick(){if(PermitMan.get_firstPerm("firstbtn")===false)return;Action.aniLocking=true;if(Action.drawCondition===0)go_direct(PageInfo.firstPage);else{if(MoveInfo.pairEnlarge===true)go_directEnc(PageInfo.firstPage);else if(Action.drawCondition===11&&PageInfo.currentPage===0)go_nearEnc(3);else go_directEnc(PageInfo.firstPage);}}
function prevbtnClick(){if(PermitMan.get_prevPerm("prevbtn")===false)return;Action.aniLocking=true;if(Action.drawCondition===0)go_prev(true);else if(MoveInfo.pairEnlarge===true||Action.drawCondition===10||ScreenInfo.onesmc===true)go_nextEnc(4,"prev");else if(Action.drawCondition===11)go_nearEnc(3);}
function nextbtnClick(){if(PermitMan.get_nextPerm("nextbtn")===false)return;Action.aniLocking=true;if(Action.drawCondition===-1)CoverObj.do_coverAnimation("next");else if(Action.drawCondition===0)go_next(true);else if(MoveInfo.pairEnlarge===true||Action.drawCondition===11||ScreenInfo.onesmc===true)go_nextEnc(3,"next");else if(Action.drawCondition===10)go_nearEnc(4);}
function slidebtnClick(){if(PermitMan.get_nextPerm("slidebtn")===false)return;Action.aniLocking=true;Action.mainState="slide";if(Action.drawCondition===-1)CoverObj.do_coverAnimation("next");else if(Action.drawCondition===0)go_next(true);else if(Action.drawCondition>9){if(MoveInfo.slideEnlarge===true){if(MoveInfo.pairEnlarge===true||Action.drawCondition===11||ScreenInfo.onesmc===true)go_nextEnc(3,"next");else if(Action.drawCondition===10)go_nearEnc(4);}
else go_downsize();}}
function lastbtnClick(){if(PermitMan.get_lastPerm("lastbtn")===false)return;Action.aniLocking=true;if(Action.drawCondition===-1)CoverObj.do_coverAnimation("last");else if(Action.drawCondition===0){if(ScreenInfo.onesmc===true)go_direct(PageInfo.lastPage);else go_direct(PageInfo.lastPage-1);}
else{if(MoveInfo.pairEnlarge===true||ScreenInfo.onesmc===true)go_directEnc(PageInfo.lastPage);else if(Action.drawCondition===10&&PageInfo.currentPage===(PageInfo.lastPage-1))go_nearEnc(4);else go_directEnc(PageInfo.lastPage);}}
function indexbtnClick(n){if(MenuInfo.indexType==="H"||FileInfo.idxFile===false)return;if(indexSvg!=undefined){unload_index();return;}
if(PermitMan.normalPerm(-1)===false)return;NewinObj.openAni=(n==undefined)?0:n;if(CataInfo.incview==="m"){if(NewinObj.openAni===1)load_indexa(true);else load_indexm(true);}
else load_index();}
function glassesbtnClick(){if(glassesSvg!=undefined){unload_glasses();return;}
if(PermitMan.normalsmcPerm()===false)return;if(SmcObj.etcPermission("glasses")===false)return;load_glasses();}
function expbtnClick(n){if(expSvg)return;if(PermitMan.normalPerm(-1)===false)return;NewinObj.openAni=(n==undefined)?0:n;Action.aniLocking=true;MenuInfo.currShowMenu="explorer";load_explorer(true);}
function totalbtnClick(n){if(expSvg)return;if(PermitMan.normalPerm(-1)===false)return;NewinObj.openAni=(n==undefined)?0:n;Action.aniLocking=true;MenuInfo.currShowMenu="total";load_explorer(true);}
function mailbtnClick(){if(MenuInfo.mailButtonHide!="N")return;if(PermitMan.normalPerm(-1)===false)return;load_mail(true);}
function printbtnClick(){if(PermitMan.normalPerm(-1)===false)return;if(SkinInfo.printkind==="000")return;if(PrintInfo.partPrint===true&&Action.drawCondition===-1)return;if(SkinInfo.printkind==="999"&&Action.drawCondition===0){alert(get_sentence(CataInfo.cataLang,"enprint",""));return;}
if(SkinInfo.printkind==="001"&&printSvg!=undefined)return;load_print(true);}
function capturebtnClick(){if(PermitMan.normalPerm(-1)===false)return;MenuObj.swap_captureImg(true);Action.set_mainState("capture");load_partprint('capture');}
function helpbtnClick(){if(PermitMan.normalPerm(-1)===false)return;load_help(true);}
function noteClick(){if(PermitMan.normalPerm(-1)===false)return;load_note(true);}
function snsbtnClick(n){if(PermitMan.normalPerm(-1)===false)return;if(MenuInfo.snsButtonHide!=="N")return;NewinObj.openAni=(n==undefined)?0:n;load_sns(true);}
//function facebookbtnClick(){if(LinkInfo.snstext==="")return;window.open("http://www.facebook.com/sharer.php?u="+encodeURIComponent(ServerInfo.selfUrl)+"&t="+encodeURIComponent(LinkInfo.snstext));}
//function twitterbtnClick(){if(LinkInfo.snstext==="")return;var sendUrl=encodeURIComponent(LinkInfo.snstext)+"%20"+encodeURIComponent(ServerInfo.selfUrl);window.open("https://twitter.com/intent/tweet?url="+sendUrl+"&text="+sendUrl);}
//function kakaobtnClick(){if(LinkInfo.snstext===""||LinkInfo.snsImage==="")return;Kakao.Link.sendDefault({objectType:'feed',content:{title:LinkInfo.snstext,imageUrl:LinkInfo.snsImage,link:{mobileWebUrl:ServerInfo.selfUrl,webUrl:ServerInfo.selfUrl}}});}
//function kakaostorybtnClick(){if(LinkInfo.snstext==="")return;Kakao.Story.share({url:ServerInfo.selfUrl,text:LinkInfo.snstext});}
function facebookbtnClick(){if(LinkInfo.snstext==="")return;window.open("http://www.facebook.com/sharer.php?u="+encodeURIComponent(window.location.href)+"&t="+encodeURIComponent(LinkInfo.snstext));}
function twitterbtnClick(){if(LinkInfo.snstext==="")return;var sendUrl=encodeURIComponent(LinkInfo.snstext)+"%20"+encodeURIComponent(window.location.href);window.open("https://twitter.com/intent/tweet?url="+sendUrl);}
function kakaobtnClick(){
	if(LinkInfo.snstext===""||LinkInfo.snsImage==="")return;
	Kakao.Link.sendDefault({objectType:'feed',
	content:{
		title:LinkInfo.snstext,
		imageUrl:window.location.href.slice(0,-14) + 'catImage/'+ PageInfo.cataDir +'/' + LinkInfo.snsImage, 
		link:{mobileWebUrl:window.location.href,webUrl:window.location.href}
	}});
}
function urlcopybtnClick(e){document.getElementById("urlcopy").value=ServerInfo.get_snsLinkUrl(2);document.getElementById("urlcopy").select();document.execCommand("Copy");alert(get_sentence(CataInfo.cataLang,"copied",""));}
function closebtnClick(){self.close();}
function fullscrbtnClick(e){var elem=document.documentElement;if(ScreenInfo.displayState==="normal"){ScreenInfo.displayState="fullscreen";if(elem.requestFullscreen){elem.requestFullscreen();}
else if(elem.msRequestFullscreen){elem.msRequestFullscreen();}
else if(elem.mozRequestFullScreen){elem.mozRequestFullScreen();}
else if(elem.webkitRequestFullscreen){elem.webkitRequestFullscreen();}
else{elem.webkitRequestFullScreen.call(elem);}}
else{ScreenInfo.displayState="normal";if(document.exitFullscreen){document.exitFullscreen();}
else if(document.msExitFullscreen){document.msExitFullscreen();}
else if(document.mozCancelFullScreen){document.mozCancelFullScreen();}
else if(document.webkitCancelFullScreen){document.webkitCancelFullScreen();}
else{document.webkitCancelFullScreen.call(elem);}}}
function leftOnsmClick(){if(PermitMan.get_prevPerm("onsmimageL")===false)return;Action.aniLocking=true;go_prev(true);}
function rightOnsmClick(){if(PermitMan.get_nextPerm("onsmimageR")===false)return;Action.aniLocking=true;if(Action.drawCondition===-1)CoverObj.do_coverAnimation("next");else go_next(true);}
function do_searchbtnClick(s,custom){if(s==="")return false;if(PermitMan.normalPerm(-1)===false)return false;if(searchSvg)return false;if(SearchInfo.get_qtxtPatternPerm(s)===false){alert(get_sentence(CataInfo.cataLang,"searchword",""));return false;}
if(custom==undefined)custom=0;SearchInfo.set_qtxt(s);load_search(custom,1);return false;}
function do_searchbtn2Click(){if(PermitMan.normalPerm(-1)===false)return;if(searchSvg)return;load_search(0,0);}
function do_qtxtFocusIn(obj){if(PermitMan.normalPerm(-1)===false){obj.blur();return;}
Action.keyDownBlock=true;Action.resizeLocking=true;obj.value="";if(SearchInfo.searchMark===true){SearchInfo.searchMark=false;LinkObj.remove_searchData();}}
function do_qtxtFocusOut(obj){Action.keyDownBlock=false;Action.resizeLocking=false;}
function spacerbtnClick(s){if(PermitMan.normalPerm(-1)===false)return;if(SpacerInfo.retrieved===false){SpacerInfo.retrieve_item();SpacerInfo.retrieved=true;}
var permit1=true,permit2=true;if(s==="left"||s==="both"||ScreenInfo.onesmc===true){permit1=PermitMan.get_spcerAddPerm(PageInfo.currentPage);if(permit1===true)SpacerInfo.add_item(""+PageInfo.currentPage,0);}
if((s==="both"||s==="right")&&ScreenInfo.onesmc===false){permit2=PermitMan.get_spcerAddPerm(PageInfo.currentPage+1);if(permit2===true)SpacerInfo.add_item(""+(PageInfo.currentPage+1),0);}
load_spacer(s,true);}
function combobtnClick(custom,n){if(PermitMan.normalPerm(-1)===false)return;if(SkinInfo.combokind==="000")return;NewinObj.openAni=(n==undefined)?0:n;if(!custom)custom="0";load_combo(true,'c',custom);}
function enlargebtnClick(skd){if(PermitMan.get_enlargePerm()===false)return;if(ScreenInfo.onesmc===true&&SmcObj.leftUrl==="")return;var leftRight=false;if(skd==="L")leftRight=true;else if(skd==="R")leftRight=false;else{if(ScreenInfo.onesmc===true)leftRight=false;else leftRight=(SmcObj.leftUrl==="")?false:true;}
Action.aniLocking=true;go_enlarge(leftRight,"current");}
function downsizebtnClick(){if(Action.drawCondition<10)return;Action.aniLocking=true;go_downsize();}
function endownsizebtnClick(s){if(Action.drawCondition===0)enlargebtnClick(s);else if(Action.drawCondition>9)downsizebtnClick();}
function show_fadeback(){if(document.getElementById('fadesect').style.visibility=="visible")return;resize_fadeback();document.getElementById('fadesect').style.visibility="visible";}
function hide_fadeback(){document.getElementById('fadesect').style.width="1px";document.getElementById('fadesect').style.height="1px";document.getElementById('fadesect').style.visibility="hidden";}
function resize_fadeback(){document.getElementById('fadesect').style.width=stageWidth+"px";document.getElementById('fadesect').style.height=stageHeight+"px";}
function change_image_src(eid,sc){document.getElementById(eid).src=sc;}
function show_debug(s,bool){debugDiv.style.visibility="visible";if(bool==undefined)debugDiv.innerHTML=s;else if(bool===false)debugDiv.appendChild(document.createTextNode(s));else{debugDiv.appendChild(document.createTextNode(s));debugDiv.appendChild(document.createElement("br"));}}
function templ_newin(nw,d,w,h,svgObj,titletext,fullscrbtn,closebtn){var ws;ws='<svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">'
+'<defs>'
+'<linearGradient id="newin_titleGradient">';if(d==="001"){ws+='<stop offset="0%" stop-color="#5A7685" />'
+'<stop offset="100%" stop-color="#A9B5C2" />';}
else if(d==="010"){ws+='<stop offset="0%`" stop-color="#111111" />'
+'<stop offset="100%" stop-color="#666666" />';}
else if(d==="011"){ws+='<stop offset="0%" stop-color="#41830F" />'
+'<stop offset="100%" stop-color="#394F20" />';}
else if(d==="020"){ws+='<stop offset="0%" stop-color="#555555" />'
+'<stop offset="100%" stop-color="#999999" />';}
else if(d==="030"){ws+='<stop offset="0%" stop-color="#329FD0" />'
+'<stop offset="100%" stop-color="#96E5ED" />';}
else if(d==="301"){ws+='<stop offset="0%" stop-color="#5283c0" />'
+'<stop offset="100%" stop-color="#96c8ff" />';}
else if(d==="302"){ws+='<stop offset="0%" stop-color="#121212" />'
+'<stop offset="100%" stop-color="#3C476F" />';}
ws+='</linearGradient>'
+'</defs>';ws+='<g onmousedown="NewinObj.do_mousedownTitle(evt, '+svgObj+');">'
+'<rect id="newin_titlerect" x="0" y="0" width="'+(w-5.5)+'" height="21" fill="url(#newin_titleGradient)" />'
+'<text id="newin_titletext" class="newin_titletext5d" x="3" y="14" fill="#ffffff">'+titletext+'</text>';if(fullscrbtn===1){ws+='<a xlink:href="javascript:'+svgObj+'.newin_fullscr();"><image id="newin_titlefullscrbtn" class="hover_opac6" cursor="pointer" '
+'x="'+(w-30)+'" y="5" width="11" height="11" xlink:href="./skin5/win/fullscr_11.png">'
+'<title>'+get_sentence(CataInfo.cataLang,"fullscr","")+'</title>'
+'</image></a>';}
if(closebtn===1){ws+='<a xlink:href="javascript:'+svgObj+'.newin_close();"><image id="newin_titleclosebtn" class="hover_opac6" cursor="pointer" '
+'x="'+(w-15)+'" y="5" width="11" height="11" xlink:href="./skin5/win/close_11.png">'
+'<title>'+get_sentence(CataInfo.cataLang,"closew","")+'</title>'
+'</image></a>';}
ws+='</g>';ws+='<line id="newin_bodyTline" x1="0.5" y1="22.5" x2="'+w+'" y2="22.5" stroke="#666666" />'
+'<line id="newin_bodyLline" x1="0.5" y1="22.5" x2="0.5" y2="'+h+'" stroke="#666666" />'
+'<line id="newin_bodyRline" x1="'+(w-0.5)+'" y1="22.5" x2="'+(w-0.5)+'" y2="'+(h-0.5)+'" stroke="#bbbbbb" />'
+'<line id="newin_bodyBline" x1="0.5" y1="'+(h-0.5)+'" x2="'+(w-0.5)+'" y2="'+(h-0.5)+'" stroke="#bbbbbb" />'
+'</svg>'
+'</div>';return ws;}
