var Action,CataInfo,ServerInfo,ScreenInfo,PageInfo,MenuInfo,FileInfo,SkinInfo,UnifyInfo,MoveInfo;var SearchInfo,SoundInfo,LinkInfo,PrintInfo,TouchInfo,SpacerInfo,GuideInfo,WinInfo,BBwInfo,CustomInfo;var winRect,cataRect,desRect,smRect,btmenuY;var cataBoxData={currIndex:-1,expCode:[],expData:[],linkCate:[],expView:[],arCataTitle:[],arCataDir:[]};var ConnectMan={currDir:'',currIdx:0};var DataMan={cataboxData:-1,arLinkData:[],arSoundData:[],arCoordData:[],arPicData:[],dobufDim:false};var PermitMan={aniSvg:false};var DebugMan={strTitle:''};var ParaMan;var ScreenMan={};var BookInfo={arTitle:[],arSearch:[],arCont:[]};function set_action(b1,b2,b3){Action={mainState:'normal',main2State:'',prevState:[],drawCondition:-2,aniLocking:false,wheelLocking:false,resizeLocking:false,loadto:0,loaded:0,mouseDragClip:undefined,keyDownBlock:false,arKeyDownClip:[],keyDownFunc:undefined,keyUpFunc:undefined,togetherEnlarge:false,downKind:'',mouseDragged:false,mouseDownBlock:false,mouseDowned:false,showAltText:b1,showLinkText:b2,touchStartTime:0,touchEndTime:0,arWheelClip:[],wheelSeq:0,wheelNum:0,wheelEnded:false,doubleClickTime:300,multiTouchTime:30,mouseTouch:b3,arMoveClip:[],arUpClip:[]};Action.set_mainState=function(s){Action.prevState.push(Action.mainState);Action.mainState=s;}
Action.restoreState=function(){var s=Action.prevState.pop();Action.mainState=s;}
Action.set_togetherEnlarge=function(){Action.togetherEnlarge=(PageInfo.blank_imageSet(PageInfo.currentPage)==true)?false:true;}
Action.do_mouseDown=function(s,e){Action.mouseDowned=true;if(Action.mainState==="slide"){Action.mainState="stop";Action.mouseDownBlock=true;}
if(combopopSvg!=undefined){ComboObj.mouseDownRoot(e);Action.mouseDownBlock=true;}}
Action.do_touchStart=function(s,e){Action.mouseDowned=true;if(Action.mainState==="slide"){Action.mainState="stop";Action.mouseDownBlock=true;}
}
Action.do_mouseMove=function(s,e){if(Action.downKind==="newin"){NewinObj.do_mousemove(e);}
else if(MenuInfo.menuAutoHide===true){if(!AniObj.mmTimer){if(e.clientY<ScreenInfo.topSwapDist&&AniObj.mmY===0)do_menuAnimate('show');else if(e.clientY>ScreenInfo.topSwapDist&&AniObj.mmY===-ScreenInfo.topSwapDist)do_menuAnimate('hide');}
if(!AniObj.lwTimer&&MenuInfo.soundMenuHide===false){if(e.clientY>desRect.bottom&&AniObj.lwY===0)do_lowerAnimate('show');else if(e.clientY<desRect.bottom&&AniObj.lwY===-ScreenInfo.bottomSwapDist)do_lowerAnimate('hide');}}
for(var i=0;i<Action.arMoveClip.length;i++){if(Action.arMoveClip[i].do_mouseMove(e)===true)break;}
if(combopop2Svg!=undefined){Combo2Obj.do_mouseOut(e);}}
Action.do_mouseDrag=function(e){if(Action.mouseDragClip!=undefined)return Action.mouseDragClip.do_mouseDrag(e);return false;}
Action.do_mouseUp=function(s,e){if(Action.mouseDragClip!=undefined){Action.mouseDragClip.do_mouseUp(e);Action.mouseDragClip=undefined;Action.mouseDragged=false;return;}
SmcObj.do_mouseUp(e);for(var i=0;i<Action.arUpClip.length;i++){if(Action.arUpClip[i].do_mouseUp(e)===true)break;}
Action.downKind="";Action.mouseDowned=false;Action.mouseDragged=false;if(Action.mouseDownBlock===true){setTimeout(function(){Action.mouseDownBlock=false},100);}}
Action.do_touchEnd=function(s,e){if(Action.mouseDragClip!=undefined){Action.mouseDragClip.do_touchEnd();Action.mouseDragClip=undefined;Action.mouseDragged=false;return;}
Action.downKind="";Action.mouseDowned=false;Action.mouseDragged=false;if(Action.mouseDownBlock===true){setTimeout(function(){Action.mouseDownBlock=false},100);}}
Action.do_mouseWheel=function(s,e){if(Action.aniLocking===true||Action.wheelLocking===true)return;if(Action.drawCondition===0||Action.drawCondition===-1){Action.wheelSeq++;if(Action.wheelSeq===1){Action.wheelNum=Action.wheelSeq;setTimeout(function(){Action.do_mouseWheel2(e)},300);}}
else{EncObj.do_mouseWheel(e);}}
Action.do_mouseWheel2=function(e){if(Action.arWheelClip.length===0)return;for(var i=0;i<Action.arWheelClip.length;i++){if(Action.arWheelClip[i].do_mouseWheel(e)===true)break;}}
Action.get_dblclicked=function(dtime){if(dtime<=Action.doubleClickTime)return true;return false;}
Action.do_keyDown=function(s,e){if(Action.keyDownBlock===true)return;if(Action.keyDownFunc!=undefined){Action.keyDownFunc(e);return;}
if(Action.arKeyDownClip.length===0)return;for(var i=0;i<Action.arKeyDownClip.length;i++){if(Action.arKeyDownClip[i].do_keyDown(e)===true)break;}
}
Action.do_keyUp=function(s,e){if(Action.keyUpFunc!=undefined)Action.keyUpFunc(e);if(Action.drawCondition>9)EncObj.do_keyUp(e);}}
function set_catainfo(c1,s2,b3,s4,s5,s6,s7,s8,s9,b10,b11,s12){CataInfo={cataVersion:'9.9.2',cataSerial:'',cataDist:'',cataLang:s12,loLang:s12,cataLangType:'option',cataVariant:'standard',memberType:b11,skinTyp:'pack',licenseDomain:[],useProtocol:'http:',useDomain:'',usePort:'80',checkDomain:false,incview:s9,cdmake:b10,servType:c1,catimage:s2,openingAnimation:b3,cataCallMode:s4,cataCharset:s5,backType:s6,backColor:s7,backAlign:s8};if(s12==="ko")CataInfo.loLang="";CataInfo.get_cataCallModeFront=function(){var idx=CataInfo.cataCallMode.indexOf("_");if(idx===-1)return CataInfo.cataCallMode;return CataInfo.cataCallMode.substr(0,idx);}
CataInfo.get_cataCallModeRear=function(){var idx=CataInfo.cataCallMode.indexOf("_");if(idx===-1)return"";return CataInfo.cataCallMode.substr(idx+1);}
CataInfo.get_useSchemAuth=function(){var s=CataInfo.useProtocol+"//"+CataInfo.useDomain;if(CataInfo.usePort!=="80")s+=":"+CataInfo.usePort;return s;}}
function set_serverinfo(s1,s2,s3,s4,s5,n6,s7,s8){ServerInfo={serverUrl:s1,progExt:s2,selfUrl:s3,snsurlKind:0,memberID:s4,memberName:s5,loggedInfo:'',memberSignedIn:n6,applyCipher:false,cpKey:'aabbccddeeffgghh',cpScript:'',fileCipher:false,wasUrl:s8};ServerInfo.cpScript="cipherdata."+ServerInfo.progExt;if(s7==="Y"||s7==="F"){ServerInfo.applyCipher=true;if(s7==="F")ServerInfo.fileCipher=true;}
if(CataInfo.cdmake===true&&CataInfo.useProtocol!=="file"){ServerInfo.selfUrl=CataInfo.get_useSchemAuth()+window.location.pathname;}
ServerInfo.get_frontPart=function(folder,wawe){var url="";if(CataInfo.cataVariant==="MBLOG")url=ServerInfo.get_memberPart(folder);if(wawe==undefined){if(ServerInfo.serverUrl!=="")url=ServerInfo.serverUrl+url;}
else if(wawe==="was"){if(ServerInfo.wasUrl!=="")url=ServerInfo.wasUrl+url;}
return url;}
ServerInfo.get_memberPart=function(folder){var url="";switch(folder){case"":case"catImage":case"flash":case"log":case"media":case"sound":case"image":url="home/"+ServerInfo.memberID;break;case"access":case"cdinfo":case"conf":case"include":case"manual":case"send":case"skin":case"skin5":default:url="";}
return url;}
ServerInfo.get_cataDoculink=function(docu,sdir,cimage,start,cate,callmode,eclang){var qstr=docu;qstr+=(sdir==undefined)?"?Dir="+PageInfo.cataDir:"?Dir="+sdir;qstr+=(cimage==undefined)?"&catimage="+CataInfo.catimage:"&catimage="+cimage;qstr+=(start==undefined)?"&start="+ParaMan.start:"&start="+start;qstr+=(cate==undefined)?"&cate="+ParaMan.cate:"&cate="+cate;qstr+=(callmode==undefined)?"&callmode="+CataInfo.cataCallMode:"&callmode="+callmode;qstr+=(eclang==undefined)?"&eclang="+ParaMan.eclang:"&eclang="+eclang;return FileInfo.frontPath("","was")+"/"+qstr;}
ServerInfo.get_srzDoculink=function(docu,sdir,cimage,start,cate,callmode,eclang){var qstr=docu+"?srz=";qstr+=(sdir==undefined)?PageInfo.cataDir:sdir;qstr+=(cimage==undefined)?"__"+CataInfo.catimage:"__"+cimage;qstr+=(start==undefined)?"__"+ParaMan.start:"__"+start;qstr+=(cate==undefined)?"__"+ParaMan.cate:"__"+cate;qstr+=(callmode==undefined)?"__"+CataInfo.cataCallMode:"__"+callmode;qstr+=(eclang==undefined)?"__"+ParaMan.eclang:"__"+eclang;return FileInfo.frontPath("","was")+"/"+qstr;}
ServerInfo.get_snsLinkUrl=function(nkd){if(nkd==undefined)nkd=ServerInfo.snsurlKind;if(nkd===0)return ServerInfo.selfUrl;else if(nkd===1)return ServerInfo.selfUrl.replace(/start=([^&#]*)/,"");return ServerInfo.selfUrl.replace(/start=([^&#]*)/,"")+"&start=a"+PageInfo.currentPage;}}
function set_skininfo(s1,s2,s3,s4,s5,s6,s8,s9,s10,s11,s12,s13,s14,b15,s16,s17){SkinInfo={mainmenu:s1,smc:s2,onsmimage:s3,combokind:s4,onbigimage:s5,nwclass:s6,nw2class:s6,cbpopskin:s8,spacerbtn:s9,dclass:s10,printkind:s11,helpmc:s12,smckind:s13,mmtype:s14,smcgallery:b15,indexmc:s16,smcenter:s17,nwsns:'014'};if(s2==="007"||s2==="008")CataInfo.openingAnimation=false;if(CataInfo.incview==="m")SkinInfo.nwsns=SkinInfo.nwclass;if(s6==="017"||s6==="021")SkinInfo.nw2class="016";}
function set_screeninfo(n1,n2,n3,n4,n5,b6,s7,n8,s9,n10,s11,s12,b13,b14,b15){ScreenInfo={smImageOriWidth:n1,smImageOriHeight:n2,smImageWidth:n1,smImageHeight:n2,smImageWidthHalf:n1/2,smImageHeightHalf:n2/2,innerOriWidth:0,bigImageOriWidth:n3,bigImageOriHeight:n4,bigImageWidth:n3,bigImageHeight:n4,midImageWidth:n5,midImageHeight:0,displayState:'normal',onesmc:b6,blankColor:s9,bigImageRect:undefined,bigDragRect:undefined,codeWidth:10000,codeHeight:10000,logoTopMargin:n10,ratioWH:0,ratioBS:0,ratioBSO:0,ratioBCO:0,syncImgToWin:s7,syncMargin:n8,syncRealHappen:false,syncRef:'both',topSwapDist:0,bottomSwapDist:0,orientation:window.orientation,m_alignVert:s11,imgRender:s12,pchZoom:b13,smImageDiff:b14,syncAddWidth:0,syncAddHeight:0,sporient:b15,befonesmc:b6};if(ScreenInfo.midImageWidth!=0)ScreenInfo.midImageHeight=Math.floor(ScreenInfo.midImageWidth*ScreenInfo.bigImageOriHeight/ScreenInfo.bigImageOriWidth);ScreenInfo.ratioWH=ScreenInfo.smImageOriWidth/ScreenInfo.smImageOriHeight;ScreenInfo.ratioBSO=ScreenInfo.bigImageOriWidth/ScreenInfo.smImageOriWidth;ScreenInfo.ratioBS=ScreenInfo.bigImageWidth/ScreenInfo.smImageWidth;ScreenInfo.ratioBCO=1;if(CataInfo.incview==="m"){if(CataInfo.cdmake===true&&check_tablet()===false)ScreenInfo.onesmc=true;else if(ScreenInfo.sporient===true){ScreenInfo.onesmc=(Math.abs(ScreenInfo.orientation)===90)?false:true;}}
if(ScreenInfo.smImageDiff===true)DataMan.dobufDim=true;ScreenInfo.set_bigImageVar=function(w,h){ScreenInfo.bigImageWidth=w;ScreenInfo.bigImageHeight=h;ScreenInfo.ratioBS=ScreenInfo.bigImageWidth/ScreenInfo.smImageWidth;ScreenInfo.ratioBCO=ScreenInfo.bigImageWidth/ScreenInfo.bigImageOriWidth;GuideInfo.ratioGB=GuideInfo.width/ScreenInfo.bigImageWidth;}
ScreenInfo.get_thumbQtyFromWidth=function(w,winpad,thumbWidth,imgspacing){if(w===0)w=cataRect.width;var k=Math.floor((w-winpad-thumbWidth)/(thumbWidth+imgspacing));return(k+1);}
ScreenInfo.get_thumbQtyFromHeight=function(h,winpad,thumbHeight,imgspacing){if(h===0)h=cataRect.height;var k=Math.floor((h-winpad-thumbHeight)/(thumbHeight+imgspacing));return(k+1);}
ScreenInfo.set_smRectDrag=function(ax,ay){if(ScreenInfo.onesmc===true)smRect=new Rectangle(ax,ay,ScreenInfo.smImageWidth,ScreenInfo.smImageHeight);else smRect=new Rectangle(ax,ay,ScreenInfo.smImageWidth*2,ScreenInfo.smImageHeight);}
ScreenInfo.set_gallerySmProperty=function(w,h){ScreenInfo.smImageOriWidth=w;ScreenInfo.smImageOriHeight=h;ScreenInfo.bigImageOriWidth=w;ScreenInfo.bigImageOriHeight=h;ScreenInfo.bigImageWidth=w;ScreenInfo.bigImageHeight=h;if(ScreenInfo.syncImgToWin=="N"||(ScreenInfo.syncImgToWin=="S"&&(ScreenInfo.smImageWidth>ScreenInfo.smImageOriWidth||ScreenInfo.smImageHeight>ScreenInfo.smImageOriHeight))){ScreenInfo.smImageWidth=ScreenInfo.smImageOriWidth;ScreenInfo.smImageWidthHalf=ScreenInfo.smImageWidth/2;ScreenInfo.smImageHeight=ScreenInfo.smImageOriHeight;ScreenInfo.smImageHeightHalf=ScreenInfo.smImageHeight/2;ScreenInfo.ratioBS=ScreenInfo.bigImageWidth/ScreenInfo.smImageWidth;}}}
function set_cataRect(n1,n2,n3,n4,n5,n6,n7,n8){if(MenuInfo.soundMenuHide===true)n8=0;if(MenuInfo.menuAutoHide===true){ScreenInfo.topSwapDist=(SkinInfo.mmtype==="bottom")?-100:n2;ScreenInfo.bottomSwapDist=n8;n2=0;n4=0;}
winRect=new Rectangle(0,0,stageWidth,stageHeight);cataRect=new Rectangle(n1,n2,stageWidth-n1-n3,stageHeight-n2-n4);desRect=new Rectangle(n1+n5,n2+n6,stageWidth-n1-n3-n5-n7,stageHeight-n2-n4-n6-n8);ScreenInfo.syncRealHappen=true;var onlywidth=(ScreenInfo.syncRef==="width")?true:false;if(ScreenInfo.syncImgToWin==="Y")set_syncProperty(onlywidth,false);else if(ScreenInfo.syncImgToWin==="S")set_syncProperty(onlywidth,true);var py=desRect.centerPt.y-Math.floor(ScreenInfo.smImageHeightHalf);if(py<n2)py=n2;if(ScreenInfo.onesmc===true){smRect=new Rectangle(desRect.centerPt.x-Math.floor(ScreenInfo.smImageWidthHalf),py,ScreenInfo.smImageWidth,ScreenInfo.smImageHeight);}
else{smRect=new Rectangle(desRect.centerPt.x-ScreenInfo.smImageWidth,py,ScreenInfo.smImageWidth*2,ScreenInfo.smImageHeight);}}
function set_cataRectm(n1,n2,n3,n4,n5,n6,n7,n8){var tw=stageWidth;var th=stageHeight;desRect=new Rectangle(n1+n5,n2+n6,tw-n1-n3-n5-n7,th-n2-n4-n6-n8);ScreenInfo.syncRealHappen=true;if(ScreenInfo.syncImgToWin==="Y")set_syncProperty(true,false);else if(ScreenInfo.syncImgToWin==="S")set_syncProperty(true,true);else if(ScreenInfo.syncImgToWin==="D")set_syncProperty(false,true);if(ScreenInfo.syncImgToWin==="N"&&ScreenInfo.smImageOriWidth>(stageWidth-n1-n3)){tw=ScreenInfo.smImageOriWidth+n1+n3+ScreenInfo.syncMargin*2;}
if(ScreenInfo.smImageHeight>(stageHeight-n2-n4)){th=ScreenInfo.smImageHeight+n2+n4+ScreenInfo.syncMargin*2;}
winRect=new Rectangle(0,0,tw,th);cataRect=new Rectangle(n1,n2,tw-n1-n3,th-n2-n4);desRect=new Rectangle(n1+n5,n2+n6,tw-n1-n3-n5-n7,th-n2-n4-n6-n8);var py;if(ScreenInfo.m_alignVert==="top")py=n2+ScreenInfo.syncMargin;else if(ScreenInfo.m_alignVert==="center")py=desRect.centerPt.y-Math.floor(ScreenInfo.smImageHeightHalf);else if(ScreenInfo.m_alignVert==="bottom")py=cataRect.bottom-ScreenInfo.smImageHeight-ScreenInfo.syncMargin;if(py<n2)py=n2;if(ScreenInfo.onesmc===true){smRect=new Rectangle(desRect.centerPt.x-Math.floor(ScreenInfo.smImageWidthHalf),py,ScreenInfo.smImageWidth,ScreenInfo.smImageHeight);}
else{smRect=new Rectangle(desRect.centerPt.x-ScreenInfo.smImageWidth,py,ScreenInfo.smImageWidth*2,ScreenInfo.smImageHeight);}}
function set_syncProperty(onlywidth,whenbigger){if(SkinInfo.spacerbtn==="030")ScreenInfo.syncAddWidth=111;else if(SkinInfo.spacerbtn==="031")ScreenInfo.syncAddWidth=46;else if(SkinInfo.spacerbtn==="032")ScreenInfo.syncAddWidth=46;var tw=(ScreenInfo.onesmc===true)?desRect.width-ScreenInfo.syncMargin*2:(desRect.width-ScreenInfo.syncMargin*2)*0.5;var th=desRect.height-ScreenInfo.syncMargin*2;if(onlywidth===true){ScreenInfo.smImageWidth=tw-ScreenInfo.syncAddWidth;ScreenInfo.smImageHeight=Math.floor((tw-ScreenInfo.syncAddWidth)/ScreenInfo.ratioWH);}
else{if(((tw-ScreenInfo.syncAddWidth)/ScreenInfo.ratioWH)>th){ScreenInfo.smImageWidth=Math.floor(th*ScreenInfo.ratioWH);ScreenInfo.smImageHeight=th;}
else{ScreenInfo.smImageWidth=tw-ScreenInfo.syncAddWidth;ScreenInfo.smImageHeight=Math.floor((tw-ScreenInfo.syncAddWidth)/ScreenInfo.ratioWH);}}
if(whenbigger===true){if(ScreenInfo.smImageWidth>ScreenInfo.smImageOriWidth&&ScreenInfo.smImageHeight>ScreenInfo.smImageOriHeight){ScreenInfo.smImageWidth=ScreenInfo.smImageOriWidth;ScreenInfo.smImageHeight=ScreenInfo.smImageOriHeight;}}
ScreenInfo.smImageWidthHalf=ScreenInfo.smImageWidth*0.5;ScreenInfo.smImageHeightHalf=ScreenInfo.smImageHeight*0.5;ScreenInfo.ratioBS=ScreenInfo.bigImageWidth/ScreenInfo.smImageWidth;}
function set_pageinfo(s1,s2,n3,n4,n5,n6,s7,s8,s9,s10,b11){PageInfo={cateCode:s1,origDir:s10,cataDir:s2,basicDir:'',cateName:s8,origFirstPage:n3,firstPage:n3,lastPage:0,prevPage:0,currentPage:0,cataPages:n4,showPno:n4,remPage:b11,oriStartPage:n5,startPage:n5,showStartPage:n6,previewPage:[],pageshowKind:s7};PageInfo.set_firstLast=function(){PageInfo.firstPage=PageInfo.origFirstPage;if(PageInfo.origFirstPage===0&&(ScreenInfo.onesmc===true||SkinInfo.smc==="008"))PageInfo.firstPage=1;if(ScreenInfo.onesmc===true)PageInfo.lastPage=PageInfo.cataPages;else PageInfo.lastPage=((PageInfo.firstPage+PageInfo.cataPages)%2===0)?PageInfo.cataPages+1:PageInfo.cataPages;if(PageInfo.startPage<PageInfo.firstPage)PageInfo.startPage=PageInfo.firstPage;else if(PageInfo.startPage>PageInfo.cataPages)PageInfo.startPage=((PageInfo.firstPage+PageInfo.cataPages)%2===0)?PageInfo.cataPages:PageInfo.cataPages-1;else PageInfo.startPage=((PageInfo.firstPage+PageInfo.startPage)%2===0||ScreenInfo.onesmc===true)?PageInfo.startPage:PageInfo.startPage-1;}
PageInfo.blank_imageSet=function(page){if(PageInfo.blank_image(page)===0||PageInfo.blank_image(page+1)===1)return true;else return false;}
PageInfo.blank_image=function(page){if(page==0&&FileInfo.s000FileName==="")return 0;else if(PageInfo.lastPage===page&&PageInfo.lastPage!=PageInfo.cataPages)return 1;else return 2;}
PageInfo.blank_imageFromLeft=function(page){if(page==0&&FileInfo.s000FileName==="")return 0;else if(PageInfo.lastPage===(page+1)&&PageInfo.lastPage!=PageInfo.cataPages)return 1;else return 2;}
PageInfo.get_nextPageNo=function(){if((Action.drawCondition<=0||Action.togetherEnlarge===true)&&ScreenInfo.onesmc===false)return(PageInfo.currentPage+2);return(PageInfo.currentPage+1);}
PageInfo.get_prevPageNo=function(){if((Action.drawCondition<=0||Action.togetherEnlarge===true)&&ScreenInfo.onesmc===false)return(PageInfo.currentPage-2);return(PageInfo.currentPage-1);}
PageInfo.is_currPage=function(n,s){if(s==="user"&&PageInfo.showStartPage>0)n=PageInfo.get_realFromShowPage(n);if(Action.drawCondition<=0||Action.togetherEnlarge==true){if(ScreenInfo.onesmc===true){if(n==PageInfo.currentPage)return true;else return false;}
else{if(PageInfo.currentPage===n||(PageInfo.currentPage+1)===n)return true;}}
if(Action.drawCondition===10&&PageInfo.currentPage===n)return true;if(Action.drawCondition===11&&(PageInfo.currentPage+1)===n)return true;return false;}
PageInfo.is_firstPage=function(){if(PageInfo.currentPage==PageInfo.firstPage){if(Action.drawCondition<=0||Action.togetherEnlarge===true)return true;if(Action.drawCondition===10)return true;if(Action.drawCondition===11&&PageInfo.blank_image(PageInfo.currentPage)===0)return true;}
return false;}
PageInfo.is_lastPage=function(){if(ScreenInfo.onesmc===true&&PageInfo.currentPage===PageInfo.lastPage)return true;if(ScreenInfo.onesmc===false&&PageInfo.currentPage===(PageInfo.lastPage-1)){if(Action.drawCondition<=0||Action.togetherEnlarge===true)return true;if(Action.drawCondition===11)return true;if(Action.drawCondition===10&&PageInfo.blank_image(PageInfo.currentPage+1)===1)return true;}
return false;}
PageInfo.reset_pageNext=function(){PageInfo.prevPage=PageInfo.currentPage;if(PageInfo.is_lastPage()===true)PageInfo.currentPage=PageInfo.firstPage;else if(ScreenInfo.onesmc===true)PageInfo.currentPage+=1;else PageInfo.currentPage+=2;}
PageInfo.reset_pagePrev=function(){PageInfo.prevPage=PageInfo.currentPage;if(PageInfo.is_firstPage()===true)PageInfo.currentPage=PageInfo.lastPage-1;else if(ScreenInfo.onesmc===true)PageInfo.currentPage-=1;else PageInfo.currentPage-=2;}
PageInfo.restore_page=function(){PageInfo.currentPage=PageInfo.prevPage;}
PageInfo.get_directPageNo=function(n){if(ScreenInfo.onesmc===true){if(n<PageInfo.firstPage)return PageInfo.firstPage;else if(n>=PageInfo.cataPages)return PageInfo.cataPages;}
else{if(n<PageInfo.firstPage)return PageInfo.firstPage;else if(n>=PageInfo.lastPage)return(PageInfo.lastPage-1);else if(n%2!=PageInfo.firstPage)return(n-1);}
return n;}
PageInfo.get_pageshowString=function(page){if(ScreenInfo.onesmc===true)return PageInfo.get_pageFromShowkind(page);if(Action.drawCondition<=0||Action.togetherEnlarge===true){if(page===0)return PageInfo.get_pageFromShowkind(page+1);else if(page===PageInfo.cataPages)return PageInfo.get_pageFromShowkind(page);else{var p1=PageInfo.get_pageFromShowkind(page);var p2=PageInfo.get_pageFromShowkind(page+1);if(p1==="")return p2;else if(p2==="")return p1;else return p1+"-"+p2;}}
else{if(Action.drawCondition===10)return PageInfo.get_pageFromShowkind(page);else return PageInfo.get_pageFromShowkind(page+1);}
return"";}
PageInfo.get_pageFromShowkind=function(page){var showpage;if(PageInfo.showStartPage>0){showpage=PageInfo.get_showPageFromReal(page);if(showpage<1)return"";}
else showpage=page;if(showpage>PageInfo.cataPages)showpage=PageInfo.cataPages;if(PageInfo.pageshowKind==="number")return""+showpage;return FileInfo.get_minusExtension(showpage,-1);}
PageInfo.get_showPageFromReal=function(page){return(page-PageInfo.showStartPage+1);}
PageInfo.get_realFromShowPage=function(page){if(PageInfo.showStartPage===0)return page;return(page+PageInfo.showStartPage-1);}
PageInfo.get_showPage=function(page){var n=PageInfo.get_nshowPage(page);if(n<=0)return"";return""+n;}
PageInfo.get_nshowPage=function(page){if(PageInfo.showStartPage===0)return page;var n=PageInfo.get_showPageFromReal(page);return n;}
PageInfo.get_parentCode=function(code){if(code==="")code=PageInfo.cateCode;if(code.substr(2,8)==="00000000")return"0000000000";if(code.substr(4,6)==="000000")return code.substr(0,2)+"00000000";if(code.substr(6,4)==="0000")return code.substr(0,4)+"000000";if(code.substr(8,2)==="00")return code.substr(0,6)+"0000";return code.substr(0,8)+"00";}
PageInfo.get_currentStep=function(code){if(code==="")code=PageInfo.cateCode;if(code.substr(2,8)==="00000000")return 0;if(code.substr(4,6)==="000000")return 1;if(code.substr(6,4)==="0000")return 2;if(code.substr(8,2)==="00")return 3;return 4;}
PageInfo.reset_openingVarFromUnify=function(n){PageInfo.cataPages=n;if(ScreenInfo.onesmc===true)PageInfo.lastPage=PageInfo.cataPages;else PageInfo.lastPage=((PageInfo.firstPage+PageInfo.cataPages)%2===0)?PageInfo.cataPages+1:PageInfo.cataPages;PageInfo.startPage=PageInfo.oriStartPage;if(PageInfo.startPage<PageInfo.firstPage)PageInfo.startPage=PageInfo.firstPage;else if(PageInfo.startPage>PageInfo.cataPages)PageInfo.startPage=PageInfo.lastPage;else PageInfo.startPage=((PageInfo.firstPage+PageInfo.startPage)%2===0)?PageInfo.startPage:PageInfo.startPage-1;PageInfo.currentPage=PageInfo.startPage;}
PageInfo.is_previewPage=function(pno){if(PageInfo.previewPage.indexOf(pno)!==-1)return true;return false;}
PageInfo.get_nextPreviewPage=function(pno){for(var i=0;i<PageInfo.previewPage.length;i++){if(pno<PageInfo.previewPage[i])return PageInfo.previewPage[i];}
return-1;}
PageInfo.get_prevPreviewPage=function(pno){for(var i=PageInfo.previewPage.length-1;i>=0;i--){if(PageInfo.previewPage[i]<pno)return PageInfo.previewPage[i];}
return-1;}
PageInfo.store_toLocal=function(n){localStorage.setItem("curp"+SpacerInfo.cKey,n);}
PageInfo.get_imagePage=function(page){if(ScreenInfo.onesmc===true)return page;if(PageInfo.blank_image(page)===0)return(page+1);return page;}
PageInfo.set_firstLast();PageInfo.currentPage=PageInfo.startPage;if(CataInfo.memberType==="P"&&s9!==""){var range=[];s9=s9.replace(/ /g,'');if(s9.indexOf(",")<0){if(s9.indexOf("-")<0)range.push("0-"+s9);else range.push(s9);}
else range=s9.split(",");var str,pos,spage,epage;for(var i=0;i<range.length;i++){str=range[i];if(str=="")continue;pos=str.indexOf("-");if(pos<0){var cln=parseInt(str);if(PageInfo.previewPage.indexOf(cln)===-1)PageInfo.previewPage.push(cln);}
else{spage=parseInt(str.substr(0,pos));epage=parseInt(str.substr(pos+1));for(var j=spage;j<=epage;j++){if(PageInfo.previewPage.indexOf(j)===-1)PageInfo.previewPage.push(j);}}}}}
function set_menuinfo(c1,c2,c3,n4,b6,b7,b8,c9,b10,c11,n13,n14,n15,n16,s17,c18){MenuInfo={moveInDist:c1,moveInClass:c2,moveInSamekind:c3,thumbHeight:n4,applyMax:c9,currShowMenu:'explorer',sizeMenuType:'guide',openingIndexView:b6,menuAutoHide:b7,soundMenuHide:b8,mailButtonHide:b10,indexType:c11,snsButtonHide:'N',snsButtonAlpha:0.3,m_thumbWidth:n13,m_thumbHeight:n14,idxPos:'lefttop',indexWidth:n15,indexHeight:n16,helpImage:'',helpWidth:0,helpHeight:0,searchWidth:0,searchHeight:0,idxmorebtn:true,cdselkind:c18};if(UnifyInfo.classUnify===true)MenuInfo.applyMax="N";if(s17!==""){var aaa=s17.split(",");MenuInfo.helpImage=aaa[0];MenuInfo.helpWidth=parseInt(aaa[1]);MenuInfo.helpHeight=parseInt(aaa[2]);}
MenuInfo.get_nextCate=function(cate,nstep){if(nstep===0)return(MenuInfo.nextChar(cate.substr(0,2))+"00000000");else if(nstep===1)return cate.substr(0,2)+MenuInfo.nextChar(cate.substr(2,2))+"000000";else if(nstep===2)return cate.substr(0,4)+MenuInfo.nextChar(cate.substr(4,2))+"0000";else if(nstep===3)return cate.substr(0,6)+MenuInfo.nextChar(cate.substr(6,2))+"00";else if(nstep===4)return cate.substr(0,8)+MenuInfo.nextChar(cate.substr(8,2));return"";}
MenuInfo.nextChar=function(s){if(!s||s==="")return"01";var an=s.charCodeAt(0);var bn=s.charCodeAt(1);if(bn===122)return MenuInfo.nextAscii(an)+"1";else return s.substr(0,1)+MenuInfo.nextAscii(bn);}
MenuInfo.nextAscii=function(n){if(n===57)return String.fromCharCode(65);else if(n===90)return String.fromCharCode(97);return String.fromCharCode(n+1);}}
function set_guideinfo(n1){GuideInfo={guidePt:undefined,sizePt:undefined,width:0,height:n1,ratioGB:1.0};if(ScreenInfo.smImageHeight===0)GuideInfo.width=0;else GuideInfo.width=Math.floor(GuideInfo.height*ScreenInfo.smImageWidth/ScreenInfo.smImageHeight);GuideInfo.ratioGB=GuideInfo.width/ScreenInfo.bigImageWidth;}
function set_unifyinfo(b1,b2){UnifyInfo={classUnify:b1,outpage:b2,dirLen:0,thisPageNo:0,fileseqLoadOnce:false,arDir:[],arFirstPage:[],arFileseq:[],arPageNo:[],arPageAccuNo:[],arSearchMethod:[],arOutPage:[],arShowPno:[]};UnifyInfo.get_diridxFromPage=function(page){for(var i=0;i<UnifyInfo.dirLen;i++){if(page<=UnifyInfo.arPageAccuNo[i])return i;}
return(UnifyInfo.dirLen-1);}
UnifyInfo.get_realNumber=function(n,idxn){if(idxn==-1)idxn=UnifyInfo.get_diridxFromPage(n);var accuNo=(idxn===0)?0:UnifyInfo.arPageAccuNo[idxn-1];if(UnifyInfo.outpage==false)return(n-accuNo);else{if(idxn>0&&UnifyInfo.arDir[idxn]==UnifyInfo.arDir[0])return(n-accuNo-1+UnifyInfo.arOutPage[idxn]);else return(n-accuNo);}}
UnifyInfo.get_virtualNumber=function(n,idxn){if(idxn===-1)idxn=UnifyInfo.get_diridxFromPage(n);var accuNo=(idxn===0)?0:UnifyInfo.arPageAccuNo[idxn-1];return(n+accuNo);}}
function set_fileinfo(b1,b2,b3,b4,b5,b6,b7,b8,b9,b10,s11,s12,s13,s14,s15){FileInfo={idxFile:b1,searchFile:b2,mediaFile:b3,downFile:b4,scrollFile:b5,linkFile:[],flashFile:b7,picdataFile:[],pagesoundFile:[],coordFile:[],arFileName:[],arFileConf:[],s000FileName:s11,diskType:s12,seqFile:[],fileExt:get_fileExtension(s14),smReplaced:false,xmlExt:s15};FileInfo.linkFile[PageInfo.cataDir]=b6;FileInfo.picdataFile[PageInfo.cataDir]=b8;FileInfo.pagesoundFile[PageInfo.cataDir]=b9;FileInfo.coordFile[PageInfo.cataDir]=b10;FileInfo.seqFile[PageInfo.cataDir]=s13;if(s12==="CD")ServerInfo.progExt="html";FileInfo.cimgFilePath=function(page,prefix,sdir,catimg){if(page<0)return new Array("","",sdir);else if(page>PageInfo.cataPages)return new Array("","",sdir);if(sdir==="")sdir=PageInfo.cataDir;catimg=(catimg==="*")?"catImage"+CataInfo.catimage:"catImage"+catimg;var realno;var fname="";if(UnifyInfo.classUnify===true){var idxn=UnifyInfo.get_diridxFromPage(page);sdir=UnifyInfo.arDir[idxn];realno=UnifyInfo.get_realNumber(page,-1);if(idxn===0&&page===0)fname=FileInfo.s000FileName;else if(idxn===(UnifyInfo.dirLen-1)&&PageInfo.blank_image(page)===1)fname="blank";else if(FileInfo.seqFile[sdir]==="F"||FileInfo.seqFile[sdir]=="X"){if(FileInfo.arFileConf[sdir][realno-1].substr(0,1)==="2")fname="blank";else fname=FileInfo.arFileName[sdir][realno-1];}
else{fname=FileInfo.get_catImageFileName("",realno);}}
else{if(page===0)fname=FileInfo.s000FileName;else if(PageInfo.blank_image(page)===1)fname="blank";else{if(FileInfo.seqFile[sdir]==="F"||FileInfo.seqFile[sdir]==="X"){var aridx=page-1;var sconf=FileInfo.arFileConf[sdir][aridx];fname=FileInfo.arFileName[sdir][aridx];if(sconf==undefined||fname==undefined)fname="blank";else if(fname===""||page>FileInfo.arFileName[sdir].length)fname="blank";else if(sconf.substr(0,1)==="2")fname="blank";}
else{fname=FileInfo.get_catImageFileName("",page);}}}
if(fname===""||fname==="blank")return new Array("","",sdir);return new Array(FileInfo.frontPath("catImage")+"/"+catimg+"/"+sdir+"/"+prefix+fname,fname,sdir);}
FileInfo.cimg2FilePath=function(page,prefix,sdir,catimg){catimg=(catimg==="*")?"catImage"+CataInfo.catimage:"catImage"+catimg;var aaa=FileInfo.get_page2FromFilename(""+page,sdir);if(aaa[1]=="")return new Array("","",sdir);return new Array(FileInfo.frontPath("catImage")+"/"+catimg+"/"+aaa[0]+"/"+aaa[1],aaa[1],aaa[0]);}
FileInfo.thumbFilePath=function(page,prefix,sdir,catimg){if(sdir==="")sdir=PageInfo.cataDir;if(catimg==="*")catimg=CataInfo.catimage;var fname="";if(UnifyInfo.classUnify===true){var idxn=UnifyInfo.get_diridxFromPage(page);sdir=UnifyInfo.arDir[idxn];var realno=UnifyInfo.get_realNumber(page,-1);if(idxn==0&&page==0)fname=FileInfo.s000FileName;else{if(FileInfo.seqFile[sdir]=="N")fname=FileInfo.get_catImageFileName(prefix,realno)
else{if(FileInfo.arFileConf[sdir][realno-1].substr(0,1)==="2")fname="blank";else fname=prefix+FileInfo.arFileName[sdir][realno-1];}}
if(fname==="blank"||fname==="")return new Array("","",sdir);return new Array(FileInfo.frontPath("catImage")+"/catImage"+catimg+"/"+sdir+"/"+fname,fname,sdir);}
else{return FileInfo.cimgFilePath(page,prefix,sdir,catimg);}}
FileInfo.get_catImageFileName=function(prefix,n){return prefix+digit3(n)+"."+FileInfo.fileExt;}
FileInfo.frontPath=function(folder,wawe){var s=ServerInfo.get_frontPart(folder,wawe);if(s=="")return"";if(s.substr(-1)==="/")return s.substring(0,s.length-1);return s;}
FileInfo.skinFilePath=function(fname){return FileInfo.frontPath("skin")+"/skin/"+fname;}
FileInfo.skin5FilePath=function(fname){return FileInfo.frontPath("skin5")+"/skin5/"+fname;}
FileInfo.catFilePath=function(fname,catimg){if(catimg==="*")return FileInfo.frontPath("catImage")+"/catImage"+CataInfo.catimage+"/"+fname;return FileInfo.frontPath("catImage")+"/catImage"+catimg+"/"+fname;}
FileInfo.dirFilePath=function(fname,dir,catimg){if(dir==="")dir=PageInfo.cataDir;if(catimg==="*")catimg=CataInfo.catimage;return FileInfo.frontPath("catImage")+"/catImage"+catimg+"/"+dir+"/"+fname;}
FileInfo.mediaFilePath=function(fname){if(FileInfo.check_outUrl(fname)===true)return fname;return FileInfo.frontPath("media")+"/media/"+fname;}
FileInfo.flashFilePath=function(fname){if(FileInfo.check_outUrl(fname)===true)return fname;return FileInfo.frontPath("flash")+"/flash/"+fname;}
FileInfo.soundFilePath=function(fname,dir,catimg){if(FileInfo.check_outUrl(fname)===true)return fname;if(dir==="")dir=PageInfo.cataDir;if(catimg==="*")catimg=CataInfo.catimage;if(fname.substr(0,1)==="*")return FileInfo.mediaFilePath(fname.substr(1));return FileInfo.frontPath("catImage")+"/catImage"+catimg+"/"+dir+"/sound/"+fname;}
FileInfo.movieFilePath=function(fname,dir,catimg){if(FileInfo.check_outUrl(fname)===true)return fname;if(dir==="")dir=PageInfo.cataDir;if(catimg==="*")catimg=CataInfo.catimage;if(fname.substr(0,1)==="*")return FileInfo.mediaFilePath(fname.substr(1));return FileInfo.frontPath("catImage")+"/catImage"+catimg+"/"+dir+"/movie/"+fname;}
FileInfo.imageFilePath=function(fname,dir,catimg){if(FileInfo.check_outUrl(fname)===true)return fname;if(dir==="")dir=PageInfo.cataDir;if(catimg==="*")catimg=CataInfo.catimage;if(fname.substr(0,1)==="*")return FileInfo.mediaFilePath(fname.substr(1));return FileInfo.frontPath("catImage")+"/catImage"+catimg+"/"+dir+"/image/"+fname;}
FileInfo.rootimageFilePath=function(fname){return FileInfo.frontPath("image")+"/image/"+fname;}
FileInfo.get_minusExtension=function(page,idxn){var s;if(UnifyInfo.classUnify==true){if(idxn===-1)idxn=UnifyInfo.get_diridxFromPage(page);var sdir=UnifyInfo.arDir[idxn];if(FileInfo.seqFile[sdir]=="N")return"";var realno=UnifyInfo.get_realNumber(page,-1);s=FileInfo.arFileName[sdir][realno-1];}
else{if(FileInfo.seqFile[PageInfo.cataDir]=="N")return"";s=FileInfo.arFileName[PageInfo.cataDir][page-1];}
return remove_frtZero(get_minusExtension(s));}
FileInfo.get_pageFromFilename=function(fname,sdir){if(UnifyInfo.classUnify===false||sdir!==""){var tdir=(sdir!=="")?sdir:PageInfo.cataDir;var k=1;var arr=FileInfo.arFileName[tdir];for(var i=0;i<arr.length;i++){tname=arr[i];if(remove_frtZero(get_minusExtension(tname))===fname)return k;k++;}}
else{for(var i=0;i<UnifyInfo.dirLen;i++){var tdir=UnifyInfo.arDir[i];if(FileInfo.seqFile[tdir]=="N")continue;var ar=FileInfo.arFileName[tdir];var alen=ar.length;for(var j=0;j<alen;j++){if(remove_frtZero(get_minusExtension(ar[j]))===fname){if(i===0)return j;return(UnifyInfo.arPageAccuNo[i-1]+j);}}}}
return-1;}
FileInfo.get_page2FromFilename=function(fname,sdir){if(UnifyInfo.classUnify===false||sdir!==""){var tdir=(sdir!=="")?sdir:PageInfo.cataDir;var arr=FileInfo.arFileName[tdir];for(var i=0;i<arr.length;i++){if(remove_frtZero(get_minusExtension(arr[i]))===fname)return new Array(tdir,arr[i]);}}
else{for(var i=0;i<UnifyInfo.dirLen;i++){var tdir=UnifyInfo.arDir[i];if(FileInfo.seqFile[tdir]=="N")continue;var ar=FileInfo.arFileName[tdir];var alen=ar.length;for(var j=0;j<alen;j++){if(remove_frtZero(get_minusExtension(ar[j]))===fname)return new Array(tdir,ar[j]);}}}
return new Array("","");}
FileInfo.check_outUrl=function(s){if(s.length<8)return false;if(s.substr(0,7)==="http://"||s.substr(0,8)==="https://")return true;return false;}}
function set_moveinfo(c1,b2,b3,b4,b5,b6,n7,n8,b9,b10,b11){MoveInfo={pageOverSpeed:c1,skipLastFirst:b2,enlargeClick:b3,enlarge2Step:b4,pairEnlarge:b5,slideEnlarge:b6,slideIntervalSM:n7,slideIntervalBIG:n8,bigImageOnly:b9,spDrag:b10,pageIcon:b11,loadLinkAtSlide:false,backMoveText:[],backMoveValu:[],backMaxItems:10,loadAni:true};if(ScreenInfo.midImageWidth==0||ScreenInfo.midImageHeight==0)MoveInfo.enlarge2Step=false;if(SkinInfo.mainmenu==="012"||SkinInfo.dclass==="016"||SkinInfo.mainmenu==="021")MoveInfo.pageIcon=false;if(SkinInfo.smcgallery===true)MoveInfo.enlargeClick=false;if(ScreenInfo.onesmc===true)MoveInfo.pairEnlarge=false;MoveInfo.show_pageNumber=function(){MenuObj.show_pageNumber();if(MoveInfo.pageIcon===true)CoverObj.show_pageIconHtml(true);}
MoveInfo.get_showPageNumber=function(){if(SkinInfo.smc==="004"||(SkinInfo.smc==="007"&&CataInfo.incview!=="m")||SkinInfo.smc==="008")return aniSvg.get_pageFromShowkind();return PageInfo.get_pageshowString(PageInfo.currentPage);}
MoveInfo.get_currTime=function(){var now=new Date();return now.getTime();}
MoveInfo.move_systemPage=function(pno){if(PermitMan.get_directGoPermNumber("",pno,"system")===false)return;go_general(pno,"system");}
MoveInfo.move_strPage=function(spno){var n=PermitMan.get_directGoPerm("showboard",spno,"","");if(n<0)return;go_general(n,"user");}}
function set_searchinfo(c1,s2,s3,b4,s5,n6,b7,b8){SearchInfo={searchMethod:c1,searchUrl:s2,qtxt:'',arqtxt:[],searchMark:false,arSearchSize:[],arSearchRot:[],arSearchCoords:[],distinctCase:b4,searchColor:s5,searchAlpha:n6,oneResultWhenUnify:true,coordTeleLink:b7,coordWebLink:b8,xmlPageGap:0,useCoords:false,areaCode:'02',applyQuickSearch:false,quickSearchKind:'page',scrape:'',showThumb:false};SearchInfo.set_qtxt=function(s){SearchInfo.arqtxt=[];SearchInfo.qtxt=s;var aaa=s.split(" ");for(var i=0;i<aaa.length;i++){if(aaa[i].trim()!=""){if(SearchInfo.distinctCase===true)SearchInfo.arqtxt.push(aaa[i].trim());else SearchInfo.arqtxt.push(aaa[i].trim().toLowerCase());}}}
SearchInfo.get_qtxtPatternPerm=function(s){var pattern3=/[~!@#$%^&*()+|<>?:{}]/;if(pattern3.test(s))return false;return true;}
if(s3!=""){SearchInfo.set_qtxt(s3);SearchInfo.searchMark=true;}
if(b7===true||b8===true)SearchInfo.useCoords=true;}
function set_soundinfo(c1,s2,c3,b4,s5,b6,b7,b8,b9,b10){SoundInfo={openingMusicPlay:c1,musicCfg:s2,soundAppKind:c3,arPageSoundFile:[],currState:0,pageoverAtSndEnd:b4,soundLinkHeader:s5,sndplayAtPageOpen:b6,leftRightUnify:b7,markLinkArea:b8,arLeftMP3:[],arRightMP3:[],sndplayInAlert:b9,sndplayInOver:b10,soundCtrlLoc:""}
if(SkinInfo.smc==="008")SoundInfo.sndplayInOver=false;SoundInfo.get_pageSoundFile=function(n){if(n==1){if(SoundInfo.arPageSoundFile[SmcObj.leftDir]==undefined)return"";if(SoundInfo.arPageSoundFile[SmcObj.leftDir][SmcObj.leftName]==undefined)return"";return SoundInfo.arPageSoundFile[SmcObj.leftDir][SmcObj.leftName];}
if(SoundInfo.arPageSoundFile[SmcObj.rightDir]==undefined)return"";if(SoundInfo.arPageSoundFile[SmcObj.rightDir][SmcObj.rightName]==undefined)return"";return SoundInfo.arPageSoundFile[SmcObj.rightDir][SmcObj.rightName];}}
function set_linkinfo(s1,s2,n3,b4,c5,c6,b7,s8,s9,s10,s11,s12,n13,n14){LinkInfo={displayStr:s1,displayColor:s2,displayAlpha:n3,sameIconSize:b4,markingVar:c5,markingKind:c6,prdLinkShow:true,hgLineColor:'#FF0000',hgAlpha:1,hgLineThick:3,swapColor:'#FFFFFF',swapAlpha:1,sameSwapSize:false,showDescript:b7,snstext:s8,descript:s10,snsImage:s12,snsImgWidth:n13,snsImgHeight:n14,imgLinkTitle:'',arLinkPoly:[],arLinkExpl:[],arLinkRule:[],arExpData:[],arExpDataPtr:[],arFlashLink:[],arImgDescript:[]};if(LinkInfo.displayColor===""){LinkInfo.displayColor="#FF0000";}
else if(LinkInfo.displayColor.toLowerCase()==="#xxxxxx"){LinkInfo.displayColor="#FFFFFF";LinkInfo.displayAlpha=0;}
LinkInfo.get_indexPtr=function(sdir,fname){var na=new Array();if(LinkInfo.arExpDataPtr[sdir]==undefined||LinkInfo.arExpDataPtr[sdir][fname]==undefined)return na;var sa=LinkInfo.arExpDataPtr[sdir][fname].split(";");var tstr,rule,nptr;for(var i=0,alen=sa.length;i<alen;i++){nptr=parseInt(sa[i]);tstr=LinkInfo.arExpData[sdir][nptr];if(tstr==="")continue;var linestr=tstr.split("\t");rule=linestr[3];if(rule.length>5&&rule.substr(0,5)==="[use]"){LinkInfo.set_useIndexPtr(sdir,rule.substr(5),na);}
else{var k=LinkInfo.arLinkPoly.length;na.push(k);LinkInfo.arLinkPoly[k]=new Polygon();LinkInfo.arLinkPoly[k].set_coordinates(linestr[1],true);LinkInfo.arLinkExpl[k]=linestr[2];LinkInfo.arLinkRule[k]=linestr[3];}}
return na;}
LinkInfo.set_useIndexPtr=function(sdir,fname,na){if(LinkInfo.arExpDataPtr[sdir]==undefined||LinkInfo.arExpDataPtr[sdir][fname]==undefined)return;var k=LinkInfo.arLinkPoly.length;var sa=LinkInfo.arExpDataPtr[sdir][fname].split(";");var tstr,rule,nptr;var alen=sa.length;for(var i=0;i<alen;i++){nptr=parseInt(sa[i]);tstr=LinkInfo.arExpData[sdir][nptr];if(tstr==="")continue;var linestr=tstr.split("\t");rule=linestr[3];var idx=rule.indexOf("]");if(idx===-1)continue;rule=rule.substr(idx+1);if(rule.length>5&&rule.substr(0,5)==="[use]"){na.push(k);LinkInfo.arLinkPoly[k]=new Polygon();LinkInfo.arLinkPoly[k].set_coordinates(linestr[1],true);LinkInfo.arLinkExpl[k]=linestr[2];LinkInfo.arLinkRule[k]=linestr[3];k++;}}}
LinkInfo.get_linkRuleFromPointer=function(n){if(LinkInfo.arLinkRule[n]==undefined)return"";return LinkInfo.arLinkRule[n];}
LinkInfo.get_headnruleFromRule=function(s){var k=s.indexOf("]");if(k<0)return["",s];return[s.substr(0,k+1),s.substr(k+1)];}
LinkInfo.bool_makeShape=function(linkunit){if(linkunit.head==="[ico]"||linkunit.head==="[nta]"||linkunit.head==="[lta]"||linkunit.head==="[tta]")return false;if(linkunit.head==="[swp]"||linkunit.head==="[swi]"||linkunit.head==="[sws]")return false;return true;}}
function set_printinfo(s1){PrintInfo={partPrintMode:s1,partPrint:false,frPageNo:0,toPageNo:0,newinPage:false,newinObj:undefined,caller:'',partX:0,partY:0,partWidth:0,partHeight:0,printSrc:'page'};if(isIE()||isIE11())PrintInfo.newinPage=true;}
function set_spacerinfo(){SpacerInfo={maxItems:10,storeWhere:'local',delWhenClick:false,arItem:[],arKind:[],cKey:'',retrieved:false,arColor:["#FF0000","#FF8C00","#1E90FF","#9400D3","#FFD700","#00FA9A","#DAA520","#FF1493","#778899","#808000"]};SpacerInfo.cKey=CataInfo.cataDist+"_"+CataInfo.catimage+"_"+PageInfo.cataDir;SpacerInfo.add_item=function(pno,kn){if(SpacerInfo.arItem.indexOf(pno)!==-1)return;SpacerInfo.arItem.push(pno);SpacerInfo.arKind.push(kn);if(SpacerInfo.arItem.length>SpacerInfo.maxItems){SpacerInfo.arItem.shift();SpacerInfo.arKind.shift();}
if(SpacerInfo.storeWhere==="local")SpacerInfo.store_toLocal();else if(SpacerInfo.storeWhere==="session")SpacerInfo.store_toSession();}
SpacerInfo.remove_item=function(idx){if(SpacerInfo.arItem.length===0)return;SpacerInfo.arItem.splice(idx,1);SpacerInfo.arKind.splice(idx,1);if(SpacerInfo.storeWhere==="local")SpacerInfo.store_toLocal();else if(SpacerInfo.storeWhere==="session")SpacerInfo.store_toSession();}
SpacerInfo.remove_itemValue=function(val){if(SpacerInfo.arItem.length==0)return;var idx=SpacerInfo.arItem.indexOf(val);if(idx!==-1)SpacerInfo.remove_item(idx);}
SpacerInfo.store_toLocal=function(){if(SpacerInfo.arItem.length===0)localStorage.setItem("bmrk"+SpacerInfo.cKey,"");else localStorage.setItem("bmrk"+SpacerInfo.cKey,SpacerInfo.arItem.join(":"));}
SpacerInfo.store_toSession=function(){if(SpacerInfo.arItem.length===0)sessionStorage.setItem("bmrk"+SpacerInfo.cKey,"");else sessionStorage.setItem("bmrk"+SpacerInfo.cKey,SpacerInfo.arItem.join(":"));}
SpacerInfo.retrieve_item=function(){if(SpacerInfo.storeWhere==="local"){if(localStorage.getItem("bmrk"+SpacerInfo.cKey)){SpacerInfo.arItem=localStorage.getItem("bmrk"+SpacerInfo.cKey).split(":");}}
else if(SpacerInfo.storeWhere==="session"){if(sessionStorage.getItem("bmrk"+SpacerInfo.cKey)){SpacerInfo.arItem=sessionStorage.getItem("bmrk"+SpacerInfo.cKey).split(":");}}}
SpacerInfo.empty_items=function(){SpacerInfo.arItem=[];SpacerInfo.arKind=[];if(SpacerInfo.storeWhere==="local")SpacerInfo.store_toLocal();else if(SpacerInfo.storeWhere==="session")SpacerInfo.store_toSession();}
BBwInfo={applyBBw:false,loc:'win',storeWhere:'local'};BBwInfo.prepare_turnover=function(){BBwObj.prepare_turnover();}
BBwInfo.finish_turnover=function(){BBwObj.finish_turnover();}
BBwInfo.prepare_enlarge=function(){BBwObj.prepare_turnover();}
BBwInfo.complete_downsize=function(){BBwObj.finish_turnover();}}
function set_optioninfo(s1,s2,s3,s4){ParaMan={start:s1,cate:s2,eclang:s3};if(!s4||s4==="")return;var t;var ar=s4.split("&");for(var i=0;i<ar.length;i++){t=ar[i].split("=");if(t[0]=="idxpos")MenuInfo.idxPos=t[1];else if(t[0]=="idxmorebtn"&&t[1]=="false")MenuInfo.idxmorebtn=false;else if(t[0]=="wsynchro"&&t[1]=="width")ScreenInfo.syncRef=t[1];else if(t[0]=="scrape")SearchInfo.scrape=t[1];else if(t[0]=="searchthumb"&&t[1]=="true")SearchInfo.showThumb=true;else if(t[0]=="nwfade"&&t[1]=="true")WinInfo.newinFade=true;}}
function set_wininfo(){WinInfo={m_maxWinHeight:600,newinFade:false,parentKind:'ebook'};WinInfo.get_titleHeight=function(nw2){if(nw2==="012"||nw2==="018"||nw2==="041")return 30;else if(nw2==="014")return 35;else if(nw2==="016")return 31;else if(nw2==="060")return 0;return 21;}
WinInfo.get_dragGap=function(nw2){if(nw2==="016")return 9;else if(nw2==="060")return 0;return 6;}
WinInfo.get_contexWidth=function(nw2){if(nw2==undefined)nw=SkinInfo.nw2class;if(nw2==="012"||nw2==="060")return 0;else if(nw2==="016")return 5;return 4;}
WinInfo.get_contexHeight=function(nw2){if(nw2==undefined)nw2=SkinInfo.nw2class;if(nw2==="012"||nw2==="018"||nw2==="041")return 30;else if(nw2==="014")return 38;else if(nw2==="016")return 42;else if(nw2==="060")return 0;return 26;}}
function set_touchInfo(){TouchInfo={arPoints:[0.0,0.2,0.4,0.5,0.6,0.65,0.7,0.75,0.8,0.85,0.9,0.92,0.94,0.95,0.96,0.97,0.98,0.99,1.0],flickTime:200,doubletapTime:200,touchholdTime:500,holdTimer:undefined,flicked:false};TouchInfo.get_doubleTapped=function(dtime){if(dtime<=TouchInfo.doubletapTime)return true;return false;}
TouchInfo.get_flicked=function(dtime){if(dtime<=TouchInfo.flickTime)return true;return false;}
TouchInfo.set_flicked=function(dtime){TouchInfo.flicked=TouchInfo.get_flicked(dtime);}}
function set_screenman(){ScreenMan.prepare_turnover=function(){if(loginDiv)hide_loginClip();if(typeof MenuObj.prepare_turnover==="function")MenuObj.prepare_turnover();if(BBwInfo.applyBBw===true)BBwInfo.prepare_turnover();}
ScreenMan.finish_turnover=function(){Action.wheelSeq=0;if(thumbSvg)thumbSvg.finish_turnover();SpacerObj.finish_turnover();if(typeof MenuObj.finish_turnover==="function")MenuObj.finish_turnover();if(BBwInfo.applyBBw===true)BBwInfo.finish_turnover();if(PageInfo.remPage===true)PageInfo.store_toLocal(PageInfo.currentPage);}
ScreenMan.onresize_func=function(){if(BBwInfo.applyBBw===true)BBwObj.onresize_func();}}
function set_perman(){PermitMan.normalPerm=function(n){if(Action.mainState!=="normal"&&Action.mainState!=="expand")return false;return PermitMan.drawcondPerm(n);}
PermitMan.specialPerm=function(n,s){if(Action.mainState!==s)return false;return PermitMan.drawcondPerm(n);}
PermitMan.includePerm=function(n,s){if(Action.mainState!=="normal"&&Action.mainState!==s)return false;return PermitMan.drawcondPerm(n);}
PermitMan.drawcondPerm=function(n){if(Action.aniLocking===true||Action.mouseDownBlock===true||CataInfo.checkDomain===false)return false;if(n===0&&Action.drawCondition!==0&&Action.drawCondition!==10&&Action.drawCondition!==11)return false;if(n===-1&&Action.drawCondition!==0&&Action.drawCondition!==-1&&Action.drawCondition!==10&&Action.drawCondition!==11)return false;return true;}
PermitMan.normalsmcPerm=function(){if(CataInfo.checkDomain===false)return false;if(Action.mainState!=="normal"||Action.aniLocking===true||Action.drawCondition!==0)return false;return true;}
PermitMan.check_memberZone=function(caller){if(CataInfo.memberType==="P"&&ServerInfo.memberSignedIn===0)return true;return false;}
PermitMan.access_memberZone=function(newPage,device,caller){if(CataInfo.checkDomain===false)return false;if(PermitMan.check_memberZone("")===false)return true;var cPage=-1;var accesszone=true;if(Action.drawCondition<=0){if(ScreenInfo.onesmc===true){if(device==="next"||device==="slide")newPage=PageInfo.currentPage+1;else if(device==="prev")newPage=PageInfo.currentPage-1;else if(device==="first")newPage=PageInfo.firstPage;else if(device==="last")newPage=PageInfo.lastPage;else if(device==="direct")newPage=PageInfo.get_directPageNo(newPage);if(PageInfo.is_previewPage(newPage)===false){accesszone=false;if(device==="next"||device==="slide"||device==="last")cPage=PageInfo.get_nextPreviewPage(newPage);else if(device==="prev"||device==="first")cPage=PageInfo.get_prevPreviewPage(newPage);}}
else{if(device==="next"||device==="slide")newPage=PageInfo.currentPage+2;else if(device==="prev")newPage=PageInfo.currentPage-2;else if(device==="first")newPage=PageInfo.firstPage;else if(device==="last")newPage=PageInfo.lastPage-1;else if(device==="direct")newPage=PageInfo.get_directPageNo(newPage);if(PageInfo.is_previewPage(newPage)===false&&PageInfo.is_previewPage(newPage+1)===false){accesszone=false;if(device==="next"||device==="slide"||device==="last")cPage=PageInfo.get_nextPreviewPage(newPage+1);else if(device==="prev"||device==="first")cPage=PageInfo.get_prevPreviewPage(newPage+1);}}}
else{if(device==="next"||device==="slide"){if(Action.togetherEnlarge===true)newPage=PageInfo.currentPage+2;else newPage=(Action.drawCondition===10)?PageInfo.currentPage+1:PageInfo.currentPage+2;}
else if(device==="prev"){if(Action.togetherEnlarge===true)newPage=PageInfo.currentPage-2;else newPage=(Action.drawCondition===11)?PageInfo.currentPage-1:PageInfo.currentPage-2;}
else if(device==="first"){newPage=PageInfo.firstPage;}
else if(device==="last"){newPage=(Action.togetherEnlarge===true)?PageInfo.lastPage-1:PageInfo.lastPage;}
else if(device==="direct"){if(Action.togetherEnlarge===true)newPage=PageInfo.get_directPageNo(newPage);}
if(Action.togetherEnlarge===true){if(PageInfo.is_previewPage(newPage)===false&&PageInfo.is_previewPage(newPage+1)===false){accesszone=false;if(device==="next"||device==="slide"||device==="last")cPage=PageInfo.get_nextPreviewPage(newPage+1);else if(device==="prev"||device==="first")cPage=PageInfo.get_prevPreviewPage(newPage+1);}}
else{if(PageInfo.is_previewPage(newPage)===false){accesszone=false;if(device==="next"||device==="slide"||device==="last")cPage=PageInfo.get_nextPreviewPage(newPage);else if(device==="prev"||device==="first")cPage=PageInfo.get_prevPreviewPage(newPage);}}}
if(accesszone===true)return true;if(cPage!==-1){go_general(cPage,"user");return false;}
if(caller!=="wheel"&&device!=="drag")DebugMan.notify_memberZone(0);return false;}
PermitMan.get_staLinkPerm=function(){if(Action.mainState==="slide"&&MoveInfo.loadLinkAtSlide===true)return true;if(Action.mainState!=="normal")return false;if(Action.drawCondition<-1)return false;return true;}
PermitMan.get_directGoPerm=function(caller,spage,pageshow,state){if(CataInfo.checkDomain===false)return-9;if(state===""){if(PermitMan.normalPerm(-1)===false)return-1;}
else{if(PermitMan.specialPerm(-1,state)===false)return-1;}
if(spage==undefined||spage==="")return-1;var n=PermitMan.get_pageFromFilename(spage,pageshow);if(n<-1)return n;if(PageInfo.is_currPage(n,"user")===true)return-2;if(PermitMan.access_memberZone(n,"direct",caller)===false)return-4;return n;}
PermitMan.get_directGoPermNumber=function(caller,n,sysuser){if(CataInfo.checkDomain==false)return false;if(caller!=="freepass"&&(caller==="explorer"||caller==="search"||caller==="spacer"||caller==="note")){if(PermitMan.specialPerm(-1,caller)===false)return false;}
else{if(PermitMan.normalPerm(-1)===false)return false;}
if(SmcObj.etcPermission("direct")===false)return false;if(PageInfo.is_currPage(n,sysuser)===true)return false;if(PermitMan.access_memberZone(n,"direct",caller)===false)return false;return true;}
PermitMan.get_pageFromFilename=function(spage,pageshow){if(CataInfo.checkDomain===false)return-1;if(pageshow==="")pageshow=PageInfo.pageshowKind;var n;if(pageshow==="filename"){n=FileInfo.get_pageFromFilename(spage,"");if(n<0)return-8;n++;}
else{n=parseInt(spage);if(isNaN(n)||n<0)return-1;}
return n;}
PermitMan.get_spcerAddPerm=function(pno){if(Action.mainState!=="spacer"&&Action.mainState!=="normal")return false;if(Action.aniLocking==true||Action.drawCondition<0)return false;if(PageInfo.blank_image(pno)===0)return false;return true;}
PermitMan.get_firstPerm=function(scaller){if(PermitMan.get_movingStatePerm()===false&&PermitMan.normalPerm(0)===false)return false;if(SmcObj.firstPermission(scaller)===false)return false;if(PermitMan.access_memberZone(PageInfo.firstPage,"first",scaller)===false)return false;return true;}
PermitMan.get_prevPerm=function(scaller){if(PermitMan.get_movingStatePerm()===false&&PermitMan.normalPerm(0)===false)return false;if(SmcObj.prevPermission(scaller)===false)return false;if(PermitMan.access_memberZone(-2,"prev",scaller)===false)return false;return true;}
PermitMan.get_nextPerm=function(scaller){if(PermitMan.get_movingStatePerm()===false&&PermitMan.normalPerm(-1)===false)return false;if(SmcObj.nextPermission(scaller)===false)return false;if(PermitMan.access_memberZone(-1,"next",scaller)==false)return false;return true;}
PermitMan.get_lastPerm=function(scaller){if(PermitMan.get_movingStatePerm()===false&&PermitMan.normalPerm(-1)===false)return false;if(SmcObj.nextPermission(scaller)===false)return false;if(PermitMan.access_memberZone(PageInfo.cataPages,"last",scaller)==false)return false;return true;}
PermitMan.get_enlargePerm=function(){if(Action.drawCondition>0)return false;if(PermitMan.get_movingStatePerm()===false&&PermitMan.normalPerm(0)===false)return false;if(MoveInfo.enlargeClick===false)return false;if(Action.mouseDragClip!=undefined&&Action.mouseDragged===true)return false;return true;}
PermitMan.get_openingPerm=function(){if(PermitMan.access_memberZone(PageInfo.currentPage,"opening","")===false)return false;return true;}
PermitMan.get_movingStatePerm=function(){if(Action.mainState==="blackboard")return true;return false;}}
function set_debugman(){DebugMan.notify_memberZone=function(n){memberzone(n);}
DebugMan.traceLog=function(s,b){console.log(s);if(b==true){load_alert(s,true);}}}
function set_connman(){ConnectMan.load_unifyData=function(){var pcode=PageInfo.get_parentCode("");var urlstr=FileInfo.catFilePath("category.txt","*");var xmlHttp=new XMLHttpRequest();xmlHttp.open("GET",urlstr);if(xmlHttp.overrideMimeType)xmlHttp.overrideMimeType("text/plain; charset=utf-8");xmlHttp.onreadystatechange=function(){if(xmlHttp.readyState!=4)return;if(xmlHttp.status==200){var restr=xmlHttp.responseText.replace(/^\s*|\s*$/g,'');var lines=restr.split("\n");var alen=lines.length;var pos,tstr;var tlinkFile,tpdataFile,tseqFile,apageno,tsoundFile,tsearchMethod;for(var i=0;i<alen;i++){tstr=lines[i].trim();if(tstr===""||tstr===undefined)continue;if(tstr.substr(0,10)!=pcode||tstr.substr(11,4)!="unif")continue;var bbb=tstr.split("\t");PageInfo.reset_openingVarFromUnify(parseInt(bbb[2]));UnifyInfo.arDir=bbb[3].split("|");apageno=bbb[4];tseqFile=bbb[5].split("|");tlinkFile=bbb[6].split("|");tsoundFile=bbb[7].split("|");tpdataFile=bbb[8].split("|");tsearchMethod=bbb[9].split("|");break;}
var aaa=apageno.split("|");UnifyInfo.dirLen=aaa.length;var accuno=0;for(i=0;i<UnifyInfo.dirLen;i++){tstr=UnifyInfo.arDir[i];FileInfo.linkFile[tstr]=(tlinkFile[i]=="N")?false:true;FileInfo.picdataFile[tstr]=(tpdataFile==undefined||tpdataFile[i]==undefined||tpdataFile[i]=="N")?false:true;FileInfo.seqFile[tstr]=tseqFile[i];FileInfo.pagesoundFile[tstr]=tsoundFile[i];UnifyInfo.arSearchMethod[tstr]=tsearchMethod[i];if(tseqFile[i]=="F")UnifyInfo.fileseqLoadOnce=true;UnifyInfo.arPageNo[i]=parseInt(aaa[i]);accuno+=UnifyInfo.arPageNo[i];UnifyInfo.arPageAccuNo[i]=accuno;}
UnifyInfo.thisPageNo=UnifyInfo.arPageNo[0];if(UnifyInfo.fileseqLoadOnce==true)ConnectMan.load_fileseqAllData();else onload_func2();console.log("info.js : load_unifyData() : "+urlstr+" : "+xmlHttp.readyState);}
else{console.log("[Error] info.js : load_unifyData() : "+urlstr+" : "+xmlHttp.status);}}
xmlHttp.send();}
ConnectMan.load_unifyOutData=function(){var pcode=PageInfo.get_parentCode("");var urlstr=(FileInfo.diskType==="CD")?FileInfo.dirFilePath("outpage.txt"):"outpage."+ServerInfo.progExt+"?Dir="+PageInfo.cataDir+"&catimage="+CataInfo.catimage;var xmlHttp=new XMLHttpRequest();xmlHttp.open("GET",urlstr);if(xmlHttp.overrideMimeType)xmlHttp.overrideMimeType("text/plain; charset=utf-8");xmlHttp.onreadystatechange=function(){if(xmlHttp.readyState!=4)return;if(xmlHttp.status==200){var restr=xmlHttp.responseText.replace(/^\s*|\s*$/g,'');var lines=restr.split("\n");var alen=lines.length;var pos,tstr,linestr;for(var i=0;i<alen;i++){tstr=lines[i].trim();if(tstr===""||tstr===undefined)continue;if(tstr.length>6&&tstr.substr(0,7)=="outpage"){linestr=tstr;break;}}
var aaa=linestr.split("\t");var tOutPage=aaa[1].split("|");var tPageNo=aaa[4].split("|");var tFileseq=aaa[5].split("|");var tLinkfile=aaa[6].split("|");var tSoundfile=aaa[7].split("|");var tPdatafile=aaa[8].split("|");var tSearchMethod=aaa[9].split("|");var tOutDir=aaa[3].split("|");PageInfo.reset_openingVarFromUnify(parseInt(aaa[2]));var nOutPage=[];var alen=tPageNo.length;for(var i=0;i<alen;i++){var sdir=tOutDir[i];FileInfo.seqFile[sdir]=tFileseq[i];FileInfo.linkFile[sdir]=(tLinkfile[i]=="N")?false:true;FileInfo.picdataFile[sdir]=(tPdatafile[i]==undefined||tPdatafile[i]=="N")?false:true;FileInfo.pagesoundFile[sdir]=tSoundfile[i];UnifyInfo.arSearchMethod[sdir]=tSearchMethod[i];if(tLinkfile[i]=="N")DataMan.arLinkData[sdir]=-2;if(tSoundfile[i]!="Y")DataMan.arSoundData[sdir]=-2;if(tPdatafile[i]=="N")DataMan.arPicData[sdir]=-2;if(tSearchMethod[i]!="A")DataMan.arCoordData[sdir]=-2;nOutPage[i]=parseInt(tOutPage[i]);UnifyInfo.arPageNo[i]=parseInt(tPageNo[i]);}
var prepage=0;var curpage;var accuno=0;var k=0;for(i=1;i<alen;i++){curpage=nOutPage[i];if(prepage<curpage){accuno+=curpage-prepage-1;UnifyInfo.arPageAccuNo[k]=accuno;UnifyInfo.arDir[k]=tOutDir[0];UnifyInfo.arOutPage[k]=prepage;k++;}
else accuno--;accuno+=UnifyInfo.arPageNo[i];UnifyInfo.arPageAccuNo[k]=accuno;UnifyInfo.arDir[k]=tOutDir[i];UnifyInfo.arOutPage[k]=curpage;k++;accuno++;prepage=curpage;}
if(curpage<=nOutPage[0]){UnifyInfo.arPageAccuNo[k]=parseInt(aaa[2]);UnifyInfo.arDir[k]=tOutDir[0];UnifyInfo.arOutPage[k]=curpage;}
UnifyInfo.dirLen=UnifyInfo.arDir.length;UnifyInfo.thisPageNo=UnifyInfo.arPageNo[0];ConnectMan.load_fileseqAllData();console.log("info.js : load_unifyOutData() : "+urlstr+" : "+xmlHttp.readyState);}
else{console.log("[Error] info.js : load_unifyOutData() : "+urlstr+" : "+xmlHttp.status);}}
xmlHttp.send();}
ConnectMan.load_fileseqAllData=function(){var cDir=UnifyInfo.arDir[ConnectMan.currIdx];if(FileInfo.seqFile[cDir]=="F")ConnectMan.load_fileseqData(cDir);else if(FileInfo.seqFile[cDir]=="X")ConnectMan.load_bookxmlData(cDir);else do_afterFileseqDataLoaded();}
ConnectMan.load_fileseqData=function(currDir){FileInfo.arFileConf[currDir]=new Array();FileInfo.arFileName[currDir]=new Array();var urlstr=FileInfo.dirFilePath("fileseq.txt",currDir,"*");var xmlHttp=new XMLHttpRequest();xmlHttp.open("GET",urlstr);xmlHttp.onreadystatechange=function(){if(xmlHttp.readyState!==4)return;if(xmlHttp.status===200){var restr=xmlHttp.responseText.replace(/^\s*|\s*$/g,'');var lines=restr.split("\n");var alen=lines.length;var pos,tstr,sconf,sname;for(var i=0;i<alen;i++){tstr=lines[i].trim();if(tstr===""||tstr===undefined)continue;pos=tstr.indexOf(":");if(pos===-1)continue;FileInfo.arFileConf[currDir].push(tstr.substr(0,pos));FileInfo.arFileName[currDir].push(tstr.substr(pos+1));}
do_afterFileseqDataLoaded();console.log("info.js : load_fileseqData() : "+urlstr+" : "+xmlHttp.readyState);}
else{console.log("[Error] info.js : load_fileseqData() : "+urlstr+" : "+xmlHttp.status);}}
xmlHttp.send();}
ConnectMan.load_bookxmlData=function(currDir){FileInfo.arFileConf[currDir]=new Array();FileInfo.arFileName[currDir]=new Array();BookInfo.arTitle[currDir]=new Array();BookInfo.arSearch[currDir]=new Array();BookInfo.arCont[currDir]=new Array();SoundInfo.arPageSoundFile[currDir]=new Array();var urlstr=FileInfo.dirFilePath("bookdata"+FileInfo.xmlExt,currDir,"*");var xmlHttp=new XMLHttpRequest();xmlHttp.open("GET",urlstr);xmlHttp.onreadystatechange=function(){if(xmlHttp.readyState!==4)return;if(xmlHttp.status===200){var xmlDoc=xmlHttp.responseXML;var docuNode=xmlDoc.getElementsByTagName("document")[0];var pageNodes=docuNode.getElementsByTagName("page");var pagenode,tno,tstr,tfname;var alen=pageNodes.length;for(var i=0;i<alen;i++){pagenode=pageNodes[i];tno=parseInt(pagenode.getAttribute('no'))-1;if(!pagenode.getAttribute('image')){FileInfo.arFileConf[currDir][tno]="20000";tfname="";}
else{FileInfo.arFileConf[currDir][tno]="10000";tfname=pagenode.getAttribute('image');}
FileInfo.arFileName[currDir][tno]=tfname;BookInfo.arTitle[currDir][tno]=pagenode.getAttribute('title');tstr=pagenode.getAttribute('search');if(tstr&&tstr!=="")BookInfo.arSearch[currDir][tno]=tstr;tstr=pagenode.getAttribute('sound');if(tstr&&tstr!=="")SoundInfo.arPageSoundFile[currDir][tfname]=tstr;}
do_afterFileseqDataLoaded();console.log("info.js : load_bookxmlData() : "+urlstr+" : "+xmlHttp.readyState);}
else{console.log("[Error] info.js : load_bookxmlData() : "+urlstr+" : "+xmlHttp.status);}}
xmlHttp.send();}
ConnectMan.load_mokchaData=function(showkd){var urlstr=FileInfo.dirFilePath("mokcha.txt","","*");var xmlHttp=new XMLHttpRequest();xmlHttp.open("GET",urlstr);if(xmlHttp.overrideMimeType)xmlHttp.overrideMimeType("text/plain; charset=utf-8");xmlHttp.onreadystatechange=function(){if(xmlHttp.readyState!==4)return;if(xmlHttp.status===200){var restr=xmlHttp.responseText.replace(/^\s*|\s*$/g,'');if(showkd==="hori"){do_horimokchaData(restr);if(SkinInfo.spacerbtn.substr(0,2)==="03")SpacerObj.do_horimokchaData(restr);}
else if(showkd==="mhori")do_mhorimokchaData(restr);else if(showkd==="spacer")SpacerObj.do_horimokchaData(restr);console.log("info.js : load_mokchaData() : "+urlstr+" : "+xmlHttp.readyState);}
else{console.log("[Error] info.js : load_mokchaData() : "+urlstr+" : "+xmlHttp.status);}}
xmlHttp.send();}
ConnectMan.load_mediaData=function(){var urlstr=FileInfo.mediaFilePath("media.txt","","*");var xmlHttp=new XMLHttpRequest();xmlHttp.open("GET",urlstr);if(xmlHttp.overrideMimeType)xmlHttp.overrideMimeType("text/plain; charset=utf-8");xmlHttp.onreadystatechange=function(){if(xmlHttp.readyState!==4)return;if(xmlHttp.status===200){var restr=xmlHttp.responseText.replace(/^\s*|\s*$/g,'');var lines=restr.split("\n");var alen=lines.length;var tstr,pos,linestr,idx;if(SoundInfo.musicCfg===""){for(var i=0;i<alen;i++){tstr=lines[i].trim();if(tstr==="")continue;pos=tstr.indexOf(":");if(pos===-1)continue;linestr=tstr.split(":");MediaObj.arMediaTitle.push(linestr[1]);MediaObj.arMediaFile.push(linestr[2]);}}
else{var selectedSound=SoundInfo.musicCfg.split(",");for(var i=0;i<alen;i++){tstr=lines[i].trim();if(tstr==="")continue;pos=tstr.indexOf(":");if(pos===-1)continue;linestr=tstr.split(":");idx=selectedSound.indexOf(linestr[2]);if(idx!=-1){MediaObj.arMediaTitle[idx]=linestr[1];MediaObj.arMediaFile[idx]=linestr[2];}}}
do_afterMediaDataLoaded();console.log("info.js : load_mediaData() : "+urlstr+" : "+xmlHttp.readyState);}
else{console.log("[Error] info.js : load_mediaData() : "+urlstr+" : "+xmlHttp.status);}}
xmlHttp.send();}
ConnectMan.load_cataboxData=function(){var urlstr=FileInfo.catFilePath("catakind.txt","*");var xmlHttp=new XMLHttpRequest();xmlHttp.open("GET",urlstr);if(xmlHttp.overrideMimeType)xmlHttp.overrideMimeType("text/plain; charset=utf-8");xmlHttp.onreadystatechange=function(){DataMan.cataboxData=xmlHttp.readyState;if(xmlHttp.readyState===4){if(xmlHttp.status===200){var restr=xmlHttp.responseText.replace(/^\s*|\s*$/g,'');var lines=restr.split("\n");var alen=lines.length;var tstr,tcode,arstr;for(var i=0;i<alen;i++){tstr=lines[i].trim();if(tstr==="")continue;arstr=tstr.split("|");tcode=arstr[0];cataBoxData.expCode.push(tcode);cataBoxData.expData[tcode]=tstr;}
console.log("info.js : load_cataboxData() : "+urlstr+" : "+xmlHttp.readyState);}
else{console.log("[Error] info.js : load_cataboxData() : "+urlstr+" : "+xmlHttp.status);}
ConnectMan.load_flashData();}}
xmlHttp.send();}
ConnectMan.load_flashData=function(){var urlstr=FileInfo.flashFilePath("flash.txt","*");var xmlHttp=new XMLHttpRequest();xmlHttp.open("GET",urlstr);if(xmlHttp.overrideMimeType)xmlHttp.overrideMimeType("text/plain; charset=utf-8");xmlHttp.onreadystatechange=function(){if(xmlHttp.readyState===4){if(xmlHttp.status===200){var restr=xmlHttp.responseText.replace(/^\s*|\s*$/g,'');var lines=restr.split("\n");var alen=lines.length;var tstr,tcode,arstr;for(var i=0;i<alen;i++){tstr=lines[i].trim();if(tstr==="")continue;arstr=tstr.split(":");tcode=arstr[2];LinkInfo.arFlashLink[tcode]=tstr;}
console.log("info.js : load_flashData() : "+urlstr+" : "+xmlHttp.readyState);}
else{console.log("[Error] info.js : load_flashData() : "+urlstr+" : "+xmlHttp.status);}
after_openingData();}}
xmlHttp.send();}
ConnectMan.load_linkData=function(sdir){ConnectMan.currDir=sdir;DataMan.arLinkData[sdir]=-1;var urlstr=FileInfo.dirFilePath("alink.txt",sdir,"*");var xmlHttp=new XMLHttpRequest();xmlHttp.open("GET",urlstr,true);if(xmlHttp.overrideMimeType)xmlHttp.overrideMimeType("text/plain; charset=utf-8");xmlHttp.onreadystatechange=function(){DataMan.arLinkData[sdir]=xmlHttp.readyState;if(xmlHttp.readyState===4){if(xmlHttp.status===200){LinkInfo.arExpData[sdir]=new Array();LinkInfo.arExpDataPtr[sdir]=new Array();var restr=xmlHttp.responseText.replace(/^\s*|\s*$/g,'');var lines=restr.split("\n");var alen=lines.length;var tstr,k,fname,pos;for(var i=0;i<alen;i++){tstr=lines[i].trim();if(tstr==="")continue;pos=tstr.indexOf("\t");if(pos===-1)continue;k=LinkInfo.arExpData[sdir].push(tstr)-1;fname=tstr.substr(0,pos);LinkInfo.arExpDataPtr[sdir][fname]=(LinkInfo.arExpDataPtr[sdir][fname]==undefined)?String(k):LinkInfo.arExpDataPtr[sdir][fname]+";"+k;}
console.log("info.js : load_linkData() : "+urlstr+" : "+xmlHttp.readyState);}
else{console.log("[Error] info.js : load_linkData() : "+urlstr+" : "+xmlHttp.status);}
show_linkData();}}
xmlHttp.send();}
ConnectMan.load_soundData=function(sdir){ConnectMan.currDir=sdir;DataMan.arSoundData[sdir]=-1;var urlstr=FileInfo.dirFilePath("pagesound.txt","","*");var xmlHttp=new XMLHttpRequest();xmlHttp.open("GET",urlstr,true);xmlHttp.onreadystatechange=function(){DataMan.arSoundData[sdir]=xmlHttp.readyState;if(xmlHttp.readyState!==4)return;if(xmlHttp.status===200){SoundInfo.arPageSoundFile[sdir]=new Array();var restr=xmlHttp.responseText.replace(/^\s*|\s*$/g,'');var lines=restr.split("\n");var alen=lines.length;var tstr,k,fname,pos;for(var i=0;i<alen;i++){tstr=lines[i].trim();if(tstr==="")continue;pos=tstr.indexOf(":");if(pos===-1)continue;fname=tstr.substr(0,pos);SoundInfo.arPageSoundFile[sdir][fname]=tstr.substr(pos+1);}
console.log("info.js : load_soundData() : "+urlstr+" : "+xmlHttp.readyState);load_pagesoundData();}
else{console.log("[Error] info.js : load_soundData() : "+urlstr+" : "+xmlHttp.status);}}
xmlHttp.send();}
ConnectMan.load_coordData=function(sdir,caller){ConnectMan.currDir=sdir;DataMan.arCoordData[sdir]=-1;var urlstr=FileInfo.dirFilePath("coords"+FileInfo.xmlExt,sdir,"*");var xmlHttp=new XMLHttpRequest();xmlHttp.open("GET",urlstr);if(xmlHttp.overrideMimeType)xmlHttp.overrideMimeType("text/plain; charset=utf-8");xmlHttp.onreadystatechange=function(){if(xmlHttp.readyState!==4)return;if(xmlHttp.status===200){SearchInfo.arSearchSize[sdir]=new Array();SearchInfo.arSearchCoords[sdir]=new Array();SearchInfo.arSearchRot[sdir]=new Array();var restr=xmlHttp.responseText.replace(/^\s*|\s*$/g,'');restr=restr.replace(/>\s*/g,'>');restr=restr.replace(/\s*</g,'<');var strRegex=new RegExp("<page>([\\s\\S]*?)<\\/page>","gi");var noRegex=new RegExp("<no>(.*?)<\\/no>","m");var sizeRegex=new RegExp("<size>(.*?)<\\/size>","m");var rotRegex=new RegExp("<rotation>(.*?)<\\/rotation>","m");var coordRegex=new RegExp("<coords>([\\s\\S]*?)<\\/coords>","m");var match,matchstr,noMatch,sizeMatch,coordMatch,rotMatch;var spage,ssise,stext,srot,k=0;while((match=strRegex.exec(restr))!=null){matchstr=match[1];noMatch=noRegex.exec(matchstr);spage=(noMatch==null)?"":noMatch[1];sizeMatch=sizeRegex.exec(matchstr);ssize=(sizeMatch==null)?"":sizeMatch[1];rotMatch=rotRegex.exec(matchstr);srot=(rotMatch==null)?"":rotMatch[1];coordMatch=coordRegex.exec(matchstr);stext=(coordMatch==null)?"":coordMatch[1];if(spage==""||stext=="")continue;var n=parseInt(spage);SearchInfo.arSearchSize[sdir][n]=ssize;SearchInfo.arSearchCoords[sdir][n]=stext;if(srot==="")srot="0";SearchInfo.arSearchRot[sdir][n]=parseInt(srot);}
console.log("info.js : load_coordData() : "+urlstr+" : "+xmlHttp.readyState);}
else{console.log("[Error] info.js : load_coordData() : "+urlstr+" : "+xmlHttp.status);}
DataMan.arCoordData[sdir]=xmlHttp.readyState;if(caller==="search")show_searchResult();}
xmlHttp.send();}
ConnectMan.load_descriptData=function(sdir){ConnectMan.currDir=sdir;DataMan.arPicData[sdir]=-1;var urlstr=FileInfo.dirFilePath("picdata.txt",sdir,"*");var xmlHttp=new XMLHttpRequest();xmlHttp.open("GET",urlstr);if(xmlHttp.overrideMimeType)xmlHttp.overrideMimeType("text/plain; charset=utf-8");xmlHttp.onreadystatechange=function(){DataMan.arPicData[sdir]=xmlHttp.readyState;if(xmlHttp.readyState!==4)return;if(xmlHttp.status===200){LinkInfo.arImgDescript[sdir]=new Array();var restr=xmlHttp.responseText.replace(/^\s*|\s*$/g,'');var lines=restr.split("\n");var alen=lines.length;var tstr,tcode,arstr;for(var i=0;i<alen;i++){tstr=lines[i].trim();if(tstr==="")continue;pos=tstr.indexOf("\t");if(pos===-1)continue;fname=tstr.substr(0,pos);LinkInfo.arImgDescript[sdir][fname]=tstr.substr(pos+1);}
console.log("info.js : load_descriptData() : "+urlstr+" : "+xmlHttp.readyState);}
else{console.log("[Error] info.js : load_descriptData() : "+urlstr+" : "+xmlHttp.status);}
}
xmlHttp.send();}}
function do_afterFileseqDataLoaded(){if(UnifyInfo.fileseqLoadOnce===true){ConnectMan.currIdx++;if(ConnectMan.currIdx<UnifyInfo.dirLen)ConnectMan.load_fileseqAllData();else{onload_func2();}}
else onload_func2();}
