function init_link(s1){LinkObj={timer:undefined,audioPlayer:undefined,seq:0,deviation:1,curScale:1.0,mpbWidth:228,mpbHeight:174,scrapeTxt:'',ttaObj:undefined,ttaLR:true,ttaN:0,ttaPlaying:false,followTTa:false,markTTaArea:false,arTTaMP3:[],delHtRules:true,arLinkUnit:[],arPolygon:[],arPolyUnitIdx:[],arInfoidx:[],arHtRules:[],arHighlight:[],outClip:[],userClip:[]
};LinkObj.audioPlayer=document.getElementById('linkoutaudio');if(s1!=="")LinkObj.arHtRules.push(s1);LinkObj.show_linkData2=function(leftRight,sdir,fname,parentObj){var sa=LinkInfo.get_indexPtr(sdir,fname);var srule,pidx,uidx,rect,ardim,img;for(var i=0,alen=sa.length;i<alen;i++){pidx=sa[i];srule=LinkInfo.get_linkRuleFromPointer(pidx);if(srule==="")continue;var linkunit=new LinkUnit(pidx);linkunit.lr=leftRight;linkunit.set_linkvar(srule);uidx=LinkObj.arLinkUnit.push(linkunit)-1;if(linkunit.head==="[swp]"){LinkObj.make_swapShape(leftRight,uidx,linkunit);}
else if(LinkInfo.bool_makeShape(linkunit)===true){var alink=document.createElementNS("http://www.w3.org/2000/svg","a");alink.setAttributeNS("http://www.w3.org/1999/xlink","xlink:href","javascript:LinkObj.link_click(undefined,"+uidx+","+leftRight+",this)");parentObj.appendChild(alink);var newpoly=document.createElementNS("http://www.w3.org/2000/svg","polygon");newpoly.setAttribute("points",LinkObj.get_svgPoints(LinkInfo.arLinkPoly[pidx],0,0));newpoly.setAttribute("cursor","pointer");newpoly.setAttribute("fill",LinkInfo.displayColor);newpoly.setAttribute("fill-opacity",LinkInfo.displayAlpha);if(Action.showLinkText===true){newpoly.setAttribute("onmouseover","LinkObj.link_over(evt,"+uidx+",'"+LinkInfo.arLinkExpl[pidx]+"',"+leftRight+")");newpoly.setAttribute("onmouseout","LinkObj.link_out(evt)");}
newpoly.setAttribute("onmousemove","LinkObj.link_move(evt)");alink.appendChild(newpoly);LinkObj.arPolygon.push(newpoly);LinkObj.arPolyUnitIdx.push(uidx);if(CataInfo.incview==="m"&&linkunit.head==="[flv]"){alink=document.createElementNS("http://www.w3.org/2000/svg","a");alink.setAttributeNS("http://www.w3.org/1999/xlink","xlink:href","javascript:LinkObj.link_click(undefined,"+uidx+","+leftRight+",this)");parentObj.appendChild(alink);rect=LinkInfo.arLinkPoly[pidx].boundRect;ardim=get_suitDimen(LinkObj.mpbWidth,LinkObj.mpbHeight,rect.width*LinkPtrObj.wRatio,rect.height*LinkPtrObj.hRatio);img=document.createElementNS("http://www.w3.org/2000/svg","image");img.setAttributeNS("http://www.w3.org/1999/xlink","xlink:href",ServerInfo.serverUrl+"/skin5/sndctrl/movieplaybtn.png");img.setAttribute("width",ardim[0]);img.setAttribute("height",ardim[1]);img.setAttribute("x",rect.x*LinkPtrObj.wRatio+(rect.width*LinkPtrObj.wRatio-ardim[0])/2);img.setAttribute("y",rect.y*LinkPtrObj.hRatio+(rect.height*LinkPtrObj.hRatio-ardim[1])/2);img.setAttribute("class","mpbAlpha");alink.appendChild(img);LinkObj.add_outClip(img,undefined,uidx,pidx,leftRight,7,0,0);}}
LinkObj.do_loadWhenStart(leftRight,uidx,linkunit);}}
LinkObj.remove_linkData=function(bool){LinkObj.remove_highlight(bool);var nodes=LinkPtrObj.leftLink.childNodes;for(var i=nodes.length-1;i>=0;i--){LinkPtrObj.leftLink.removeChild(nodes[i]);}
if(!LinkPtrObj.rightLink)return;var nodes=LinkPtrObj.rightLink.childNodes;for(var i=nodes.length-1;i>=0;i--){LinkPtrObj.rightLink.removeChild(nodes[i]);}
if(SoundItemObj){SoundItemObj.unload();SoundItemObj=undefined;}}
LinkObj.refresh_linkData=function(){LinkObj.remove_linkData(false);show_linkData();}
LinkObj.add_outClip=function(divobj,imgobj,uidx,pidx,leftRight,nkd,nw,nh){var iconobj=new IconObj(divobj,imgobj,uidx,pidx,leftRight,nkd,nw,nh);LinkObj.outClip.push(iconobj);return iconobj;}
LinkObj.loc_linkData=function(){var i,alen,uidx,pidx;for(i=0,alen=LinkObj.arPolygon.length;i<alen;i++){uidx=LinkObj.arPolyUnitIdx[i];pidx=LinkObj.arLinkUnit[uidx].pointer;LinkObj.arPolygon[i].setAttribute("points",LinkObj.get_svgPoints(LinkInfo.arLinkPoly[pidx],0,0));}
var rect,posx,posy,pw,ph,divobj,tkd,leftRight,ardim;for(i=0,alen=LinkObj.outClip.length;i<alen;i++){icbj=LinkObj.outClip[i];tkd=icbj.nkd;pidx=icbj.polyidx;leftRight=icbj.lr;rect=LinkInfo.arLinkPoly[pidx].boundRect;posx=Math.floor(rect.x*LinkPtrObj.wRatio);if(leftRight===false)posx+=(Action.drawCondition<1)?ScreenInfo.smImageWidth:ScreenInfo.bigImageWidth;posy=Math.floor(rect.y*LinkPtrObj.hRatio);pw=Math.floor(rect.width*LinkPtrObj.wRatio);ph=Math.floor(rect.height*LinkPtrObj.hRatio);divobj=document.getElementById("linkdiv"+pidx);switch(tkd){case 1:divobj.style.left=posx+"px";divobj.style.top=posy+"px";divobj.style.width=pw+"px";divobj.style.height=ph+"px";break;case 2:divobj.style.left=posx+"px";divobj.style.top=posy+"px";if(LinkInfo.sameIconSize===false){icbj.iconImage.style.width=Math.floor(icbj.nwidth*LinkPtrObj.wRatio)+"px";icbj.iconImage.style.height=Math.floor(icbj.nheight*LinkPtrObj.hRatio)+"px";divobj.style.width=icbj.iconImage.style.width;divobj.style.height=icbj.iconImage.style.height;}
break;case 3:case 6:divobj.style.left=posx+"px";divobj.style.top=posy+"px";break;case 4:divobj.style.left=posx+"px";divobj.style.top=posy+"px";if(LinkInfo.sameSwapSize===true){divobj.style.width=pw+"px";divobj.style.height=ph+"px";}
else{divobj.style.width=Math.floor(icbj.nwidth*LinkPtrObj.wRatio)+"px";divobj.style.height=Math.floor(icbj.nheight*LinkPtrObj.hRatio)+"px";}
break;case 5:var divw=(Action.drawCondition<1)?ScreenInfo.smImageWidth:ScreenInfo.bigImageWidth;var divh=(Action.drawCondition<1)?ScreenInfo.smImageHeight:ScreenInfo.bigImageHeight;document.getElementById('swspoly'+pidx).setAttribute("points",LinkObj.get_svgPoints(LinkInfo.arLinkPoly[pidx],0,0));document.getElementById('swsimage'+pidx).setAttribute("width",divw);document.getElementById('swsimage'+pidx).setAttribute("height",divh);break;case 7:ardim=get_suitDimen(LinkObj.mpbWidth,LinkObj.mpbHeight,pw,ph);icbj.iconDiv.setAttribute("width",ardim[0]);icbj.iconDiv.setAttribute("height",ardim[1]);icbj.iconDiv.setAttribute("x",rect.x*LinkPtrObj.wRatio+(pw-ardim[0])/2);icbj.iconDiv.setAttribute("y",posy+(ph-ardim[1])/2);break;case 9:Link2Obj.loc_aslideImage(divobj,posx,posy,pw,ph);break;case 11:Link2Obj.loc_oahDocu(divobj,pidx,posx,posy,pw,ph);break;default:}}
if(LinkObj.ttaObj){n=LinkObj.ttaN;rect=LinkInfo.arLinkPoly[n].boundRect;LinkObj.ttaObj.style.left=Math.floor(rect.x*LinkPtrObj.wRatio)+"px";LinkObj.ttaObj.style.top=Math.floor(rect.y*LinkPtrObj.hRatio)+"px";}
LinkObj.loc_linkData2();}
LinkObj.loc_linkData2=function(){var i,alen,icbj,tkd,pidx,nw,nh,divobj;for(i=0,alen=LinkObj.outClip.length;i<alen;i++){icbj=LinkObj.outClip[i];tkd=icbj.nkd;pidx=icbj.polyidx;divobj=document.getElementById("linkdivimg"+pidx);switch(tkd){case 10:nw=icbj.nwidth,nh=icbj.nheight;var tw=nw+2,th=nh+20;if(stageWidth<nw+4){nw=stageWidth-4;tw=nw+2;}
if(stageHeight<nh+33)nh=stageHeight-33;th=nh+33;posx=Math.floor((winRect.width-tw)/2);posy=Math.floor((winRect.height-th)/2);divobj.style.left=posx+"px";divobj.style.top=posy+"px";divobj.style.width=tw+"px";divobj.style.height=th+"px";document.getElementById('docnewin_frame_svg').style.width=tw+"px";document.getElementById('docnewin_frame_svg').style.height=th+"px";document.getElementById('docnewin_iframe').style.width=nw+"px";document.getElementById('docnewin_iframe').style.height=nh+"px";document.getElementById('docnewin_frame_img').setAttribute("x",tw-25);break;default:}}}
LinkObj.link_over=function(e,n,s,lr){if(Action.mouseTouch===false)return;cursorDiv.style.visibility="visible";CursorObj.set_stext(s);CursorObj.do_animate();}
LinkObj.link_move=function(e){if(Action.mouseTouch===false)return;cursorDiv.style.left=(document.documentElement.scrollLeft+e.clientX+13)+"px";cursorDiv.style.top=(document.documentElement.scrollTop+e.clientY+13)+"px";}
LinkObj.link_out=function(e){if(Action.mouseTouch===false)return;CursorObj.stop_animate();}
LinkObj.link_click=function(e,uidx,leftRight,basemc){LinkObj.arLinkUnit[uidx].callDevice="mouseup";LinkObj.go_link(leftRight,uidx,LinkObj.arLinkUnit[uidx],basemc);LinkObj.link_out(e);}
LinkObj.do_loadWhenStart=function(leftRight,uidx,linkunit){if(SoundInfo.soundAppKind==="P"){if((linkunit.ruleKind===0&&linkunit.head===SoundInfo.soundLinkHeader)||(linkunit.ruleKind===1&&linkunit.head2===SoundInfo.soundLinkHeader)){if(leftRight===true)SoundInfo.arLeftMP3.push(uidx);else SoundInfo.arRightMP3.push(uidx);}}
if(linkunit.head==="[sta]"||linkunit.head==="[nta]"||linkunit.head==="[lta]"){linkunit.callDevice="pageload";LinkObj.go_link(leftRight,uidx,linkunit,undefined);}
else if(linkunit.head==="[ico]"){LinkObj.load_linkIcon(leftRight,uidx,linkunit);}
else if(linkunit.head==="[mph]"){LinkObj.arTTaMP3.push(uidx);if(LinkObj.arTTaMP3.length===1)LinkObj.go_link(leftRight,uidx,linkunit,undefined);}
else if(linkunit.head==="[ald]"){Link2Obj.make_aslideImage(leftRight,uidx,linkunit);}}
LinkObj.go_link=function(leftRight,uidx,linkunit,basemc){var linkHead=linkunit.get_actHead();if(linkHead==="[sta]"||linkHead==="[nta]"||linkHead==="[swf]"||linkHead==="[flv]"){if(linkunit.option1==="[center]")LinkObj.load_sfaCenter(leftRight,uidx,linkunit,basemc);else LinkObj.load_sfa(leftRight,uidx,linkunit,basemc);}
else if(linkHead==="[img]"){LinkObj.load_linkImage(leftRight,uidx,linkunit);}
else if(linkHead==="[str]"){LinkObj.load_linkString(leftRight,uidx,linkunit);}
else if(linkHead==="[mp3]"||linkHead==="[mph]"){LinkObj.load_linkSound(leftRight,uidx,linkunit,basemc);}
else if(linkHead==="[ttl]"||linkHead==="[ttn]"){LinkObj.load_ttaSound(leftRight,uidx,linkunit,basemc);}
else if(linkHead==="[swp]"){LinkObj.make_iconswapShape(leftRight,uidx,linkunit);}
else if(linkHead==="[swi]"){LinkObj.make_swapImage(leftRight,uidx,linkunit);}
else if(linkHead==="[sws]"){LinkObj.make_maskImage(leftRight,uidx,linkunit);}
else if(linkHead==="[odh]"||linkHead==="[odw]"){LinkObj.load_outDocu(leftRight,uidx,linkunit,linkHead);}
else if(linkHead==="[lta]"){LinkObj.call_ltaLink(leftRight,uidx,linkunit,basemc);}
else if(linkHead==="[page]"){LinkObj.move_page(linkunit.rule);}
else if(linkHead==="[win]"){LinkObj.call_window(linkunit);}
else if(linkHead==="[tel]"){LinkObj.call_telephone(linkunit.rule);}
else if(linkHead==="[eic]"){eval(linkunit.rule);}
else{simpleLink(linkunit.rule,3);}}
LinkObj.move_page=function(s){if(s.length>1&&s.substr(0,1)==="a"){var n=parseInt(s.substr(1));if(PermitMan.get_directGoPermNumber("link",n,"system")===false)return;go_general(n,"system");}
else{var n=PermitMan.get_directGoPerm("link",s,"","");if(n<0)return;go_general(n,"user");}}
LinkObj.call_window=function(linkunit){var pos=linkunit.option1.indexOf("]");var myvar=linkunit.option1.substr(1,pos-1).split(",");newLink(myvar[0],myvar[1],myvar[2],linkunit.rule);}
LinkObj.call_ltaLink=function(leftRight,uidx,linkunit,basemc){if(linkunit.option1==="[page]")LinkObj.move_page(linkunit.rule);else if(linkunit.option1==="[win]")LinkObj.call_window(linkunit.rule);else if(linkunit.option1==="[eic]")eval(linkunit.rule);else if(linkunit.option1==="[mp3]")LinkObj.load_linkSound(leftRight,uidx,linkunit,basemc);else if(linkunit.option1==="[odh]"||linkunit.option1==="[odw]"){var linkHead=linkunit.get_actHead();LinkObj.load_outDocu(leftRight,uidx,linkunit,linkHead);}
else if(linkunit.option1==="[oah]")Link2Obj.load_oahDocu(leftRight,uidx,linkunit);else simpleLink(linkunit.rule,3);}
LinkObj.call_telephone=function(s){simpleLink("tel:"+s,1);}
LinkObj.load_sfaCenter=function(leftRight,uidx,linkunit,basemc){if(PermitMan.get_staLinkPerm()===false)return;if(LinkObj.has_linkPointer(linkunit.pointer)!==-1)return;var arfname=linkunit.get_actRule();var arflen=arfname.length;var fname=arfname[0];if(arflen===2&&CataInfo.incview==="m")fname=arfname[1];else if(arflen>2)fname=(CataInfo.incview==="d")?arfname[1]:arfname[2];var arstr,contw,conth,ext;var odv=false;if(fname.substr(0,1)==="@"){arstr=fname.split(",");contw=parseInt(arstr[1]);conth=parseInt(arstr[2]);fname=arstr[3];ext=arstr[0].substr(1);odv=true;}
else{if(!LinkInfo.arFlashLink[fname]||LinkInfo.arFlashLink[fname].indexOf(":")<0)return;arstr=LinkInfo.arFlashLink[fname].split(":");contw=parseInt(arstr[3]);conth=parseInt(arstr[4]);ext=get_extension(fname).toLowerCase();}
var tw=contw+WinInfo.get_contexWidth();var th=conth+WinInfo.get_contexHeight();if(CataInfo.incview==="m"){if(tw>stageWidth){tw=stageWidth;th=Math.floor(tw*conth/contw)+WinInfo.get_contexHeight();}
if(th>stageHeight){th=stageHeight;tw=Math.floor((stageHeight-WinInfo.get_contexHeight())*contw/conth);}}
NewinObj.titleHeight=WinInfo.get_titleHeight(SkinInfo.nw2class);var pidx=linkunit.pointer;var qstr="w="+tw+"&h="+th+"&idx="+uidx+"&d="+SkinInfo.mainmenu+"."+SkinInfo.nwclass+"."+CataInfo.incview+"."+CataInfo.cataLang;var s="<div id='newin_frame'></div>"
+"<iframe class='newinobjE"+SkinInfo.nwclass+"' src='./skin5/linkctrwin001."+ServerInfo.progExt+"?"+qstr+"'></iframe>";if(ext==="youtube"){s+="<iframe class='newinobjE"+SkinInfo.nwclass+"' src='"+fname+"' frameborder='0' allowfullscreen></iframe>";}
else if(ext==="gif"){s+="<img src='"+FileInfo.flashFilePath(fname)+"'>\n";}
else{s+="<video id='newin_obj' class='newinobjE"+SkinInfo.nwclass+"' autoplay='autoplay' controls='controls' onerror=\"LinkObj.video_failed(event,1)\">\n";if(odv===true)s+="<source src='"+fname+"' type='video/"+ext+"'>";else s+="<source src='"+FileInfo.flashFilePath(fname)+"' type='video/"+ext+"'>";if(arfname.length>1){ext=get_extension(arfname[1]).toLowerCase();if(odv===true)s+="<source src='"+arfname[1]+"' type='video/"+ext+"'>";else s+="<source src='"+FileInfo.flashFilePath(arfname[1])+"' type='video/"+ext+"'>";}
s+="<p>Your browser does not support the video element.</p>";s+="</video>\n";}
befX=Math.floor((stageWidth-tw)/2);befY=Math.floor((stageHeight-th)/2);Action.set_mainState("ctrwin");newinDiv.style.width=tw+"px";newinDiv.style.height=th+"px";newinDiv.style.left=befX+"px";newinDiv.style.top=befY+"px";newinDiv.innerHTML=s;newinDiv.style.visibility="visible";}
LinkObj.load_sfa=function(leftRight,uidx,linkunit,basemc){if(PermitMan.get_staLinkPerm()===false)return;if(LinkObj.has_linkPointer(linkunit.pointer)!==-1)return;var arfname=linkunit.get_actRule();var arflen=arfname.length;var fname=arfname[0];if(arflen===2&&CataInfo.incview==="m")fname=arfname[1];else if(arflen>2)fname=(CataInfo.incview==="d")?arfname[1]:arfname[2];var arstr,contw,conth,ext;var odv=false;if(fname.substr(0,1)==="@"){arstr=fname.split(",");fname=(arstr.length==4)?arstr[3]:arstr[1];ext=arstr[0].substr(1);odv=true;}
else{ext=get_extension(fname).toLowerCase();}
var pidx=linkunit.pointer;var rect=LinkInfo.arLinkPoly[pidx].boundRect;var posx=Math.floor(rect.x*LinkPtrObj.wRatio);if(leftRight===false)posx+=(Action.drawCondition<1)?ScreenInfo.smImageWidth:ScreenInfo.bigImageWidth;var posy=Math.floor(rect.y*LinkPtrObj.hRatio);var pw=Math.floor(rect.width*LinkPtrObj.wRatio);var ph=Math.floor(rect.height*LinkPtrObj.hRatio);var obj=document.createElement("div");obj.id="linkdiv"+pidx;obj.style.cssText="z-index:3;display:block;position:absolute;left:"+posx+"px;top:"+posy+"px;width:"+pw+"px;height:"+ph+"px";var s="";if(ext==="youtube"){s+="<iframe src='"+fname+"' class='linkmovieFull' frameborder='0' allowfullscreen></iframe>";}
else if(ext==="gif"){s+="<img class='linkmovieFull' src='"+FileInfo.flashFilePath(fname)+"'>\n";}
else{s+="<video class='linkmovieFull' autoplay='autoplay' controls='controls' onerror=\"LinkObj.video_failed(event,2)\">\n";if(odv===true)s+="<source src='"+fname+"' type='video/"+ext+"'>";else s+="<source src='"+FileInfo.flashFilePath(fname)+"' type='video/"+ext+"'>";if(arfname.length>1){ext=get_extension(arfname[1]).toLowerCase();s+=(odv===true)?"<source src='"+arfname[1]+"' type='video/"+ext+"'>":"<source src='"+FileInfo.flashFilePath(arfname[1])+"' type='video/"+ext+"'>";}
s+="<p>Your browser does not support the video element.</p></video>\n";}
if(CataInfo.incview==="m"){setTimeout(function(){obj.innerHTML=s;linkoutDiv.appendChild(obj);LinkObj.add_outClip(obj,undefined,uidx,pidx,leftRight,1,0,0);},100);}
else{obj.innerHTML=s;linkoutDiv.appendChild(obj);LinkObj.add_outClip(obj,undefined,uidx,pidx,leftRight,1,0,0);}}
LinkObj.support_video=function(s){if(!!document.createElement('video').canPlayType){var videoElem=document.createElement("video");if(s==="ogg"){var oggTest=videoElem.canPlayType('video/ogg; codecs="theora, vorbis"');if(oggTest==="probably"||oggTest==="maybe")return true;}
else if(s==="mp4"){var h264Test=vidTest.canPlayType('video/mp4; codecs="avc1.42E01E"');if(h264Test==="probably"||h264Test==="maybe")return true;}
else if(s==="webm"){var webmTest=vidTest.canPlayType('video/webm; codecs="vp8, vorbis"');if(webmTest==="probably"||webmTest==="maybe")return true;}}
return false;}
LinkObj.video_failed=function(e,nkd){console.log(e.target.childNodes[1].src+" : ");switch(e.target.error.code){case e.target.error.MEDIA_ERR_ABORTED:console.log('You aborted the video playback.(failed-1)');break;case e.target.error.MEDIA_ERR_NETWORK:console.log('Network Error.(failed-2)');break;case e.target.error.MEDIA_ERR_DECODE:console.log('The browser does not support the &lt;video&gt;');break;case e.target.error.MEDIA_ERR_SRC_NOT_SUPPORTED:console.log('The browser does not support this video codec.(failed-4)');break;default:console.log('An unknown error occurred.(failed-5)');break;}
if(nkd===1){unload_newin("ctrwin");ctrwinSvg=undefined;}}
LinkObj.go_winToFullscr=function(){newinDiv.style.left="0px";newinDiv.style.top="0px";newinDiv.style.width=stageWidth+"px";newinDiv.style.height=stageHeight+"px";document.getElementById('newin_obj').className="newinobjFull";newinDiv.addEventListener('mousemove',LinkObj.do_mousemoveFullscr);document.getElementById('newin_frame').style.zIndex=3;}
LinkObj.go_winToNormalscr=function(){newinDiv.style.left=befX+"px";newinDiv.style.top=befY+"px";newinDiv.style.width=ctrwinSvg.svgWidth+"px";newinDiv.style.height=ctrwinSvg.svgHeight+"px";document.getElementById('newin_obj').className="newinobjE"+SkinInfo.nwclass;newinDiv.removeEventListener('mousemove',LinkObj.do_mousemoveFullscr);document.getElementById('newin_frame').style.zIndex=1;document.getElementById('newin_frame').style.visibility="visible";}
LinkObj.do_mousemoveFullscr=function(e){if(e.clientY<NewinObj.titleHeight){document.getElementById('newin_frame').style.visibility="visible";}
else{document.getElementById('newin_frame').style.visibility="hidden";}}
LinkObj.load_linkIcon=function(leftRight,uidx,linkunit){var fsrc=FileInfo.catFilePath(linkunit.fname,"");var pidx=linkunit.pointer;var obj=document.createElement("div");obj.id="linkdiv"+pidx;obj.className="linkdivicon";var newImg=new Image();newImg.onload=function(){var rect=LinkInfo.arLinkPoly[pidx].boundRect;var posx=Math.floor(rect.x*LinkPtrObj.wRatio);if(Action.drawCondition<1&&leftRight===false)posx+=ScreenInfo.smImageWidth;else if(Action.drawCondition>0&&Action.togetherEnlarge===true&&leftRight===false)posx+=ScreenInfo.bigImageWidth;var posy=Math.floor(rect.y*LinkPtrObj.hRatio);obj.style.left=posx+"px";obj.style.top=posy+"px";if(LinkInfo.sameIconSize===false){var s="<a href=\"javascript:LinkObj.go_iconlink("+leftRight+","+uidx+",this);\" ";if(Action.showLinkText===true)s+="title='"+LinkInfo.arLinkExpl[pidx]+"'";s+="><img id='linkico"+pidx+"' src='"+fsrc+"' style=\"width:"+Math.floor(newImg.naturalWidth*LinkPtrObj.wRatio)+"px;height:"+Math.floor(newImg.naturalHeight*LinkPtrObj.hRatio)+"px;\"></a>\n";obj.innerHTML=s;}
else{obj.innerHTML="<a href=\"javascript:LinkObj.go_iconlink("+leftRight+","+uidx+",this);\"><img id='linkico"+pidx+"' src='"+fsrc+"'></a>\n";}
linkoutDiv.appendChild(obj);LinkObj.add_outClip(obj,document.getElementById("linkico"+pidx),uidx,pidx,leftRight,2,newImg.naturalWidth,newImg.naturalHeight);}
newImg.src=fsrc;}
LinkObj.go_iconlink=function(leftRight,uidx,basemc){LinkObj.go_link(leftRight,uidx,LinkObj.arLinkUnit[uidx],basemc);}
LinkObj.load_linkImage=function(leftRight,uidx,linkunit){var pidx=linkunit.pointer;if(document.getElementById("linkdivimg"+pidx))return;var fname,stitle="";var pos=linkunit.rule.indexOf(",");if(pos!=-1){stitle=linkunit.rule.substr(0,pos);fname=linkunit.rule.substr(pos+1);}
else{fname=linkunit.rule;}
var rect=LinkInfo.arLinkPoly[pidx].boundRect;var posx=Math.floor(rect.x*LinkPtrObj.wRatio);if(Action.drawCondition<1&&leftRight===false)posx+=ScreenInfo.smImageWidth;else if(Action.drawCondition>0&&Action.togetherEnlarge===true&&leftRight===false)posx+=ScreenInfo.bigImageWidth;var posy=Math.floor(rect.y*LinkPtrObj.hRatio);var fsrc=FileInfo.imageFilePath(fname,"","*");var newImg=new Image();newImg.onload=function(){var tw=newImg.naturalWidth+16;var th=newImg.naturalHeight+37;if(Action.drawCondition<1){if(posx+tw>smRect.right)posx=smRect.right-tw;if(posy+th>smRect.bottom-smRect.y)posy=smRect.bottom-smRect.y-th;else if(posy<cataRect.y-smRect.y)posy=cataRect.y-smRect.y;}
else{if(posx+tw>ScreenInfo.bigImageRect.right)posx=ScreenInfo.bigImageRect.right-tw;if(posy<cataRect.y-ScreenInfo.bigImageRect.y)posy=cataRect.y-ScreenInfo.bigImageRect.y;else if(posy+th>cataRect.bottom-ScreenInfo.bigImageRect.y)posy=cataRect.bottom-ScreenInfo.bigImageRect.y-th;}
var obj=document.createElement("div");obj.id="linkdivimg"+pidx;obj.style.cssText="z-index:5;display:block;position:absolute;left:"+posx+"px;top:"+posy+"px;width:"+tw+"px;height:"+th+"px;";obj.innerHTML="<div class='imgnewin_frame'>"+templ_newinImglink(pidx,leftRight,tw,th,stitle)+"</div><img class='imgnewin_frame_img' src='"+fsrc+"'>\n";linkoutDiv.appendChild(obj);LinkObj.add_outClip(obj,newImg,uidx,pidx,leftRight,3,newImg.naturalWidth,newImg.naturalHeight);}
newImg.src=fsrc;}
LinkObj.load_linkString=function(leftRight,uidx,linkunit){var pidx=linkunit.pointer;if(document.getElementById("linkdivimg"+pidx))return;var showstr=linkunit.rule;var obj=document.createElement("div");obj.className="imgnewin_frame_p_hide";obj.innerHTML=showstr;linkoutDiv.appendChild(obj);var tw=obj.clientWidth+16;var th=obj.clientHeight+37;linkoutDiv.removeChild(obj);var rect=LinkInfo.arLinkPoly[pidx].boundRect;var posx=Math.floor(rect.x*LinkPtrObj.wRatio);if(leftRight===false)posx+=(Action.drawCondition<1)?ScreenInfo.smImageWidth:ScreenInfo.bigImageWidth;var posy=Math.floor(rect.y*LinkPtrObj.hRatio);if(Action.drawCondition<1){if(posx+tw>smRect.right)posx=smRect.right-tw;if(posy+th>smRect.bottom-smRect.y)posy=smRect.bottom-smRect.y-th;else if(posy<cataRect.y-smRect.y)posy=cataRect.y-smRect.y;}
else{if(posx+tw>ScreenInfo.bigImageRect.right)posx=ScreenInfo.bigImageRect.right-tw;if(posy<cataRect.y-ScreenInfo.bigImageRect.y)posy=cataRect.y-ScreenInfo.bigImageRect.y;else if(posy+th>cataRect.bottom-ScreenInfo.bigImageRect.y)posy=cataRect.bottom-ScreenInfo.bigImageRect.y-th;}
var obj=document.createElement("div");obj.id="linkdivimg"+pidx;obj.style.cssText="z-index:6;display:block;position:absolute;left:"+posx+"px;top:"+posy+"px;width:"+tw+"px;height:"+th+"px;";obj.innerHTML="<div class='imgnewin_frame'>"+templ_newinImglink(pidx,leftRight,tw,th,LinkInfo.imgLinkTitle)+"</div><p class=\"imgnewin_frame_p\">"+showstr+"</p>\n";linkoutDiv.appendChild(obj);LinkObj.add_outClip(obj,undefined,uidx,pidx,leftRight,6,0,0);}
LinkObj.unload_linkImage=function(pidx,leftRight){var oidx=LinkObj.has_linkPointer(pidx);if(oidx!==-1)LinkObj.outClip.splice(oidx,1);var obj=document.getElementById("linkdivimg"+pidx);obj.innerHTML="";linkoutDiv.removeChild(obj);}
LinkObj.load_outDocu=function(leftRight,uidx,linkunit,shead){var pidx=linkunit.pointer;if(document.getElementById("linkdivimg"+pidx))return;var aaa=linkunit.rule.split(",");var nw=parseInt(aaa[0]);var nh=parseInt(aaa[1]);var stitle=(aaa.length>3)?aaa[3]:"";var fsrc=FileInfo.imageFilePath(aaa[2],"","*");fsrc+=(aaa[2].indexOf("?")>0)?"&uidx="+uidx:"?uidx="+uidx;var ow=nw,oh=nh;var tw=nw+2,th=nh+20;var posx=0,posy=0;var s="";if(shead==="[odh]"){if(Action.drawCondition<1){posx=Math.floor((smRect.width-tw)/2);posy=Math.floor((smRect.height-th)/2);}
else{posx=Math.floor((stageWidth-tw)/2)-EncObj.encX;posy=Math.floor((stageHeight-th)/2)-EncObj.encY;}
s+="<div class='imgnewin_frame'>"+templ_newinImglink(pidx,leftRight,tw,th,stitle)+"</div>";s+="<iframe class='docnewin_iframe' id='docnewin_iframe' src='"+fsrc+"' style=\"left:1px;top:19px;width:"+nw+"px;height:"+nh+"px;\"></iframe>";}
else{if(stageWidth<nw+4){nw=stageWidth-4;tw=nw+2;}
if(stageHeight<nh+33)nh=stageHeight-33;th=nh+33;posx=Math.floor((winRect.width-tw)/2);posy=Math.floor((winRect.height-th)/2);s+="<div class='docnewin_frame'>"+templ_newinImg2link(pidx,tw,th,stitle)+"</div>";s+="<iframe class='docnewin_iframe' id='docnewin_iframe' src='"+fsrc+"' style=\"left:1px;top:31px;width:"+nw+"px;height:"+nh+"px;\"></iframe>";}
var obj=document.createElement("div");obj.id="linkdivimg"+pidx;obj.style.cssText="z-index:1;display:block;position:absolute;left:"+posx+"px;top:"+posy+"px;width:"+tw+"px;height:"+th+"px;border:1px solid #0081fa;";obj.innerHTML=s;if(shead==="[odh]"){linkoutDiv.appendChild(obj);LinkObj.add_outClip(obj,undefined,uidx,pidx,leftRight,9,ow,oh);}
else{Action.set_mainState("outdoc");newin2Div.appendChild(obj);LinkObj.add_outClip(obj,undefined,uidx,pidx,leftRight,10,ow,oh);}}
LinkObj.unload_outDocu=function(pidx){Action.restoreState();var oidx=LinkObj.has_linkPointer(pidx);if(oidx!==-1)LinkObj.outClip.splice(oidx,1);var obj=document.getElementById("linkdivimg"+pidx);obj.innerHTML="";newin2Div.removeChild(obj);}
LinkObj.make_iconswapShape=function(leftRight,uidx,linkunit){var swpunit,tunit,swpidx=-1;var alen=LinkObj.arLinkUnit.length;for(var i=0;i<alen;i++){tunit=LinkObj.arLinkUnit[i];if(tunit.head==="[swp]"&&tunit.rule===linkunit.rule){swpunit=tunit;swpidx=i;break;}}
if(swpidx===-1){console.log("No the [swp] pointer.");return;}
var n=LinkObj.arPolyUnitIdx.indexOf(swpidx);if(n!==-1){LinkObj.remove_swapShape(n,swpidx,leftRight);}
else{LinkObj.make_swapShape(leftRight,swpidx,swpunit);}}
LinkObj.make_swapShape=function(leftRight,swpidx,swpunit){var newpoly=document.createElementNS("http://www.w3.org/2000/svg","polygon");newpoly.setAttribute("points",LinkObj.get_svgPoints(LinkInfo.arLinkPoly[swpunit.pointer],0,0));newpoly.setAttribute("cursor","pointer");newpoly.setAttribute("fill",LinkInfo.swapColor);newpoly.setAttribute("fill-opacity",LinkInfo.swapAlpha);if(leftRight===true)LinkPtrObj.leftLink.appendChild(newpoly);else LinkPtrObj.rightLink.appendChild(newpoly);LinkObj.arPolygon.push(newpoly);LinkObj.arPolyUnitIdx.push(swpidx);}
LinkObj.remove_swapShape=function(n,idx,leftRight){if(leftRight===true)LinkPtrObj.leftLink.removeChild(LinkObj.arPolygon[n]);else LinkPtrObj.rightLink.removeChild(LinkObj.arPolygon[n]);LinkObj.arPolyUnitIdx.splice(n,1);LinkObj.arPolygon.splice(n,1);}
LinkObj.make_swapImage=function(leftRight,uidx,linkunit){var swiunit,tunit,swiuidx=-1;var alen=LinkObj.arLinkUnit.length;for(var i=0;i<alen;i++){tunit=LinkObj.arLinkUnit[i];if(tunit.head==="[swi]"&&tunit.rule===linkunit.rule){swiunit=tunit;swiuidx=i;break;}}
if(swiuidx===-1){console.log("No the [swi] pointer.");return;}
var pidx=swiunit.pointer;var oidx=LinkObj.has_linkPointer(pidx);if(oidx!==-1){LinkObj.remove_swapImage(pidx,oidx,leftRight);return;}
var fsrc=FileInfo.imageFilePath(swiunit.fname,"","*");var newImg=new Image();newImg.onload=function(){var rect=LinkInfo.arLinkPoly[pidx].boundRect;var posx=Math.floor(rect.x*LinkPtrObj.wRatio);if(leftRight===false)posx+=(Action.drawCondition<1)?ScreenInfo.smImageWidth:ScreenInfo.bigImageWidth;var posy=Math.floor(rect.y*LinkPtrObj.hRatio);var pw,ph;if(LinkInfo.sameSwapSize===true){pw=Math.floor(rect.width*LinkPtrObj.wRatio);ph=Math.floor(rect.height*LinkPtrObj.hRatio);}
else{pw=Math.floor(newImg.naturalWidth*LinkPtrObj.wRatio);ph=Math.floor(newImg.naturalHeight*LinkPtrObj.hRatio);}
var obj=document.createElement("div");obj.id="linkdiv"+pidx;obj.style.cssText="z-index:1;display:block;position:absolute;left:"+posx+"px;top:"+posy+"px;width:"+pw+"px;height:"+ph+"px;";obj.innerHTML="<img src='"+fsrc+"' class='linkmovieFull'>";linkoutDiv.appendChild(obj);LinkObj.add_outClip(obj,newImg,swiuidx,pidx,leftRight,4,newImg.naturalWidth,newImg.naturalHeight);}
newImg.src=fsrc;}
LinkObj.remove_swapImage=function(pidx,oidx,leftRight){if(leftRight===true){LinkPtrObj.leftSearch.removeChild(document.getElementById('swsmask'+pidx));LinkPtrObj.leftSearch.removeChild(document.getElementById('swsimage'+pidx));}
else{LinkPtrObj.rightSearch.removeChild(document.getElementById('swsmask'+pidx));LinkPtrObj.rightSearch.removeChild(document.getElementById('swsimage'+pidx));}
LinkObj.outClip.splice(oidx,1);}
LinkObj.make_maskImage=function(leftRight,uidx,linkunit){var swsunit=undefined;var alen=LinkObj.arLinkUnit.length;for(var i=0;i<alen;i++){tunit=LinkObj.arLinkUnit[i];if(tunit.head==="[sws]"&&tunit.rule===linkunit.rule){swsunit=tunit;break;}}
if(swsunit==undefined){console.log("No the [sws] pointer.");return;}
var pidx=swsunit.pointer;var oidx=LinkObj.has_linkPointer(pidx);if(oidx!==-1){LinkObj.remove_swapImage(pidx,oidx,leftRight);return;}
var fsrc=(Action.drawCondition<1)?FileInfo.imageFilePath(swsunit.fname,"","*"):FileInfo.imageFilePath("b"+swsunit.fname,"","*");var newImg=new Image();newImg.onload=function(){var pw=(Action.drawCondition<1)?ScreenInfo.smImageWidth:ScreenInfo.bigImageWidth;var ph=(Action.drawCondition<1)?ScreenInfo.smImageHeight:ScreenInfo.bigImageHeight;var clipObj=document.createElementNS("http://www.w3.org/2000/svg","clipPath");clipObj.setAttribute("id","swsmask"+pidx);var newpoly=document.createElementNS("http://www.w3.org/2000/svg","polygon");newpoly.setAttribute("id","swspoly"+pidx);newpoly.setAttribute("points",LinkObj.get_svgPoints(LinkInfo.arLinkPoly[pidx],0,0));clipObj.appendChild(newpoly);if(leftRight===true)LinkPtrObj.leftSearch.appendChild(clipObj);else LinkPtrObj.rightSearch.appendChild(clipObj);var imageObj=document.createElementNS("http://www.w3.org/2000/svg","image");imageObj.setAttributeNS("http://www.w3.org/1999/xlink","xlink:href",fsrc);imageObj.setAttribute("preserveAspectRatio","none");imageObj.setAttribute("id","swsimage"+pidx);imageObj.setAttribute("width",pw);imageObj.setAttribute("height",ph);imageObj.setAttribute("clip-path","url(#swsmask"+pidx+")");if(leftRight===true)LinkPtrObj.leftSearch.appendChild(imageObj);else LinkPtrObj.rightSearch.appendChild(imageObj);LinkObj.add_outClip(clipObj,newImg,uidx,pidx,leftRight,5,newImg.naturalWidth,newImg.naturalHeight);}
newImg.src=fsrc;}
LinkObj.load_linkSound=function(leftRight,uidx,linkunit,basemc){if(SoundInfo.soundCtrlLoc==="linkout"){if(LinkObj.ttaPlaying===true&&LinkObj.arTTaMP3.indexOf(uidx)>=0){SoundItemObj.play_interSound(uidx);return;}
LinkObj.ttaPlaying=false;LinkObj.markTTaArea=true;if(SoundItemObj){SoundItemObj.unload();SoundItemObj=undefined;}
LinkObj.load_sounditem(leftRight,uidx,linkunit,undefined);}
else{if(soundctrlSvg)soundctrlSvg.play_interSound(uidx);else{var urlstr=FileInfo.soundFilePath(LinkObj.arLinkUnit[uidx].rule,"","*");load_soundcontrol(uidx,leftRight,urlstr);}}}
LinkObj.load_ttaSound=function(leftRight,uidx,linkunit,basemc){if(LinkObj.ttaPlaying===true)return;var ttaunit,areaunit,tunit;for(var i=0,alen=LinkObj.arLinkUnit.length;i<alen;i++){tunit=LinkObj.arLinkUnit[i];if(tunit.head==="[tta]"&&tunit.rule==linkunit.rule){if(tunit.option1==="")ttaunit=tunit;else if(tunit.option1==="[ctl]")areaunit=tunit;}}
if(ttaunit==undefined){console.log("No the [tta] pointer.");return;}
if(SoundItemObj){SoundItemObj.unload();SoundItemObj=undefined;}
LinkObj.remove_ttaClip();LinkObj.markTTaArea=(linkunit.get_actHead()==="[ttl]")?true:false;LinkObj.followTTa=(linkunit.option1==="[follow]")?true:false;LinkObj.arTTaMP3=new Array();var poly=LinkInfo.arLinkPoly[ttaunit.pointer];for(i=0;i<alen;i++){tunit=LinkObj.arLinkUnit[i];if(tunit.head==="[mp3]"&&leftRight===tunit.lr&&poly.contain(LinkInfo.arLinkPoly[tunit.pointer].boundRect)){LinkObj.arTTaMP3.push(i);}}
if(LinkObj.arTTaMP3.length===0)return;LinkObj.ttaPlaying=true;if(areaunit==undefined)LinkObj.load_sounditem(leftRight,uidx,linkunit,ttaunit);else LinkObj.load_sounditem(leftRight,uidx,linkunit,areaunit);}
LinkObj.load_sounditem=function(leftRight,uidx,linkunit,areaunit){init_sounditem(uidx);if(areaunit==undefined)return;var pidx=areaunit.pointer;var rect=LinkInfo.arLinkPoly[pidx].boundRect;var posx=Math.floor(rect.x*LinkPtrObj.wRatio);if(leftRight===false){if(Action.drawCondition<1)posx+=ScreenInfo.smImageWidth;else if(Action.drawCondition>9&&Action.togetherEnlarge==true)posx+=ScreenInfo.bigImageWidth;}
var posy=Math.floor(rect.y*LinkPtrObj.hRatio);var obj=document.createElement("div");obj.id="linkdiv"+pidx;obj.className="linkdivsoundctrl";obj.style.left=posx+"px";obj.style.top=posy+"px";obj.innerHTML=templ_sounditem();linkoutDiv.appendChild(obj);LinkObj.ttaObj=obj;LinkObj.ttaLR=leftRight;LinkObj.ttaN=pidx;}
LinkObj.remove_outClip=function(){LinkObj.remove_ttaClip();var nodes=linkoutDiv.childNodes;for(var i=nodes.length-1;i>=0;i--){linkoutDiv.removeChild(nodes[i]);}
LinkObj.outClip.length=0;}
LinkObj.remove_ttaClip=function(){if(LinkObj.ttaObj==undefined)return;linkoutDiv.removeChild(LinkObj.ttaObj);LinkObj.ttaObj=undefined;LinkObj.ttaPlaying=false;}
LinkObj.has_linkPointer=function(n){if(LinkObj.outClip.length===0)return-1;for(var i=0;i<LinkObj.outClip.length;i++){var icoj=LinkObj.outClip[i];if(icoj.polyidx===n&&icoj.nkd!==2&&icoj.nkd!==7)return i;}
return-1;}
LinkObj.show_markAreaRule=function(samerule){if(samerule!==""&&samerule!=="*"){LinkObj.arHtRules.push(samerule);}
LinkObj.arHighlight=new Array();if(samerule==="*")return;var k;for(var i=0;i<LinkObj.arPolyUnitIdx.length;i++){k=LinkObj.arPolyUnitIdx[i];if(LinkObj.arHtRules.indexOf(LinkObj.arLinkUnit[k].rule)>=0){LinkObj.arHighlight.push(LinkObj.arPolygon[i]);if(SoundItemObj)SoundItemObj.playedUnitIdx.push(k);}}
if(LinkObj.arHighlight.length===0)return;LinkObj.start_highlight();}
LinkObj.show_markAreaPtr=function(pidx){if(pidx!=undefined)LinkObj.arHtRules.push(pidx);LinkObj.arHighlight=new Array();var k;for(var i=0;i<LinkObj.arPolyUnitIdx.length;i++){k=LinkObj.arPolyUnitIdx[i];if(LinkObj.arHtRules.indexOf(LinkObj.arLinkUnit[k].pointer)>=0){LinkObj.arHighlight.push(LinkObj.arPolygon[i]);if(SoundItemObj)SoundItemObj.playedUnitIdx.push(k);}}
if(LinkObj.arHighlight.length===0)return;LinkObj.start_highlight();}
LinkObj.start_highlight=function(){if(LinkInfo.markingKind==="S"){for(var i=0;i<LinkObj.arHighlight.length;i++){LinkObj.arHighlight[i].setAttribute("fill",LinkInfo.hgLineColor);LinkObj.arHighlight[i].setAttribute("fill-opacity",LinkInfo.hgAlpha);}}
else{LinkObj.seq=0;LinkObj.timer=setInterval(LinkObj.show_highlight,300);}}
LinkObj.show_highlight=function(){for(var i=0;i<LinkObj.arHighlight.length;i++){if(LinkObj.seq%2==0){LinkObj.arHighlight[i].setAttribute("stroke",LinkInfo.hgLineColor);LinkObj.arHighlight[i].setAttribute("stroke-width",LinkInfo.hgLineThick);LinkObj.arHighlight[i].setAttribute("stroke-opacity",LinkInfo.hgAlpha);}
else{LinkObj.arHighlight[i].setAttribute("stroke","none");}}
LinkObj.seq++;}
LinkObj.remove_highlight=function(bool){if(LinkInfo.markingKind==="S"){for(var i=0;i<LinkObj.arHighlight.length;i++){LinkObj.arHighlight[i].setAttribute("fill",LinkInfo.displayColor);LinkObj.arHighlight[i].setAttribute("fill-opacity",LinkInfo.displayAlpha);}
if(LinkObj.delHtRules===true){if(bool===true)LinkObj.arHtRules.length=0;}
else LinkObj.delHtRules=true;}
else{clearInterval(LinkObj.timer);LinkObj.timer=undefined;if(LinkObj.delHtRules===true){if(bool===true)LinkObj.arHtRules.length=0;}
else LinkObj.delHtRules=true;for(var i=0;i<LinkObj.arHighlight.length;i++){LinkObj.arHighlight[i].setAttribute("stroke","none");}}}
LinkObj.show_searchData=function(bool,sdir,npage,parentObj){if(UnifyInfo.classUnify===true)npage=UnifyInfo.get_realNumber(npage,-1);if(SearchInfo.xmlPageGap!==0)npage+=SearchInfo.xmlPageGap;if(!SearchInfo.arSearchSize[sdir][npage]||!SearchInfo.arSearchCoords[sdir][npage])return;var rot=!SearchInfo.arSearchRot[sdir][npage]?0:SearchInfo.arSearchRot[sdir][npage];var arPageSize=SearchInfo.arSearchSize[sdir][npage].split("x");var aw=parseFloat(arPageSize[0]);var ah=parseFloat(arPageSize[1]);var ratioW=(Action.drawCondition<1)?ScreenInfo.smImageWidth/aw:ScreenInfo.bigImageWidth/aw;var ratioH=(Action.drawCondition<1)?ScreenInfo.smImageHeight/ah:ScreenInfo.bigImageHeight/ah;var restr=SearchInfo.arSearchCoords[sdir][npage].replace(/^\s*|\s*$/g,'');var lines=restr.split("\n");var s,pos,ax,ay,bx,by,ox,oy,qx,qy,rtxt,r;for(var i=0,alen=lines.length;i<alen;i++){s=lines[i];pos=s.indexOf(":");if(pos<0)continue;rtxt=(SearchInfo.distinctCase===true)?LinkObj.get_searchTxt(s.substr(0,pos)):LinkObj.get_searchTxtCase(s.substr(0,pos).toLowerCase());if(rtxt==="")continue;r=s.substr(pos+1).split(" ");ox=parseFloat(r[0]);oy=parseFloat(r[1]);qx=parseFloat(r[2]);qy=parseFloat(r[3]);if(ox<0||ox>aw||oy<0||oy>ah||qx<0||qx>aw||qy<0||qy>ah)continue;if(rot===90){ax=(aw-oy)*ratioW;ay=(ah-qx)*ratioH;bx=(aw-qy)*ratioW;by=(ah-ox)*ratioH;}
else if(rot===180){ax=(aw-qx)*ratioW;ay=qy*ratioH;bx=(aw-ox)*ratioW;by=oy*ratioH;}
else if(rot===270){ax=(aw-qy)*ratioW;ay=(ah-ox)*ratioH;bx=(aw-oy)*ratioW;by=(ah-qx)*ratioH;}
else{ax=ox*ratioW;ay=(ah-oy)*ratioH;bx=qx*ratioW;by=(ah-qy)*ratioH;}
parentObj.appendChild(LinkObj.get_searchRect(ax,by,bx-ax,ay-by));}}
LinkObj.get_searchTxt=function(s){for(var i=0;i<SearchInfo.arqtxt.length;i++){if(s.indexOf(SearchInfo.arqtxt[i])>=0)return SearchInfo.arqtxt[i];}
return"";}
LinkObj.get_searchTxtCase=function(s){for(var i=0;i<SearchInfo.arqtxt.length;i++){if(s.indexOf(SearchInfo.arqtxt[i].toLowerCase())>=0)return SearchInfo.arqtxt[i];}
return"";}
LinkObj.remove_searchData=function(){var nodes=LinkPtrObj.leftSearch.childNodes;for(var i=nodes.length-1;i>=0;i--){LinkPtrObj.leftSearch.removeChild(nodes[i]);}
if(ScreenInfo.onesmc===true)return;var nodes=LinkPtrObj.rightSearch.childNodes;for(var i=nodes.length-1;i>=0;i--){LinkPtrObj.rightSearch.removeChild(nodes[i]);}}
LinkObj.refresh_searchResult=function(){LinkObj.remove_searchData();show_searchResult();}
LinkObj.get_svgPoints=function(poly,posx,posy){var s=Math.floor(poly.points[0].x*LinkPtrObj.wRatio-posx)+","+Math.floor(poly.points[0].y*LinkPtrObj.hRatio-posy);for(var i=1;i<poly.faces;i++){s+=" "+Math.floor(poly.points[i].x*LinkPtrObj.wRatio-posx)+","+Math.floor(poly.points[i].y*LinkPtrObj.hRatio-posy);}
return s;}
LinkObj.show_coordsData=function(bool,sdir,npage,parentObj){if(UnifyInfo.classUnify===true)npage=UnifyInfo.get_realNumber(npage,-1);if(!SearchInfo.arSearchSize[sdir][npage]||!SearchInfo.arSearchCoords[sdir][npage])return;var arPageSize=SearchInfo.arSearchSize[sdir][npage].split("x");var aw=parseFloat(arPageSize[0]);var ah=parseFloat(arPageSize[1]);var ratioW=(Action.drawCondition<1)?ScreenInfo.smImageWidth/aw:ScreenInfo.bigImageWidth/aw;var ratioH=(Action.drawCondition<1)?ScreenInfo.smImageHeight/ah:ScreenInfo.bigImageHeight/ah;var restr=SearchInfo.arSearchCoords[sdir][npage].replace(/^\s*|\s*$/g,'');var lines=restr.split("\n");var cx,cy;var s,stext,pos,ax,ay,bx,by,ox,oy,qx,qy,rtxt,r,exchangeNum,isFax=false,faxseq;for(var i=0,alen=lines.length;i<alen;i++){s=lines[i];pos=s.lastIndexOf(":");if(pos<0)continue;stext=s.substr(0,pos);if(stext.toLowerCase().substr(0,3)==="fax"){isFax=true;faxseq=0;continue;}
if(isFax===true){rtxt=LinkObj.get_phone2Txt(stext);if(rtxt==""){faxseq++;if(faxseq>3)isFax=false;continue;}
else{isFax=false;continue;}}
r=s.substr(pos+1).split(" ");ox=parseFloat(r[0]);oy=parseFloat(r[1]);qx=parseFloat(r[2]);qy=parseFloat(r[3]);if(ox<0||ox>aw||oy<0||oy>ah||qx<0||qx>aw||qy<0||qy>ah)continue;ax=Math.floor(ox*ratioW);ay=Math.floor((ah-oy)*ratioH);bx=Math.floor(qx*ratioW);by=Math.floor((ah-qy)*ratioH);if(SearchInfo.coordTeleLink===true){if(exchangeNum===""){exchangeNum=LinkObj.get_exchangeNum(stext);if(exchangeNum!==""){cx=ax,cy=ay;continue;}}
rtxt=LinkObj.get_phoneTxt(stext);if(rtxt===""){rtxt=LinkObj.get_phone2Txt(stext);if(rtxt!==""){if(exchangeNum!==""){rtxt=exchangeNum+rtxt;ax=cx,ay=cy;}
else rtxt=SearchInfo.areaCode+rtxt;}}
exchangeNum="";if(rtxt!==""){var newrect=LinkObj.get_searchRect(ax,by,bx-ax,ay-by);newrect.setAttribute("class","pntrcsr");newrect.setAttribute("onclick","LinkObj.call_telephone('"+rtxt+"')");parentObj.appendChild(newrect);continue;}}
if(SearchInfo.coordWebLink===true){rtxt=LinkObj.get_weblinkTxt(stext);if(rtxt==="")continue;var newrect=LinkObj.get_searchRect(ax,by,bx-ax,ay-by);newrect.setAttribute("class","pntrcsr");newrect.setAttribute("onclick","simpleLink('"+rtxt+"',3)");parentObj.appendChild(newrect);}}}
LinkObj.get_phoneTxt=function(s){var stRegex1=/(\+{0,1})82-(\d{1,2})-(\d{3,4})-(\d{4})/;var matches=stRegex1.exec(s);if(matches)return"82"+matches[2]+matches[3]+matches[4];var stRegex2=/0(\d{1,2})[\)-](\d{3,4})-(\d{4})/;var matches2=stRegex2.exec(s);if(matches2)return"0"+matches2[1]+matches2[2]+matches2[3];return"";}
LinkObj.get_exchangeNum=function(s){var stRegex1=/(\d{3,4})/;if((s.length===3||s.length===4)&&stRegex1.exec(s))return s;return"";}
LinkObj.get_phone2Txt=function(s){var stRegex2=/(\d{3,4})-(\d{4})/;matches=stRegex2.exec(s);if(matches)return matches[1]+matches[2];return"";}
LinkObj.get_weblinkTxt=function(s){var wRegex1=/(http|https):\/\/([a-z0-9]+\.)?[a-z0-9][a-z0-9-]*\.[a-z]{2,6}(\/)?/i;var matches=wRegex1.exec(s);if(matches)return s;var wRegex2=/^(www\.)[a-z0-9][a-z0-9-]*\.[a-z]{2,6}(\/)?/i;matches=wRegex2.exec(s);if(matches)return"http://"+s;return"";}
LinkObj.get_searchRect=function(ax,ay,aw,ah){var newrect=document.createElementNS("http://www.w3.org/2000/svg","rect");newrect.setAttribute("fill",SearchInfo.searchColor);newrect.setAttribute("fill-opacity",SearchInfo.searchAlpha);newrect.setAttribute("x",ax);newrect.setAttribute("y",ay);newrect.setAttribute("width",aw);newrect.setAttribute("height",ah);return newrect;}
LinkObj.do_scrapeDown=function(e,bool){tempB=bool;clickX=(bool===true)?e.clientX-smRect.x:e.clientX-smRect.centerPt.x;clickY=e.clientY-smRect.y;e.preventDefault();if(bool===true&&SmcObj.leftApproved===true&&LinkPtrObj.leftImg!=undefined&&FileInfo.coordFile[LinkPtrObj.leftDir]===true){if(DataMan.arCoordData[LinkPtrObj.leftDir]==undefined)ConnectMan.load_coordData(LinkPtrObj.leftDir,"scrape");}
if(bool===false&&SmcObj.rightApproved===true&&LinkPtrObj.rightImg!=undefined&&FileInfo.coordFile[LinkPtrObj.rightDir]===true){if(DataMan.arCoordData[LinkPtrObj.rightDir]==undefined)ConnectMan.load_coordData(LinkPtrObj.rightDir,"scrape");}
Action.mouseDragClip=LinkObj;}
LinkObj.do_mouseDrag=function(e){if(tempB===true&&DataMan.arCoordData[LinkPtrObj.leftDir]!==4)return;if(tempB===false&&DataMan.arCoordData[LinkPtrObj.rightDir]!==4)return;if(Action.mouseDragged===false){Action.mouseDragged=true;if(tempB===true){tempS=SmcObj.leftImgGrp.getAttribute("class");SmcObj.leftImgGrp.setAttribute("class","normcsr");}
else{tempS=SmcObj.rightImgGrp.getAttribute("class");SmcObj.rightImgGrp.setAttribute("class","normcsr");}}
if(tempB===true){befX=e.clientX-smRect.x;LinkObj.show_scrapeData(true,PageInfo.cataDir,PageInfo.currentPage,LinkPtrObj.leftSearch);}
else{befX=e.clientX-smRect.centerPt.x;LinkObj.show_scrapeData(false,PageInfo.cataDir,PageInfo.currentPage+1,LinkPtrObj.rightSearch);}
befY=e.clientY-smRect.y;return true;}
LinkObj.show_scrapeData=function(bool,sdir,npage,parentObj){if(!SearchInfo.arSearchSize[PageInfo.cataDir][npage]||!SearchInfo.arSearchCoords[PageInfo.cataDir][npage])return;LinkObj.remove_searchData();var arPageSize=SearchInfo.arSearchSize[sdir][npage].split("x");var aw=parseFloat(arPageSize[0]);var ah=parseFloat(arPageSize[1]);var ratioW=(Action.drawCondition<1)?ScreenInfo.smImageWidth/aw:ScreenInfo.bigImageWidth/aw;var ratioH=(Action.drawCondition<1)?ScreenInfo.smImageHeight/ah:ScreenInfo.bigImageHeight/ah;var restr=SearchInfo.arSearchCoords[sdir][npage].replace(/^\s*|\s*$/g,'');var lines=restr.split("\n");LinkObj.scrapeTxt="";var bl,pos,ax,ay,bx,by,ox,oy,qx,qy,s,r;var alen=lines.length;if(SearchInfo.scrape==="rect"){for(var i=0;i<alen;i++){s=lines[i];pos=s.indexOf(":");if(pos<0)continue;r=s.substr(pos+1).split(" ");ox=parseFloat(r[0]),oy=parseFloat(r[1]),qx=parseFloat(r[2]),qy=parseFloat(r[3]);if(ox<0||ox>aw||oy<0||oy>ah||qx<0||qx>aw||qy<0||qy>ah)continue;ax=Math.floor(ox*ratioW);ay=Math.floor((ah-qy)*ratioH);bx=Math.floor(qx*ratioW);by=Math.floor((ah-oy)*ratioH);if(clickX<=ax&&ax<=befX&&clickY<=ay&&ay<=befY){LinkObj.scrapeTxt+=" "+s.substr(0,pos);parentObj.appendChild(LinkObj.get_searchRect(ax,ay,bx-ax,by-ay));}}}
else if(SearchInfo.scrape==="line"){for(var i=0;i<alen;i++){s=lines[i];pos=s.indexOf(":");if(pos<0)continue;r=s.substr(pos+1).split(" ");ox=parseFloat(r[0]),oy=parseFloat(r[1]),qx=parseFloat(r[2]),qy=parseFloat(r[3]);if(ox<0||ox>aw||oy<0||oy>ah||qx<0||qx>aw||qy<0||qy>ah)continue;ax=Math.floor(ox*ratioW);ay=Math.floor((ah-qy)*ratioH);bx=Math.floor(qx*ratioW);by=Math.floor((ah-oy)*ratioH);bl=false;if(clickY<=ay&&by<befY)bl=true;else if(clickX<=ax&&ax<=befX&&clickY<=ay&&ay<=befY)bl=true;else if(clickY<=ay&&ay<befY&&befY<by){if(clickX<=ax&&bx<=befX)bl=true;}
else if(ay<clickY&&clickY<=by){if(by<=befY){if(clickX<=ax)bl=true;}
else{if(clickX<=ax&&bx<=befX)bl=true;}}
else if(ay<befY&&befY<=by){if(ax<befX)bl=true;}
if(bl===true){LinkObj.scrapeTxt+=" "+s.substr(0,pos);parentObj.appendChild(LinkObj.get_searchRect(ax,ay,bx-ax,by-ay));}}}}
LinkObj.do_mouseUp=function(e){if(Action.mouseDragged===true){if(LinkObj.scrapeTxt!==""){if(confirm("복사하시겠습니까?")){if(window.clipboardData&&window.clipboardData.setData){clipboardData.setData("Text",LinkObj.scrapeTxt);}
else{document.getElementById("urlcopy").value=LinkObj.scrapeTxt;document.getElementById("urlcopy").select();if(document.execCommand("Copy")===false){prompt('브라우저가 복사기능을 지원하지 않습니다. Ctrl+C 버튼을 눌러주십시오',LinkObj.scrapeTxt);}}}}
Action.mouseDownBlock=true;if(tempB===true)SmcObj.leftImgGrp.setAttribute("class",tempS);else SmcObj.rightImgGrp.setAttribute("class",tempS);LinkObj.remove_searchData();if(SearchInfo.searchMark===true||SearchInfo.useCoords===true)show_searchResult();setTimeout(function(){Action.mouseDownBlock=false},100);}}}
function show_linkData(){LinkObj.arLinkUnit=new Array();LinkObj.arPolygon=new Array();LinkObj.arPolyUnitIdx=new Array();LinkObj.outClip=new Array();LinkObj.arHighlight=new Array();LinkObj.arTTaMP3=new Array();SoundInfo.arLeftMP3=new Array();SoundInfo.arRightMP3=new Array();if(LinkPtrObj.leftImg!=undefined&&FileInfo.linkFile[LinkPtrObj.leftDir]===true&&DataMan.arLinkData[LinkPtrObj.leftDir]==undefined){ConnectMan.load_linkData(LinkPtrObj.leftDir);return;}
if(LinkPtrObj.rightImg!=undefined&&FileInfo.linkFile[LinkPtrObj.rightDir]===true&&DataMan.arLinkData[LinkPtrObj.rightDir]==undefined){ConnectMan.load_linkData(LinkPtrObj.rightDir);return;}
if(SmcObj.leftApproved===true&&LinkPtrObj.leftImg!=undefined&&FileInfo.linkFile[LinkPtrObj.leftDir]===true&&DataMan.arLinkData[LinkPtrObj.leftDir]===4){LinkObj.show_linkData2(true,LinkPtrObj.leftDir,LinkPtrObj.leftName,LinkPtrObj.leftLink);}
if(SmcObj.rightApproved===true&&LinkPtrObj.rightImg!=undefined&&FileInfo.linkFile[LinkPtrObj.rightDir]===true&&DataMan.arLinkData[LinkPtrObj.rightDir]===4){if(Action.drawCondition>2&&EncObj.guidewidth===1)LinkObj.show_linkData2(false,LinkPtrObj.rightDir,LinkPtrObj.rightName,LinkPtrObj.rightLink);else LinkObj.show_linkData2(false,LinkPtrObj.rightDir,LinkPtrObj.rightName,LinkPtrObj.rightLink);}
if(LinkInfo.markingVar!=="")LinkObj.show_markAreaRule('');if(SoundInfo.soundAppKind==="P"){if(SoundInfo.arLeftMP3.length>0){var k=SoundInfo.arLeftMP3[0];var urlstr=FileInfo.soundFilePath(LinkObj.arLinkUnit[k].rule,"","*");load_soundcontrol(k,true,urlstr);}
else if(SoundInfo.arRightMP3.length>0){var k=SoundInfo.arRightMP3[0];var urlstr=FileInfo.soundFilePath(LinkObj.arLinkUnit[k].rule,"","*");load_soundcontrol(k,false,urlstr);}}}
function show_searchResult(){if(SmcObj.leftApproved===true&&LinkPtrObj.leftImg!=undefined&&DataMan.arCoordData[LinkPtrObj.leftDir]==undefined){ConnectMan.load_coordData(LinkPtrObj.leftDir,"search");return;}
if(SmcObj.rightApproved===true&&LinkPtrObj.rightImg!=undefined&&DataMan.arCoordData[LinkPtrObj.rightDir]==undefined){ConnectMan.load_coordData(LinkPtrObj.rightDir,"search");return;}
if(LinkPtrObj.leftImg!=undefined&&DataMan.arCoordData[LinkPtrObj.leftDir]===4){if(SearchInfo.searchMark===true)LinkObj.show_searchData(true,LinkPtrObj.leftDir,LinkPtrObj.storedPage,LinkPtrObj.leftSearch);if(SearchInfo.useCoords===true)LinkObj.show_coordsData(true,LinkPtrObj.leftDir,LinkPtrObj.storedPage,LinkPtrObj.leftSearch);}
if(LinkPtrObj.rightImg!=undefined&&DataMan.arCoordData[LinkPtrObj.rightDir]===4){if(SearchInfo.searchMark===true)LinkObj.show_searchData(false,LinkPtrObj.rightDir,LinkPtrObj.storedPage+1,LinkPtrObj.rightSearch);if(SearchInfo.useCoords===true)LinkObj.show_coordsData(false,LinkPtrObj.rightDir,LinkPtrObj.storedPage+1,LinkPtrObj.rightSearch);}}
function show_picData(){if(SmcObj.leftApproved===true&&LinkPtrObj.leftImg!=undefined&&FileInfo.picdataFile[LinkPtrObj.leftDir]==true&&DataMan.arPicData[LinkPtrObj.leftDir]==undefined){ConnectMan.load_descriptData(LinkPtrObj.leftDir);return;}
if(SmcObj.rightApproved===true&&LinkPtrObj.rightImg!=undefined&&FileInfo.picdataFile[LinkPtrObj.rightDir]==true&&DataMan.arPicData[LinkPtrObj.rightDir]==undefined){ConnectMan.load_descriptData(LinkPtrObj.rightDir);return;}
var res="";if(LinkPtrObj.leftImg!=undefined&&FileInfo.picdataFile[LinkPtrObj.leftDir]==true&&DataMan.arPicData[LinkPtrObj.leftDir]==4){if(LinkInfo.arImgDescript[LinkPtrObj.leftDir][LinkPtrObj.leftName]){res+=LinkInfo.arImgDescript[LinkPtrObj.leftDir][LinkPtrObj.leftName];}}
if(LinkPtrObj.rightImg!=undefined&&FileInfo.picdataFile[LinkPtrObj.rightDir]==true&&DataMan.arPicData[LinkPtrObj.rightDir]==4){if(LinkInfo.arImgDescript[LinkPtrObj.rightDir][LinkPtrObj.rightName]){res+=(res=="")?LinkInfo.arImgDescript[LinkPtrObj.rightDir][LinkPtrObj.rightName]:"<br>"+LinkInfo.arImgDescript[LinkPtrObj.rightDir][LinkPtrObj.rightName];}}
if(res!=""){descriptDiv.style.visibility="visible";descriptDiv.innerHTML=res;}
else{descriptDiv.style.visibility="hidden";descriptDiv.innerHTML="";}
descriptDiv.style.left=(cataRect.centerPt.x-descriptDiv.clientWidth/2)+"px";}
function load_pagesoundData(){SoundInfo.currState=0;if(SmcObj.leftApproved===true&&LinkPtrObj.leftUrl!==""){if(FileInfo.seqFile[LinkPtrObj.leftDir]==="X"){if(SoundInfo.arPageSoundFile[LinkPtrObj.leftDir][LinkPtrObj.leftName]!=undefined)SoundInfo.currState=1;}
else{if(FileInfo.pagesoundFile[LinkPtrObj.leftDir]===true&&DataMan.arSoundData[LinkPtrObj.leftDir]==undefined){ConnectMan.load_soundData(LinkPtrObj.leftDir);return;}
if(FileInfo.pagesoundFile[LinkPtrObj.leftDir]===true&&DataMan.arSoundData[LinkPtrObj.leftDir]===4){if(SoundInfo.arPageSoundFile[LinkPtrObj.leftDir][LinkPtrObj.leftName]!=="")SoundInfo.currState=1;}}}
if(SmcObj.rightApproved===true&&LinkPtrObj.rightUrl!==""){if(FileInfo.seqFile[LinkPtrObj.rightDir]==="X"){if(SoundInfo.arPageSoundFile[LinkPtrObj.rightDir][LinkPtrObj.rightName]!==""){SoundInfo.currState=(SoundInfo.currState===1)?3:2;}}
else{if(FileInfo.pagesoundFile[LinkPtrObj.rightDir]===true&&DataMan.arSoundData[LinkPtrObj.rightDir]==undefined){ConnectMan.load_soundData(LinkPtrObj.rightDir);return;}
if(FileInfo.pagesoundFile[LinkPtrObj.rightDir]===true&&DataMan.arSoundData[LinkPtrObj.rightDir]===4){if(SoundInfo.arPageSoundFile[LinkPtrObj.rightDir][LinkPtrObj.rightName]!==""){SoundInfo.currState=(SoundInfo.currState==1)?3:2;}}}}
if(SoundInfo.currState===1||SoundInfo.currState===3){var urlstr=FileInfo.soundFilePath(SoundInfo.get_pageSoundFile(1),"","*");load_soundcontrol(-1,true,urlstr);}
else if(SoundInfo.currState===2){var urlstr=FileInfo.soundFilePath(SoundInfo.get_pageSoundFile(2),"","*");load_soundcontrol(-1,false,urlstr);}}
function load_soundcontrol(uidx,leftRight,urlstr){if(urlstr!==""){LinkObj.audioPlayer.setAttribute("src",urlstr);LinkObj.audioPlayer.load();}
var tw=250,th=30;var qstr="w="+tw+"&h="+th+"&idx="+uidx+"&lr="+leftRight;soundDiv.innerHTML="<iframe src='"+FileInfo.skin5FilePath("soundcontrol001.html")+"?"+qstr+"'></iframe>";soundDiv.style.width=tw+"px";soundDiv.style.height=th+"px";loc_soundcontrol();if(uidx===-1)soundDiv.style.visibility="visible";else{var linkunit=LinkObj.arLinkUnit[uidx];if(linkunit.option1!=="[hln]")soundDiv.style.visibility="visible";}}
function loc_soundcontrol(){if(Action.drawCondition<3){if(CataInfo.incview==="m"){soundDiv.style.left=(winRect.right-soundDiv.clientWidth-5)+"px";soundDiv.style.top=(smRect.bottom+soundDiv.clientHeight>cataRect.bottom)?(smRect.bottom-5-soundDiv.clientHeight)+"px":(smRect.bottom+5)+"px";}
else{soundDiv.style.left=smRect.centerPt.x+"px";soundDiv.style.top=(smRect.bottom+5)+"px";}
soundDiv.style.zIndex=31;soundDiv.style.opacity=1;}
else{var tw=250,th=30;soundDiv.style.left=(cataRect.right-tw-5)+"px";soundDiv.style.top=(cataRect.bottom-th-5)+"px";soundDiv.style.zIndex=45;soundDiv.style.opacity=0.7;}}
function unload_soundcontrol(){soundctrlSvg.unload();soundDiv.style.visibility="hidden";soundDiv.innerHTML="";soundctrlSvg=undefined;}
ImgwinObj={curobj:undefined,befX:0,befX:0,befW:0,befH:0,limitX:0,limitR:0,limitT:0,limitB:0};ImgwinObj.do_mousedownTitle=function(e,obj,n,leftRight){clickX=e.clientX;clickY=e.clientY;Action.mouseDragClip=obj;ImgwinObj.curobj=document.getElementById("linkdivimg"+n);ImgwinObj.befX=parseInt(ImgwinObj.curobj.style.left.replace("px",""));ImgwinObj.befY=parseInt(ImgwinObj.curobj.style.top.replace("px",""));ImgwinObj.befW=ImgwinObj.curobj.clientWidth;ImgwinObj.befH=ImgwinObj.curobj.clientHeight;if(Action.drawCondition<1){ImgwinObj.limitX=cataRect.x-smRect.x;ImgwinObj.limitR=cataRect.right-smRect.x;ImgwinObj.limitT=cataRect.y-smRect.y;ImgwinObj.limitB=cataRect.bottom-smRect.y;}
else{ImgwinObj.limitX=cataRect.x-ScreenInfo.bigImageRect.x;ImgwinObj.limitR=cataRect.right-ScreenInfo.bigImageRect.x;ImgwinObj.limitT=cataRect.y-ScreenInfo.bigImageRect.y;ImgwinObj.limitB=cataRect.bottom-ScreenInfo.bigImageRect.y;}}
ImgwinObj.do_mouseDrag=function(e){e.preventDefault();var posX=e.clientX-clickX+ImgwinObj.befX;var posY=e.clientY-clickY+ImgwinObj.befY;if(posX<ImgwinObj.limitX)posX=ImgwinObj.limitX;else if(posX>ImgwinObj.limitR-ImgwinObj.befW)posX=ImgwinObj.limitR-ImgwinObj.befW;if(posY<ImgwinObj.limitT)posY=ImgwinObj.limitT;else if(posY>ImgwinObj.limitB-ImgwinObj.befH)posY=ImgwinObj.limitB-ImgwinObj.befH;ImgwinObj.curobj.style.left=posX+"px";ImgwinObj.curobj.style.top=posY+"px";return true;}
ImgwinObj.do_mouseUp=function(e){}
ImgwinObj.do_touchEnd=function(){}
function templ_newinImglink(pidx,b,w,h,s){var ws;ws="<svg version='1.1' width='"+w+"' height='"+h+"' xmlns='http://www.w3.org/2000/svg' xmlns:xlink='http://www.w3.org/1999/xlink'>"
+"<defs>"
+"<linearGradient id='imgwin_titleGradient"+pidx+"'>"
+"<stop offset='0%' stop-color='#7DAC1E' />"
+"<stop offset='100%' stop-color='#6D951A' />"
+"</linearGradient>"
+"</defs>"
+"<rect x='0' y='0' width='"+w+"' height='"+h+"' fill='#f5f5f5' />"
+"<g onmouseDown=\"ImgwinObj.do_mousedownTitle(evt, ImgwinObj,"+pidx+","+b+");\">"
+"<rect x='0' y='0' width='"+w+"' height='19' fill='url(#imgwin_titleGradient"+pidx+")' />"
+"<text x='3' y='14'>"+s+"</text>"
+"<a xlink:href=\"javascript:LinkObj.unload_linkImage("+pidx+","+b+")\">"
+"<image x='"+(w-17)+"' y='3' width='13' height='13' xlink:href='./skin5/etc/close_img.png' cursor='pointer' /></a>"
+"</g>"
+"</svg>";return ws;}
function templ_newinImg2link(pidx,w,h,s){var ws;ws="<svg version='1.1' id='docnewin_frame_svg' width='"+w+"' height='"+h+"' xmlns='http://www.w3.org/2000/svg' xmlns:xlink='http://www.w3.org/1999/xlink'>"
+"<rect x='0' y='0' width='100%' height='100%' fill='#ffffff' />"
+"<g onmouseDown=\"Newin2Obj.do_mousedownTitle(evt, Newin2Obj,'linkdivimg"+pidx+"');\">"
+"<rect id='docnewin_frame_rect2' x='0' y='0' width='100%' height='31' fill='#dee1e6' />"
+"<text x='8' y='19'>"+s+"</text>"
+"<a xlink:href=\"javascript:LinkObj.unload_outDocu("+pidx+")\">"
+"<image id='docnewin_frame_img' x='"+(w-25)+"' y='8' width='10' height='10' xlink:href='./skin5/etc/close_img2.png' cursor='pointer' /></a>"
+"</g>"
+"</svg>";return ws;}
function init_sounditem(n){SoundItemObj={playTime:0,idx:0,sndState:'play',linkunit:undefined,timer:undefined,followPaused:false,playedUnitIdx:[]};if(LinkObj.ttaPlaying===true)SoundItemObj.idx=LinkObj.arTTaMP3[0];else SoundItemObj.idx=n;SoundItemObj.audioLoaded=function(){SoundItemObj.playTime=LinkObj.audioPlayer.duration;LinkObj.audioPlayer.removeEventListener('loadeddata',SoundItemObj.audioLoaded);}
SoundItemObj.audioEnded=function(){LinkObj.audioPlayer.removeEventListener('ended',SoundItemObj.audioEnded);if(LinkObj.markTTaArea===true)LinkObj.remove_highlight(true);if(LinkObj.ttaPlaying===false)return;var k=LinkObj.arTTaMP3.indexOf(SoundItemObj.idx);if(k===-1){console.log("audioEnded: arTTaMP3 array index error");return;}
k++;var boolStop=false;if(k>=LinkObj.arTTaMP3.length)boolStop=true;else{for(i=k;i<LinkObj.arTTaMP3.length;i++){if(SoundItemObj.playedUnitIdx.indexOf(LinkObj.arTTaMP3[i])===-1){k=i;break;}
k++;}
if(k>=LinkObj.arTTaMP3.length)boolStop=true;}
if(boolStop===true){SoundItemObj.idx=0;SoundItemObj.sndState="stop";return;}
SoundItemObj.idx=LinkObj.arTTaMP3[k];if(LinkObj.followTTa===true)SoundItemObj.timer=window.setTimeout(SoundItemObj.audioEnded2,SoundItemObj.playTime*1000);else SoundItemObj.audioEnded2();}
SoundItemObj.audioEnded2=function(){SoundItemObj.linkunit=LinkObj.arLinkUnit[SoundItemObj.idx];LinkObj.audioPlayer.setAttribute("src",FileInfo.soundFilePath(SoundItemObj.linkunit.rule,"","*"));LinkObj.audioPlayer.load();LinkObj.audioPlayer.addEventListener('loadeddata',SoundItemObj.audioLoaded);LinkObj.audioPlayer.play();LinkObj.audioPlayer.addEventListener('ended',SoundItemObj.audioEnded);if(LinkObj.markTTaArea===true)LinkObj.show_markAreaPtr(SoundItemObj.linkunit.pointer);}
SoundItemObj.play_interSound=function(n){SoundItemObj.idx=n;SoundItemObj.linkunit=LinkObj.arLinkUnit[SoundItemObj.idx];LinkObj.audioPlayer.removeEventListener('ended',SoundItemObj.audioEnded);if(LinkObj.markTTaArea===true)LinkObj.remove_highlight(true);if(LinkObj.followTTa===true&&SoundItemObj.timer){window.clearTimeout(SoundItemObj.timer);SoundItemObj.timer=undefined;}
SoundItemObj.currMode="play";LinkObj.audioPlayer.setAttribute("src",FileInfo.soundFilePath(SoundItemObj.linkunit.rule,"","*"));LinkObj.audioPlayer.load();LinkObj.audioPlayer.addEventListener('loadeddata',SoundItemObj.audioLoaded);LinkObj.audioPlayer.play();LinkObj.audioPlayer.addEventListener('ended',SoundItemObj.audioEnded);if(LinkObj.markTTaArea===true)LinkObj.show_markAreaPtr(SoundItemObj.linkunit.pointer);}
SoundItemObj.playbtnClick=function(){if(SoundItemObj.sndState==="play")return;if(SoundItemObj.sndState==="pause"){if(SoundItemObj.followPaused===true)SoundItemObj.timer=window.setTimeout(SoundItemObj.audioEnded2,SoundItemObj.playTime*1000);else LinkObj.audioPlayer.play();}
else if(SoundItemObj.sndState==="stop")SoundItemObj.audioEnded2();SoundItemObj.sndState="play";SoundItemObj.followPaused=false;}
SoundItemObj.pausebtnClick=function(){if(SoundItemObj.sndState==="pause"||SoundItemObj.sndState==="stop")return;LinkObj.audioPlayer.pause();if(LinkObj.followTTa===true&&SoundItemObj.timer){window.clearTimeout(SoundItemObj.timer);SoundItemObj.timer=undefined;SoundItemObj.followPaused=true;}
SoundItemObj.sndState="pause";}
SoundItemObj.stopbtnClick=function(){SoundItemObj.unload();SoundItemObj.sndState="stop";LinkObj.remove_ttaClip();}
SoundItemObj.unload=function(){if(LinkObj.markTTaArea===true)LinkObj.remove_highlight(true);if(LinkObj.followTTa===true&&SoundItemObj.timer){window.clearTimeout(SoundItemObj.timer);SoundItemObj.timer=undefined;}
SoundItemObj.playedUnitIdx=[];LinkObj.audioPlayer.pause();LinkObj.audioPlayer.removeEventListener('ended',SoundItemObj.audioEnded);LinkObj.audioPlayer.src="";}
SoundItemObj.linkunit=LinkObj.arLinkUnit[SoundItemObj.idx];LinkObj.audioPlayer.setAttribute("src",FileInfo.soundFilePath(SoundItemObj.linkunit.rule,"","*"));LinkObj.audioPlayer.load();LinkObj.audioPlayer.addEventListener('loadeddata',SoundItemObj.audioLoaded);LinkObj.audioPlayer.play();LinkObj.audioPlayer.addEventListener('ended',SoundItemObj.audioEnded);if(LinkObj.markTTaArea===true)LinkObj.show_markAreaPtr(SoundItemObj.linkunit.pointer);LinkObj.audioPlayer.volume=1;}
function show_loginClip(){if(SmcObj.leftApproved===false){loginDiv=document.getElementById("loginsect");loginDiv.style.display="block";loginDiv.style.left=(cataRect.x+(ScreenInfo.smImageWidth-loginDiv.clientWidth)/2)+"px";loginDiv.style.top=(cataRect.centerPt.y-loginDiv.clientHeight/2)+"px";}
else if(SmcObj.rightApproved===false){loginDiv=document.getElementById("loginsect");loginDiv.style.display="block";loginDiv.style.left=(cataRect.centerPt.x+(ScreenInfo.smImageWidth-loginDiv.clientWidth)/2)+"px";loginDiv.style.top=(cataRect.centerPt.y-loginDiv.clientHeight/2)+"px";}}
function hide_loginClip(){loginDiv.style.display="none";loginDiv=undefined;}
function templ_sounditem(){var ws="<a href=\"javascript:SoundItemObj.playbtnClick();\"><img src='./skin5/sndctrl/play_item.png' width='26' height='18' "
+"onmouseover=\"this.src='./skin5/sndctrl/play_item_s.png'\" onmouseout=\"this.src='./skin5/sndctrl/play_item.png'\"></a>"
+"<a href=\"javascript:SoundItemObj.pausebtnClick();\"><img src='./skin5/sndctrl/pause_item.png' width='26' height='18' "
+"onmouseover=\"this.src='./skin5/sndctrl/pause_item_s.png'\" onmouseout=\"this.src='./skin5/sndctrl/pause_item.png'\"></a>"
+"<a href=\"javascript:SoundItemObj.stopbtnClick();\"><img src='./skin5/sndctrl/stop_item.png' width='26' height='18' "
+"onmouseover=\"this.src='./skin5/sndctrl/stop_item_s.png'\" onmouseout=\"this.src='./skin5/sndctrl/stop_item.png'\"></a>";return ws;}